Makefile
netlify.toml

This PR adds an explicit TOML configuration for Netlify (so that the Netlify configuration is also in version control).

Add Netlify config

---

assets/sass/nav.sass
config.toml
content/docs/getting-started/_index.md
content/docs/getting-started/customized-default-settings.md
content/docs/getting-started/helm.md
layouts/partials/docs/nav.html

We can improve this over time but this is a first try at a tiered navigation system.
cc @yasker

Add tiered docs nav

---

assets/sass/style.sass

Change secondary color

---

.gitignore
.htmltest.external.yml
.htmltest.yml
Makefile
assets/sass/style.sass
content/docs/_index.md
content/docs/disaster-recovery-volumes.md
content/docs/restore-statefulset.md
content/docs/settings.md
content/docs/snapshots.md
content/docs/upgrade.md
layouts/_default/baseof.html
layouts/partials/meta.html
netlify.toml

This PR adds a link checker for the site and fixes all existing broken links.
cc @yasker

Add link checker and fix broken links

---

content/docs/architecture.md

Very minor, drive by PR to fix while reading the docs.
Signed-off-by: Sean Escriva <sean.escriva@gmail.com>

spelling: creates

---

content/docs/architecture/driver.md
content/docs/concepts/backups.md
content/docs/contributing/_index.md
content/docs/examples/restore-to-file.md
content/docs/getting-started/quick-start-with-helm.md
content/docs/install/install-with-rancher.md
content/docs/install/uninstall-longhorn.md
content/docs/install/upgrades.md
content/docs/users-guide/backup-and-restore/backupstores-and-backuptargets.md
content/docs/users-guide/backup-and-restore/restore-statefulset.md
content/docs/users-guide/backup-and-restore/restore-to-file.md
content/docs/users-guide/backup-and-restore/scheduling-backups-and-snapshots.md
content/docs/users-guide/distribution-specific-notes/csi-on-k3s.md
content/docs/users-guide/distribution-specific-notes/csi-on-rke-and-coreos.md
content/docs/users-guide/multidisk.md
content/docs/users-guide/storage-tags.md

Remake doc changes from longhorn/longhorn v0.8.1 branch to longhorn.io

---

layouts/partials/javascript.html

Add hoverable anchor links

---

Makefile
content/docs/_index.md
layouts/partials/docs/dashboard.html
layouts/partials/footer.html
layouts/shortcodes/version-list.html

This PR adds a temporary /docs landing page that can direct users to the right place until the redirect issue is addressed.
cc @yasker

Docs landing page

---

assets/sass/style.sass
layouts/partials/css.html
layouts/partials/javascript.html
layouts/partials/navbar.html
layouts/partials/search-bar.html
package.json
yarn.lock

cc @yasker 
They actually finished faster than I expected. Yay!

Add Algolia search bar

---

README.md

Add section on contributing to docs

---

content/docs/0.8.0/install/upgrades.md

https://github.com/longhorn/longhorn/issues/878
https://github.com/longhorn/longhorn/issues/1207

Add instructions to migrate PVs and PVCs for pre v0.7.0 volumes

---

content/docs/0.8.0/users-guide/default-disk-and-node-config.md

https://github.com/longhorn/longhorn/issues/1168

Add doc default-disk-and-node-config.md

---

README.md

Explain how to signoff when contributing to docs

---

content/docs/0.8.0/install/install-with-helm.md

In the clone statement above, the user already cd into `longhorn`.

Fixup path to helm charts

---

content/docs/0.8.1/_index.md

Update to Longhorn v0.8.1

---

content/docs/0.8.1/deploy/install/_index.md

Update installation requirement to add `lsblk`

---

layouts/index.redirects

https://github.com/longhorn/website/issues/65

Redirect docs.longhorn.io to longhorn.io/docs

---

layouts/index.redirects

Continue trying to redirect docs.longhorn.io

---

content/docs/0.8.1/high-availability/recover-volume.md
content/docs/0.8.1/snapshots-and-backups/setup-disaster-recovery-volumes.md

Change restoration to restore

---

content/docs/0.8.0/install/install-with-helm.md

This PR has a merge conflict https://github.com/longhorn/website/pull/28/files so I'm remaking the changes in this PR.

Update Helm installation doc

---

content/docs/0.8.1/advanced-resources/deploy/airgap.md

longhorn/longhorn#1097
Signed-off-by: Mohamed Eldafrawi <mohamed.eldafrawi@rancher.com>

airgap: add instance manager image name limitation

---

content/docs/0.8.1/best-practices.md
content/docs/0.8.1/contributing.md
content/docs/0.8.1/high-availability/recover-volume.md

This PR is intended to put this best practices guide https://github.com/yasker/longhorn/wiki/Best-practices-for-deploying-Longhorn-in-production into the Longhorn docs.

Add best practices guide

---

layouts/index.redirects

@yasker I honestly don't quite understand how this even could work but we'll give it a try.
Fixes #65.

Add docs wildcard domain redirect

---

layouts/index.redirects

This is my last idea for getting docs.longhorn.io to work. Fingers crossed!
cc @yasker

http redirect for docs.longhorn.io

---

content/docs/0.8.0/install/upgrades.md
content/docs/0.8.0/users-guide/settings.md
content/docs/0.8.1/advanced-resources/default-disk-and-node-config.md
content/docs/0.8.1/advanced-resources/deploy/airgap.md
content/docs/0.8.1/advanced-resources/deploy/customizing-default-settings.md
content/docs/0.8.1/advanced-resources/deploy/taint-toleration.md
content/docs/0.8.1/advanced-resources/iscsi.md
content/docs/0.8.1/advanced-resources/migrating-flexvolume.md
content/docs/0.8.1/advanced-resources/os-distro-specific/csi-on-gke.md
content/docs/0.8.1/advanced-resources/troubleshooting.md
content/docs/0.8.1/best-practices.md
content/docs/0.8.1/concepts.md
content/docs/0.8.1/deploy/install/_index.md
content/docs/0.8.1/high-availability/node-failure.md
content/docs/0.8.1/high-availability/recover-volume.md
content/docs/0.8.1/high-availability/recover-without-system.md
content/docs/0.8.1/references/settings.md
content/docs/0.8.1/snapshots-and-backups/backup-and-restore/create-a-backup.md
content/docs/0.8.1/snapshots-and-backups/backup-and-restore/restore-statefulset.md
content/docs/0.8.1/snapshots-and-backups/backup-and-restore/set-backup-target.md
content/docs/0.8.1/snapshots-and-backups/scheduling-backups-and-snapshots.md
content/docs/0.8.1/snapshots-and-backups/setup-a-snapshot.md
content/docs/0.8.1/snapshots-and-backups/setup-disaster-recovery-volumes.md
content/docs/0.8.1/volumes-and-nodes/create-volumes.md
content/docs/0.8.1/volumes-and-nodes/detaching-volumes.md
content/docs/0.8.1/volumes-and-nodes/expansion.md
content/docs/0.8.1/volumes-and-nodes/multidisk.md
content/docs/0.8.1/volumes-and-nodes/storage-tags.md

Edit guides for grammar, style, formatting, clarity

---

layouts/index.redirects

https://github.com/longhorn/website/issues/65

Fix the missing empty line in _redirects

---

content/docs/0.8.1/deploy/accessing-the-ui/longhorn-ingress.md

Fixed ingress controller creation step.
See https://github.com/longhorn/website/pull/100
Signed-off-by: Marco Bellaccini <marco.bellaccini[at!]gmail.com>

Fixed ingress controller creation step upd

---

content/docs/0.8.1/best-practices.md
content/docs/0.8.1/references/settings.md

This PR is intended to address this issue https://github.com/longhorn/longhorn/issues/1332

Update guaranteed engine CPU info

---

content/docs/0.8.1/deploy/install/_index.md

This PR addresses this issue https://github.com/longhorn/website/issues/49

Link to minimum hardware in installation section

---

content/docs/0.8.1/references/settings.md
content/docs/0.8.1/volumes-and-nodes/scheduling.md

This document contains all scheduling related settings with explanations.
https://github.com/longhorn/longhorn/issues/1334

Add scheduling.md for all scheduling settings

---

content/docs/0.8.1/advanced-resources/data-recovery/_index.md
content/docs/0.8.1/advanced-resources/data-recovery/corrupted-replica.md
content/docs/0.8.1/advanced-resources/data-recovery/data-error.md
content/docs/0.8.1/advanced-resources/data-recovery/export-from-replica.md
content/docs/0.8.1/advanced-resources/data-recovery/full-disk.md
content/docs/0.8.1/advanced-resources/data-recovery/recover-without-system.md
content/docs/0.8.1/deploy/upgrade/longhorn-manager.md
content/docs/0.8.1/references/examples.md

The documents in this PR are relevant to this issue https://github.com/longhorn/longhorn/issues/1298
The work on the docs was tracked in this issue https://github.com/longhorn/longhorn/issues/60

Document recovery from server/cluster crash

---

content/docs/0.8.1/advanced-resources/default-disk-and-node-config.md
content/docs/0.8.1/advanced-resources/deploy/customizing-default-settings.md
content/docs/0.8.1/deploy/accessing-the-ui/longhorn-ingress.md
content/docs/0.8.1/references/settings.md

Add more examples to docs 

---

content/docs/0.8.1/deploy/upgrade/longhorn-manager.md
content/docs/0.8.1/high-availability/node-failure.md

Draft for the Volume Attachment recovery behavior.
longhorn/longhorn#820

Add Documentation for the new Volume Attachment Recovery Policy

---

content/docs/0.8.1/best-practices.md
content/docs/0.8.1/deploy/upgrade/upgrade-engine.md
content/docs/0.8.1/references/examples.md

https://github.com/longhorn/longhorn/issues/1429

doc: StorageClass and iscsi live upgrade

---

content/docs/1.0.0/advanced-resources/data-recovery/corrupted-replica.md

docs: Update corrupted-replica.md

---

content/docs/1.0.0/best-practices.md
content/docs/1.0.0/deploy/upgrade/longhorn-manager.md
content/docs/1.0.0/references/settings.md

docs: Remove experimental tag for GuranteedEngineCPU

---

content/docs/1.0.0/deploy/upgrade/upgrade-engine.md

docs: Update upgrade-engine.md

---

content/docs/0.8.1/deploy/upgrade/longhorn-manager.md

Fix the volume migration doc

---

assets/sass/style.sass
config.toml
content/blog/_index.md
content/blog/first-post.md
content/blog/second-post.md
layouts/blog/list.html
layouts/blog/single.html
layouts/partials/blog/content.html
layouts/partials/blog/hero.html
layouts/partials/blog/post-list.html
layouts/partials/content.html

Add blog template

---

content/docs/0.8.0/install/uninstall-longhorn.md
content/docs/0.8.0/install/viewing-ui.md
content/docs/0.8.0/users-guide/troubleshooting.md
content/docs/0.8.1/advanced-resources/troubleshooting.md
content/docs/0.8.1/deploy/uninstall/_index.md
content/docs/1.0.0/advanced-resources/troubleshooting.md
content/docs/1.0.0/deploy/uninstall/_index.md

I used brokenlinkcheck.com to scan for broken external links, addressing this issue https://github.com/longhorn/website/issues/55

Fix broken links

---

content/docs/1.0.0/deploy/accessing-the-ui/longhorn-ingress.md

This PR supersedes #145 due to issues amending the commit with signoff. The changes are the same.
Signed-off-by: Adrian Goins <mon@chus.cc>

update ingress docs

---

content/docs/1.0.0/snapshots-and-backups/backup-and-restore/set-backup-target.md

Add instruction to enable virtual-hosted-style access for S3 backupstore

---

content/docs/1.0.2/deploy/upgrade/_index.md

Fix upgrade instruction for v1.0.2

---

content/docs/1.0.2/deploy/upgrade/longhorn-manager.md

Signed-off-by: Mohamed Eldafrawi <mohamed.eldafrawi@rancher.com>

add upgrade instruction to v1.0.2 for airgap setup

---

content/docs/1.0.2/advanced-resources/deploy/airgap.md
content/docs/1.0.2/contributing.md

Signed-off-by: weifeilong <weifeilong2013@gmail.com>

Update version to v1.0.2

---

README.md

Change the document work flow.

---

content/docs/1.1.0/advanced-resources/deploy/customizing-default-settings.md
content/docs/1.1.0/high-availability/data-locality.md
content/docs/1.1.0/references/settings.md

content/docs/v1.1.0: add document for data locality enhancement feature

---

content/docs/1.1.0/volumes-and-nodes/disks-or-nodes-eviction.md
content/docs/1.1.0/volumes-and-nodes/maintenance.md

Add new document about disks or nodes eviction support and update
maintenance.md parts related to this new support.
https://github.com/longhorn/longhorn/issues/298

docs: Add disks or nodes eviction support

---

content/docs/1.0.2/snapshots-and-backups/backup-and-restore/set-backup-target.md

The UI path pointer seems to be incorrect.

Fix Backup Target Credential Secret path pointer

---

content/docs/0.8.0/getting-started/quick-start-with-helm.md

updated  helm comamnds for helm2 and helm3 for helm2 and helm3 versions on the page.

Update quick-start-with-helm.md  

---

content/docs/1.1.0/advanced-resources/deploy/revision_counter.md
content/docs/1.1.0/references/settings.md

Add revision_counter.md document which describes details about how
revision counter works. Also includes the ways to disable it, and the
expected behavior.
https://github.com/longhorn/longhorn/issues/508

Add disable revision counter feature support document

---

content/docs/1.1.0/references/settings.md
content/docs/1.1.0/snapshots-and-backups/scheduling-backups-and-snapshots.md

Add document for the feature `Allow Recurring Job While Volume Is Detached`

---

content/docs/1.1.0/references/settings.md

https://github.com/longhorn/longhorn/issues/307

Add 'Disable Replica Rebuild' setting

---

content/docs/0.8.1/advanced-resources/deploy/taint-toleration.md
content/docs/1.0.0/advanced-resources/deploy/taint-toleration.md
content/docs/1.0.1/advanced-resources/deploy/taint-toleration.md
content/docs/1.0.2/advanced-resources/deploy/taint-toleration.md

https://github.com/longhorn/website/issues/156

Fix broken link

---

content/docs/1.1.0/references/settings.md

docs: Add setting system-pods-image-pull-policy

---

content/docs/1.1.0/best-practices.md
content/docs/1.1.0/references/settings.md

Also, update the Best Practices guide.
https://github.com/longhorn/longhorn/issues/1701

docs: Add Allow Volume Creation with Degraded Availability

---

content/docs/1.1.0/references/settings.md

https://github.com/longhorn/longhorn/issues/1669

Add 'Auto Cleanup System Generated Snapshot' setting

---

content/docs/1.1.0/high-availability/recover-volume.md
content/docs/1.1.0/references/settings.md

Add document for the setting `Automatically Delete Workload Pod when The Volume Is Detached Unexpectedly`

---

content/docs/1.1.0/what-is-longhorn.md

https://github.com/longhorn/longhorn/issues/6

Add multi-arch support document for arm64 support

---

content/kb/troubleshooting-volume-pvc-xxx-not-scheduled.md

kb: Fix typo

---

content/docs/0.8.0/users-guide/backup-and-restore/create-a-backup.md
content/docs/1.0.2/advanced-resources/deploy/airgap.md
content/docs/1.0.2/deploy/accessing-the-ui/longhorn-ingress.md
content/docs/1.0.2/deploy/upgrade/longhorn-manager.md
content/docs/1.0.2/deploy/upgrade/upgrade-engine.md
content/docs/1.0.2/high-availability/node-failure.md
content/docs/1.1.0/advanced-resources/deploy/airgap.md
content/docs/1.1.0/advanced-resources/deploy/priority-class.md
content/docs/1.1.0/advanced-resources/deploy/revision_counter.md
content/docs/1.1.0/advanced-resources/deploy/taint-toleration.md
content/docs/1.1.0/advanced-resources/troubleshooting.md
content/docs/1.1.0/best-practices.md
content/docs/1.1.0/contributing.md
content/docs/1.1.0/monitoring/integrating-with-rancher-monitoring.md
content/docs/1.1.0/monitoring/kubelet-volume-metrics.md
content/docs/1.1.0/monitoring/metrics.md
content/docs/1.1.0/snapshots-and-backups/backup-and-restore/create-a-backup.md
content/docs/1.1.0/snapshots-and-backups/csi-snapshot-support/create-a-backup-via-csi.md
content/docs/1.1.0/snapshots-and-backups/csi-snapshot-support/enable-csi-snapshot-support.md
content/docs/1.1.0/snapshots-and-backups/csi-snapshot-support/restore-a-backup-via-csi.md
content/docs/1.1.0/volumes-and-nodes/detaching-volumes.md
content/docs/1.1.0/volumes-and-nodes/disks-or-nodes-eviction.md
content/docs/1.1.0/volumes-and-nodes/expansion.md
content/docs/1.1.0/volumes-and-nodes/multidisk.md
content/docs/1.1.0/volumes-and-nodes/node-space-usage.md
content/docs/1.1.0/volumes-and-nodes/scheduling.md
content/docs/1.1.0/volumes-and-nodes/storage-tags.md
content/docs/1.1.0/volumes-and-nodes/volume-size.md
content/docs/1.1.0/what-is-longhorn.md

Note: I removed mentions of project monitoring from the monitoring section because I believe we don't use projects in Rancher v2.5 monitoring.

Edit files in Longhorn v1.1.0 docs branch

---

content/docs/1.1.0/deploy/install/_index.md

https://github.com/longhorn/longhorn/issues/1741

Add DaemonSet way for installing iscsi on each host running Longhorn

---

content/docs/1.0.2/snapshots-and-backups/backup-and-restore/set-backup-target.md

Signed-off-by: cloudoutloud <seanrigby26@gmail.com>
Adding link to AWS region code doc.

Add aws region code link

---

content/blog/kubecon-na-2020.md

blog: fix: KubeCon NA 2020

---

content/docs/0.8.0/install/requirements.md
content/docs/0.8.1/deploy/install/_index.md
content/docs/1.0.0/deploy/install/_index.md
content/docs/1.0.1/deploy/install/_index.md
content/docs/1.0.2/deploy/install/_index.md

See https://github.com/longhorn/longhorn/issues/1984

requirements.md: further explain open-iscsi req

---

content/docs/0.8.1/snapshots-and-backups/backup-and-restore/restore-statefulset.md

Was getting an error due to indentation:
* spec.accessModes: Required value: at least 1 access mode is required
* spec.resources[storage]: Required value
Fixed indentation.

Fix indentation

---

content/docs/1.1.0/deploy/install/_index.md

Docs: update Longhorn iscsi installation documentation

---

content/docs/1.1.0/best-practices.md
content/docs/1.1.0/references/settings.md

Add more descriptions for setting 'Guaranteed Engine CPU'

---

content/docs/1.1.0/references/longhorn-client-python.md

Add document for how to use Longhorn Client Python to opreate Longhorn

---

content/docs/1.0.2/best-practices.md

doc: add SSD/NVMe into best practice guide

---

content/docs/0.8.0/users-guide/longhorn-ingress.md

the file flag was missing was in kubectl apply command

KB : Fix Ingress apply command

---

content/docs/1.1.0/volumes-and-nodes/maintenance.md

docs: Update node maintenance guide

---

content/docs/1.1.0/high-availability/node-failure.md

docs: Update node failure page

---

content/docs/1.1.0/advanced-resources/deploy/airgap.md
content/docs/1.1.0/deploy/upgrade/_index.md
content/docs/1.1.0/deploy/upgrade/longhorn-manager.md
content/docs/1.1.0/deploy/upgrade/upgrade-engine.md

Update the upgrade steps for v1.1.0

---

content/docs/1.0.2/advanced-resources/rwx-workloads.md

Update some broken links to rwx examples

---

content/docs/1.1.0/snapshots-and-backups/backup-and-restore/restore-statefulset.md

The YAML indentation was wrong and should be valid now.

fix: fixed YAML structure

---

content/kb/troubleshooting-volume-readonly-or-io-error.md

kb: Add troubleshooting-volume-readonly-or-io-error.md

---

content/docs/1.1.0/references/settings.md

doc: Add the missed setting descriptions

---

content/blog/longhorn-v1.1.0.md

Longhorn v1.1.0 announcement blog

---

content/docs/1.1.1/deploy/install/_index.md

1. Add description to install `nfs-utils` using deamonset/initcontainer
New Feature.
None
Refs: https://github.com/longhorn/longhorn/issues/2033
None
Signed-off-by: cclhsu <clark.hsu@suse.com>

add description to install nfs using manifest/daemonset (#2033)

---

content/docs/1.1.1/references/settings.md

update settings according to reviews to resolve ticket '[FEATURE] Add new setting descriptions in the doc' (#2153)
1. Update missed field descriptions in settings according to https://github.com/longhorn/longhorn/issues/2153#issuecomment-760532491
2. Remove default values for `Default Engine Image, Default Share Manage Image, Default Instance Manager Image, Latest Longhorn version`.
3. Rearrange fields in alphabetic order.
Improvement.
None
Refs: https://github.com/longhorn/longhorn/issues/2153
None
Signed-off-by: cclhsu <clark.hsu@suse.com>

update settings according to reviews (#2153)

---

content/docs/1.1.1/deploy/upgrade/_index.md
content/docs/1.1.1/deploy/upgrade/auto-uprade-engine.md
content/docs/1.1.1/deploy/upgrade/upgrade-engine.md
content/docs/1.1.1/references/settings.md

Add doc for feature automatically upgrade volumes' engine to the default engine image after upgrading Longhorn

---

content/docs/1.1.1/advanced-resources/backing-image.md
content/docs/1.1.1/references/settings.md

Docs for the new feature Backing image 

---

content/docs/1.1.1/volumes-and-nodes/maintenance.md

Add instruction to delete node from Longhorn.
https://github.com/longhorn/longhorn/issues/2186

Remove nodes from Longhorn

---

content/docs/1.1.1/advanced-resources/deploy/customizing-default-settings.md
content/docs/1.1.1/best-practices.md
content/docs/1.1.1/references/settings.md

docs: Update docs for the enhanced instance manager CPU reservation feature

---

content/docs/1.1.1/snapshots-and-backups/backup-and-restore/set-backup-target.md

Add a new feature for S3 permission supports providing AWS IAM role to the secret other than providing the AWS credential.
https://github.com/longhorn/longhorn/issues/1526

Support AWS IAM Role

---

content/docs/1.1.1/advanced-resources/deploy/customizing-default-settings.md
content/docs/1.1.1/advanced-resources/deploy/priority-class.md
content/docs/1.1.1/advanced-resources/deploy/taint-toleration.md
content/docs/1.1.1/references/settings.md

User need to set tolerations for system components and user-deployed
components separately
longhorn/longhorn#2120

Update document for taint tolerations settings

---

content/docs/1.1.1/deploy/upgrade/longhorn-manager.md

The upgrade note related to the CPU reservation enhancement

---

content/docs/1.1.0/deploy/install/_index.md

Fix small typo on iscsi installation part.

Update _index.md to fix small typo

---

content/blog/kubecon-eu-2020.md
content/blog/kubecon-na-2020.md
content/blog/longhorn-v1.1.0.md
content/blog/performance-scalability-report-aug-2020.md
content/kb/troubleshooting-rwx-mount-ownership-set-to-nobody.md
content/kb/troubleshooting-volume-pvc-xxx-not-scheduled.md
content/kb/troubleshooting-volume-take-long-time-to-mount.md

https://github.com/longhorn/longhorn/issues/2357

Add Kb for "rwx mount ownership set to nobody" issue

---

content/docs/1.1.1/advanced-resources/rancher-cluster-restore.md

Restore cluster with a Rancher snapshot

---

content/kb/troubleshooting-create-support-bundle-with-curl.md

https://github.com/longhorn/longhorn/issues/2458

Add Kb for "create support bundle with cURL"

---

content/project.md

Add Longhorn share manager

---

content/docs/1.1.1/volumes-and-nodes/multidisk.md

Add note about multiple disk with duplicated filesystem ID

---

content/docs/1.1.1/advanced-resources/deploy/customizing-default-settings.md
content/docs/1.1.1/advanced-resources/deploy/node-selector.md
content/docs/1.1.1/advanced-resources/deploy/taint-toleration.md
content/docs/1.1.1/references/settings.md

Add document for node selector feature

---

content/kb/troubleshooting-traefik-2.x-as-ingress-controller.md

https://github.com/longhorn/longhorn/issues/1442

Add knowledge base when use Traefik 2.x as ingress controller

---

content/docs/1.1.1/advanced-resources/data-recovery/export-from-replica.md

Use [shortcode](https://gohugo.io/content-management/shortcodes/) to render the current doc version in the markdown template.

Use release tag for each longhorn release settings

---

content/docs/1.0.0/advanced-resources/data-recovery/export-from-replica.md
content/docs/1.0.0/references/settings.md
content/docs/1.0.1/advanced-resources/data-recovery/export-from-replica.md
content/docs/1.0.1/references/settings.md
content/docs/1.0.2/advanced-resources/data-recovery/export-from-replica.md
content/docs/1.0.2/references/settings.md
content/docs/1.1.0/advanced-resources/data-recovery/export-from-replica.md
content/docs/1.1.0/references/settings.md

Use [shortcode](https://gohugo.io/content-management/shortcodes/) to render the current doc version in the markdown template.

Use release tag

---

content/docs/0.8.0/users-guide/distribution-specific-notes/csi-on-k3s.md
content/docs/0.8.0/users-guide/distribution-specific-notes/csi-on-rke-and-coreos.md
content/docs/0.8.1/advanced-resources/os-distro-specific/csi-on-k3s.md
content/docs/0.8.1/advanced-resources/os-distro-specific/csi-on-rke-and-coreos.md
content/docs/1.0.0/advanced-resources/os-distro-specific/csi-on-k3s.md
content/docs/1.0.0/advanced-resources/os-distro-specific/csi-on-rke-and-coreos.md
content/docs/1.0.1/advanced-resources/os-distro-specific/csi-on-k3s.md
content/docs/1.0.1/advanced-resources/os-distro-specific/csi-on-rke-and-coreos.md
content/docs/1.0.2/advanced-resources/os-distro-specific/csi-on-k3s.md
content/docs/1.0.2/advanced-resources/os-distro-specific/csi-on-rke-and-coreos.md
content/docs/1.1.0/advanced-resources/os-distro-specific/csi-on-k3s.md
content/docs/1.1.0/advanced-resources/os-distro-specific/csi-on-rke-and-coreos.md
content/docs/1.1.1/advanced-resources/os-distro-specific/csi-on-k3s.md
content/docs/1.1.1/advanced-resources/os-distro-specific/csi-on-rke-and-coreos.md

Remove the anchor and use release tag.

Fix anchored URL for setting kubelet root directory

---

content/kb/troubleshooting-default-settings-do-not-persist.md

https://github.com/longhorn/longhorn/issues/2542

Add KB - default setting not persist after upgrade

---

content/docs/0.8.1/deploy/install/_index.md
content/docs/1.0.0/deploy/install/_index.md
content/docs/1.0.1/deploy/install/_index.md
content/docs/1.0.2/deploy/install/_index.md
content/docs/1.1.0/deploy/install/_index.md
content/docs/1.1.1/deploy/install/_index.md

https://github.com/longhorn/longhorn/issues/2573

Add bash to install requirement

---

layouts/partials/blog/content.html
layouts/partials/blog/hero.html
layouts/partials/content.html
layouts/partials/hero.html
layouts/partials/home/features.html
layouts/partials/home/hero.html
layouts/partials/kb/content.html
layouts/partials/kb/hero.html
layouts/partials/navbar.html

The anchor of the class name configured in Algolia is `doc-content`, not `container`.
Ref to https://github.com/algolia/docsearch-configs/blob/680a4c9/configs/longhorn.json#L16-L21
Run the test locally with https://docsearch.algolia.com/docs/run-your-own.
The search result of `nb_hit` increases from 32 to 15649.
The Algolia crawler run every 24 hours https://docsearch.algolia.com/docs/what-is-docsearch#quick-description
So the production Algolia index would be update after this PR merged within 24 hours.
https://github.com/longhorn/longhorn/issues/2155

Fix search partial work

---

content/docs/0.8.1/snapshots-and-backups/backup-and-restore/restore-from-a-backup.md
content/docs/0.8.1/snapshots-and-backups/setup-disaster-recovery-volumes.md
content/docs/1.0.0/snapshots-and-backups/backup-and-restore/restore-from-a-backup.md
content/docs/1.0.0/snapshots-and-backups/setup-disaster-recovery-volumes.md
content/docs/1.0.1/snapshots-and-backups/backup-and-restore/restore-from-a-backup.md
content/docs/1.0.1/snapshots-and-backups/setup-disaster-recovery-volumes.md
content/docs/1.0.2/snapshots-and-backups/backup-and-restore/restore-from-a-backup.md
content/docs/1.0.2/snapshots-and-backups/setup-disaster-recovery-volumes.md
content/docs/1.1.0/snapshots-and-backups/backup-and-restore/restore-from-a-backup.md
content/docs/1.1.0/snapshots-and-backups/setup-disaster-recovery-volumes.md
content/docs/1.1.1/snapshots-and-backups/backup-and-restore/restore-from-a-backup.md
content/docs/1.1.1/snapshots-and-backups/setup-disaster-recovery-volumes.md

https://github.com/longhorn/longhorn/issues/2503

Warn backup restore on XFS filesystem

---

layouts/partials/javascript.html

#305
This depends on https://github.com/algolia/docsearch-configs/pull/4090

Add version facet filter

---

layouts/partials/blog/content.html
layouts/partials/blog/hero.html
layouts/partials/content.html
layouts/partials/hero.html
layouts/partials/home/features.html
layouts/partials/home/hero.html
layouts/partials/kb/content.html
layouts/partials/kb/hero.html
layouts/partials/navbar.html

Add one more layer `<div class="docs-content">...</div>` on the title and the content (docs, blog, knowledge base).

Add div class docs-content

---

content/kb/troubleshooting-recurring-job-stuck-after-detach-attach.md

https://github.com/longhorn/longhorn/issues/2513

Add Kb - Recurring job does not create new jobs after detach and attach

---

layouts/partials/footer.html

Make homepage elegant

---

content/docs/0.8.0/users-guide/backup-and-restore/backupstores-and-backuptargets.md
content/docs/0.8.1/snapshots-and-backups/backup-and-restore/set-backup-target.md
content/docs/1.0.0/snapshots-and-backups/backup-and-restore/set-backup-target.md
content/docs/1.0.1/snapshots-and-backups/backup-and-restore/set-backup-target.md
content/docs/1.0.2/snapshots-and-backups/backup-and-restore/set-backup-target.md
content/docs/1.1.0/snapshots-and-backups/backup-and-restore/set-backup-target.md
content/docs/1.1.1/snapshots-and-backups/backup-and-restore/set-backup-target.md

Rename Minio to MinIO

---

content/docs/0.8.0/_index.md
content/docs/0.8.0/contributing.md
content/docs/0.8.1/contributing.md
content/docs/1.0.0/contributing.md
content/docs/1.0.1/contributing.md
content/docs/1.0.2/contributing.md
content/docs/1.1.0/contributing.md
content/docs/1.1.1/contributing.md

Update contributing guide

---

content/docs/1.2.0/contributing.md
content/docs/1.2.0/snapshots-and-backups/backup-and-restore/set-backup-target.md

[cherry-pick-for-v1.2.0]

---

content/docs/1.1.2/contributing.md
content/docs/1.1.2/snapshots-and-backups/backup-and-restore/set-backup-target.md

[cherry-pick-for-v1.1.2]

---

content/docs/1.1.2/advanced-resources/profiling.md
content/docs/1.1.2/deploy/install/_index.md

https://github.com/longhorn/longhorn/issues/2696

[v1.1.2] add profiling section

---

content/docs/1.2.0/high-availability/auto-balance-replicas.md
content/docs/1.2.0/references/settings.md

https://github.com/longhorn/longhorn/issues/587

Support replica auto-balance

---

content/docs/1.2.0/advanced-resources/profiling.md
content/docs/1.2.0/deploy/install/_index.md

https://github.com/longhorn/longhorn/issues/2696

[v1.2.0] Add profiling sections

---

content/kb/troubleshooting-none-standard-kubelet-dir.md

Feel like we should add this to kb.
https://github.com/longhorn/longhorn/issues/2537

Add Kb - troubleshoot none-standard Kubelet directory

---

layouts/partials/blog/post-list.html
layouts/partials/javascript.html
layouts/partials/kb/post-list.html
static/js/jquery.matchHeight.js
static/js/scripts.js

- Show truncated HTML content
- Use https://github.com/liabru/jquery-match-height to make the card height alignment
**Blog**
- WAS
- IS
**KB**
- WAS
- IS

Enhance blog & kb summary

---

config.toml

Add 1.1.2 in versions

---

config.toml

Add 1.2.0 in versions

---

content/docs/1.1.1/deploy/upgrade/longhorn-manager.md
layouts/partials/meta.html

ref: https://github.com/longhorn/longhorn/issues/2758

Add noindex to old version pages

---

config.toml
content/docs/1.1.2/deploy/upgrade/_index.md
content/docs/1.1.2/deploy/upgrade/longhorn-manager.md
content/docs/1.1.2/deploy/upgrade/upgrade-engine.md

Update v1.1.2 upgrade guide

---

content/docs/1.1.2/references/examples.md

Increase timeoutSeconds to 4

---

content/docs/1.1.2/deploy/upgrade/_index.md
content/docs/1.1.2/deploy/upgrade/upgrade-engine.md

Add note about:
* how to reduce the the chance of hitting the deadlock
* How to recover from the deadlock if it happens
longhorn/longhorn#2697

Add a note about deadlock in old instance manager v1_20201216

---

content/docs/1.1.1/deploy/upgrade/longhorn-manager.md
content/docs/1.1.2/deploy/upgrade/_index.md
content/docs/1.1.2/deploy/upgrade/upgrade-engine.md

ref: https://github.com/longhorn/longhorn/issues/2697

Update 1.1.2 release note

---

content/kb/troubleshooting-volume-filesystem-corruption.md

https://github.com/longhorn/longhorn/issues/2779

Add KB - volume filesystem corruption

---

content/docs/1.2.0/snapshots-and-backups/csi-volume-clone.md

Add doc for volume clone

---

content/docs/1.2.0/deploy/upgrade/_index.md
content/docs/1.2.0/snapshots-and-backups/scheduling-backups-and-snapshots.md

https://github.com/longhorn/longhorn/issues/467

Update Recurring Snapshots and Backups

---

content/docs/1.2.0/references/settings.md
content/docs/1.2.0/volumes-and-nodes/scheduling.md

https://cloud-native.slack.com/archives/CNVPEL9U3/p1629250829158500

docs: Explicit explain how Longhorn identifies a node zone

---

content/docs/1.2.0/deploy/install/_index.md

Make sure user understand the default installation process is not for production usage

---

content/docs/1.2.0/advanced-resources/volume-encryption.md

Add user documentation for volume encryption.
longhorn/longhorn#1859
Signed-off-by: Joshua Moody <joshua.moody@suse.com>

Add Volume encryption documentation

---

content/docs/1.2.0/deploy/important-notes/index.md
content/docs/1.2.0/deploy/uninstall/_index.md
content/docs/1.2.0/deploy/upgrade/_index.md

Add `Important Notes` page

---

content/blog/kubecon-na-2021.md

Add kubecon na 2021 post

---

config.toml
content/promo.md
layouts/_default/baseof.html
layouts/_default/promo.html
layouts/partials/promo/button.html
layouts/partials/promo/features.html
layouts/partials/promo/hero.html

Add promot page

---

content/docs/1.2.1/references/settings.md

Deprecate setting 'disable-replica-rebuild' and merge it into the new setting

---

content/docs/1.1.0/high-availability/recover-volume.md
content/docs/1.1.0/references/examples.md
content/docs/1.1.1/high-availability/recover-volume.md
content/docs/1.1.1/references/examples.md
content/docs/1.1.2/high-availability/recover-volume.md
content/docs/1.1.2/references/examples.md
content/docs/1.2.0/high-availability/recover-volume.md
content/docs/1.2.0/references/examples.md
content/docs/1.2.1/high-availability/recover-volume.md
content/docs/1.2.1/references/examples.md

https://cloud-native.slack.com/archives/CNVPEL9U3/p1632123916152100?thread_ts=1631890074.139400&cid=CNVPEL9U3

Update the StorageClass example and the auto remount description

---

content/docs/1.2.1/references/settings.md

This is suggested by Khushboo.
Longhorn/longhorn#2460

Improve the description for the concurrent rebuild limit setting

---

content/docs/1.2.0/snapshots-and-backups/scheduling-backups-and-snapshots.md

fix recurringjob example format

---

config.toml
content/blog/kubecon-na-2021.md
content/docs/1.2.0/deploy/important-notes/index.md
content/docs/1.2.0/deploy/uninstall/_index.md
content/docs/1.2.0/deploy/upgrade/_index.md
content/docs/1.2.0/references/examples.md
content/docs/1.2.0/snapshots-and-backups/scheduling-backups-and-snapshots.md
content/docs/1.2.0/volumes-and-nodes/create-volumes.md
content/docs/1.2.1/references/examples.md
content/docs/1.2.1/volumes-and-nodes/create-volumes.md
content/promo.md
layouts/_default/baseof.html
layouts/_default/promo.html
layouts/partials/meta.html
layouts/partials/promo/button.html
layouts/partials/promo/features.html
layouts/partials/promo/hero.html

Update v1.2.1 from master cherry-picks

---

content/docs/0.8.0/users-guide/create-volumes.md
content/docs/0.8.1/volumes-and-nodes/workload-identification.md
content/docs/1.0.0/volumes-and-nodes/workload-identification.md
content/docs/1.0.1/volumes-and-nodes/workload-identification.md
content/docs/1.0.2/volumes-and-nodes/workload-identification.md
content/docs/1.1.0/volumes-and-nodes/workload-identification.md
content/docs/1.1.1/volumes-and-nodes/workload-identification.md
content/docs/1.1.2/volumes-and-nodes/workload-identification.md
content/docs/1.2.0/volumes-and-nodes/workload-identification.md

Remove redundant word

---

content/docs/0.8.0/users-guide/create-volumes.md
content/docs/0.8.1/volumes-and-nodes/workload-identification.md
content/docs/1.0.0/volumes-and-nodes/workload-identification.md
content/docs/1.0.1/volumes-and-nodes/workload-identification.md
content/docs/1.0.2/volumes-and-nodes/workload-identification.md
content/docs/1.1.0/volumes-and-nodes/workload-identification.md
content/docs/1.1.1/volumes-and-nodes/workload-identification.md
content/docs/1.1.2/volumes-and-nodes/workload-identification.md
content/docs/1.2.0/volumes-and-nodes/workload-identification.md
content/docs/1.2.1/volumes-and-nodes/workload-identification.md

Cherry pick from master to v1.2.1

---

content/docs/1.2.1/deploy/important-notes/index.md
content/docs/1.2.1/deploy/uninstall/_index.md
content/docs/1.2.1/deploy/upgrade/_index.md

Add Important Notes page

---

content/docs/1.1.2/high-availability/node-failure.md
content/docs/1.2.0/high-availability/node-failure.md
content/docs/1.2.0/references/settings.md
content/docs/1.2.1/high-availability/node-failure.md
content/docs/1.2.1/references/settings.md
content/docs/1.2.2/high-availability/node-failure.md
content/docs/1.2.2/references/settings.md

https://github.com/longhorn/longhorn/issues/2954

Remove volume attachment recovery policy from 1.1.2

---

content/kb/troubleshooting-volume-cannot-be-cleaned-up-after-the-node-of-the-workload-pod-is-down-and-recovered.md

https://github.com/longhorn/longhorn/issues/3080

Add KB doc for volume cleanup issue after node is down and recovered

---

content/docs/0.8.0/install/customizing-default-settings.md
content/docs/0.8.1/advanced-resources/deploy/customizing-default-settings.md
content/docs/1.0.0/advanced-resources/deploy/customizing-default-settings.md
content/docs/1.0.1/advanced-resources/deploy/customizing-default-settings.md
content/docs/1.0.2/advanced-resources/deploy/customizing-default-settings.md
content/docs/1.1.0/advanced-resources/deploy/customizing-default-settings.md
content/docs/1.1.1/advanced-resources/deploy/customizing-default-settings.md
content/docs/1.1.2/advanced-resources/deploy/customizing-default-settings.md
content/docs/1.2.0/advanced-resources/deploy/customizing-default-settings.md
content/docs/1.2.1/advanced-resources/deploy/customizing-default-settings.md
content/docs/1.2.2/advanced-resources/deploy/customizing-default-settings.md

https://github.com/longhorn/longhorn/issues/2954

Remove volume-attachment-recovery-policy from the default settings

---

content/docs/0.8.0/install/upgrades.md
content/docs/0.8.1/deploy/upgrade/_index.md
content/docs/1.0.0/deploy/upgrade/_index.md
content/docs/1.0.1/deploy/upgrade/_index.md
content/docs/1.0.2/deploy/upgrade/_index.md
content/docs/1.1.0/deploy/upgrade/_index.md
content/docs/1.1.1/deploy/upgrade/_index.md
content/docs/1.1.2/deploy/upgrade/_index.md
content/docs/1.2.0/deploy/upgrade/_index.md
content/docs/1.2.1/deploy/upgrade/_index.md
content/docs/1.2.2/deploy/upgrade/_index.md
content/kb/troubleshooting-some-old-instance-manager-pods-are-still-running-after-upgrade.md

Add KB doc for some old instance-manager in longhorn-system are still running after upgrade

---

content/docs/1.1.3/deploy/important-notes/index.md

Add important notes

---

content/docs/1.1.3/deploy/install/_index.md
content/docs/1.1.3/volumes-and-nodes/expansion.md

Longhorn v1.1.3: Raise minimum Kubernetes version to v1.18

---

content/docs/1.1.0/deploy/install/_index.md
content/docs/1.1.1/deploy/install/_index.md
content/docs/1.1.2/deploy/install/_index.md
content/docs/1.1.3/deploy/install/_index.md

https://github.com/longhorn/longhorn/issues/3319
Change the v1.1.x docs only.

Add maximum supported Kubernetes version

---

content/kb/troubleshooting-default-settings-do-not-persist.md

https://github.com/longhorn/longhorn/issues/2570

kb: Update affected longhorn version range

---

content/docs/0.8.0/install/install-with-kubectl.md
content/docs/0.8.1/deploy/install/install-with-kubectl.md
content/docs/1.0.0/deploy/install/install-with-kubectl.md
content/docs/1.0.1/deploy/install/install-with-kubectl.md
content/docs/1.0.2/deploy/install/install-with-kubectl.md
content/docs/1.1.0/deploy/install/install-with-kubectl.md
content/docs/1.1.1/deploy/install/install-with-kubectl.md
content/docs/1.1.2/deploy/install/install-with-kubectl.md
content/docs/1.2.0/deploy/install/install-with-kubectl.md
content/docs/1.2.1/deploy/install/install-with-kubectl.md
content/docs/1.2.2/deploy/install/install-with-kubectl.md
content/docs/1.3.0/advanced-resources/deploy/customizing-default-settings.md
content/docs/1.3.0/deploy/install/install-with-kubectl.md

https://github.com/longhorn/longhorn/issues/2570

doc: Configure settings CR directly, removes longhorn-default-setting ConfigMap

---

content/docs/1.3.0/snapshots-and-backups/backup-and-restore/create-a-backup.md

https://github.com/longhorn/longhorn-manager/pull/1037
https://github.com/longhorn/longhorn/issues/2271

Add note for backup detached volume with CSI

---

content/docs/1.2.3/advanced-resources/deploy/customizing-default-settings.md
content/docs/1.2.3/deploy/upgrade/_index.md
content/docs/1.2.3/snapshots-and-backups/backup-and-restore/set-backup-target.md
content/docs/1.2.3/snapshots-and-backups/scheduling-backups-and-snapshots.md
content/docs/1.2.3/volumes-and-nodes/maintenance.md

Port changes after 1.2.2 from master

---

content/docs/1.2.3/deploy/upgrade/_index.md

Add deprecation note in the upgrade page

---

content/blog/cve-2021-36779-36780.md

Add CVE 2021-36779-36780 blog post

---

content/docs/1.2.3/best-practices.md

Update the supported OS matrix in the best practices.
Signed-off-by: Khushboo <fnu.khushboo@suse.com>

Add the supported OS matrix

---

content/kb/troubleshooting-engine-upgrading-stuck-in-deadlock.md

Add KB: Troubleshooting: Upgrading volume engine is stuck in deadlock

---

content/docs/1.2.3/advanced-resources/cluster-restore/restore-to-a-cluster-contains-data-using-Rancher-snapshot.md
content/docs/1.2.3/advanced-resources/cluster-restore/restore-to-a-new-cluster-using-velero.md

[Backport][v1.2.3]Cluster restore doc

---

content/docs/1.3.0/advanced-resources/cluster-restore/restore-to-a-cluster-contains-data-using-Rancher-snapshot.md
content/docs/1.3.0/advanced-resources/cluster-restore/restore-to-a-new-cluster-using-velero.md

https://github.com/longhorn/longhorn/issues/3367

Add a doc that instructs how users can restore Longhorn to a new cluster 

---

content/docs/1.3.0/references/networking.md

https://github.com/longhorn/longhorn/issues/3513

Add longhorn-manager webhook server port 9443

---

content/docs/1.2.3/volumes-and-nodes/volume-size.md

Signed-off-by: msiddiqui <msiddiqui@cloudera.com>

Spelling correction

---

content/docs/1.1.1/references/settings.md
content/docs/1.1.2/references/settings.md
content/docs/1.1.3/references/settings.md
content/docs/1.2.0/references/settings.md
content/docs/1.2.1/references/settings.md
content/docs/1.2.2/references/settings.md
content/docs/1.2.3/references/settings.md

Signed-off-by: Phan Le <phan.le@suse.com>

Fix node selector example typo

---

content/docs/1.2.3/advanced-resources/volume-encryption.md

https://github.com/longhorn/longhorn/issues/3511
Signed-off-by: Khushboo <fnu.khushboo@suse.com>

Update the encrypted volume expansion content

---

content/docs/1.1.1/references/settings.md
content/docs/1.1.2/references/settings.md
content/docs/1.1.3/references/settings.md
content/docs/1.2.0/references/settings.md
content/docs/1.2.1/references/settings.md
content/docs/1.2.2/references/settings.md
content/docs/1.2.3/references/settings.md

Signed-off-by: Phan Le <phan.le@suse.com>

[Backport v1.1.4] Fix node selector example typo

---

content/docs/1.1.1/references/settings.md
content/docs/1.1.2/references/settings.md
content/docs/1.1.3/references/settings.md
content/docs/1.2.0/references/settings.md
content/docs/1.2.1/references/settings.md
content/docs/1.2.2/references/settings.md
content/docs/1.2.3/references/settings.md

Signed-off-by: Phan Le <phan.le@suse.com>

[Backport v1.2.4] Fix node selector example typo

---

content/blog/_index.md
layouts/blog/single.html

Capitalize the title of the blog page

---

content/docs/1.2.3/advanced-resources/volume-encryption.md

https://github.com/longhorn/longhorn/issues/3511
Removed the online expansion details from encrypted volume expansion page.
Signed-off-by: Khushboo <fnu.khushboo@suse.com>
cc: @innobead @joshimoo

Remove the online expansion info

---

content/docs/1.2.3/deploy/install/_index.md

Add Root and Privileged Permission description

---

content/kb/troubleshooting-instance-manager-pods-are-restarted-every-hour.md

Add KB: Troubleshooting: Instance manager pods are restarted every hour

---

content/docs/1.2.3/advanced-resources/deploy/customizing-default-settings.md

https://github.com/longhorn/longhorn/issues/3578

Add script way to update Longhorn Setting CR from ConfigMap

---

content/docs/1.2.3/advanced-resources/deploy/customizing-default-settings.md

Fix the anchor

---

content/docs/1.2.4/advanced-resources/deploy/customizing-default-settings.md

https://github.com/longhorn/longhorn/issues/3654

Add script way to update Longhorn Setting CR from longhorn-default-setting ConfigMap

---

content/docs/1.2.3/deploy/install/_index.md
content/kb/troubleshooting-open-iscsi-on-rhel.md

https://github.com/longhorn/longhorn/issues/3630

Rhel iscsi

---

.gitignore
content/docs/0.8.0/users-guide/backup-and-restore/backupstores-and-backuptargets.md
content/docs/0.8.1/snapshots-and-backups/backup-and-restore/set-backup-target.md
content/docs/1.0.0/snapshots-and-backups/backup-and-restore/set-backup-target.md
content/docs/1.0.1/snapshots-and-backups/backup-and-restore/set-backup-target.md
content/docs/1.0.2/deploy/uninstall/_index.md
content/docs/1.0.2/snapshots-and-backups/backup-and-restore/set-backup-target.md
content/docs/1.0.2/volumes-and-nodes/create-volumes.md
content/docs/1.1.0/snapshots-and-backups/backup-and-restore/set-backup-target.md
content/docs/1.1.1/snapshots-and-backups/backup-and-restore/set-backup-target.md
content/docs/1.1.2/snapshots-and-backups/backup-and-restore/set-backup-target.md
content/docs/1.1.3/snapshots-and-backups/backup-and-restore/set-backup-target.md
content/docs/1.2.0/snapshots-and-backups/backup-and-restore/set-backup-target.md
content/docs/1.2.1/snapshots-and-backups/backup-and-restore/set-backup-target.md
content/docs/1.2.2/snapshots-and-backups/backup-and-restore/set-backup-target.md
content/docs/1.2.3/snapshots-and-backups/backup-and-restore/set-backup-target.md

Replace docs pointing to master with release

---

content/docs/1.3.0/monitoring/metrics.md

https://github.com/longhorn/longhorn/issues/2940

Add Prometheus metrics for backup

---

content/docs/1.3.0/monitoring/alert-rules-example.md

[Longhorn 3729](https://github.com/longhorn/longhorn/issues/3729)

Fix LonghornNodeDown alert example not work

---

content/docs/1.2.3/deploy/install/_index.md
content/docs/1.2.4/deploy/install/_index.md

https://github.com/longhorn/longhorn/issues/3549

Add detailed list of which directories the longhorn components need

---

content/docs/1.3.0/deploy/install/_index.md

https://github.com/longhorn/longhorn/issues/3549

[BACKPORT-v1.3.0] Add detailed directories Longhorn components required

---

content/docs/1.2.2/deploy/install/install-with-rancher.md
content/docs/1.2.3/deploy/install/install-with-rancher.md
content/docs/1.2.4/deploy/install/install-with-rancher.md

Use Rancher Apps & Marketplace naming

---

content/docs/1.3.0/deploy/install/install-with-rancher.md

[BACKPORT-v1.3.0] Use Rancher Apps & Marketplace naming

---

content/docs/1.3.0/advanced-resources/support-managed-k8s-service/_index.md
content/docs/1.3.0/advanced-resources/support-managed-k8s-service/manage-node-group-on-aks.md
content/docs/1.3.0/advanced-resources/support-managed-k8s-service/manage-node-group-on-eks.md
content/docs/1.3.0/advanced-resources/support-managed-k8s-service/manage-node-group-on-gke.md
content/docs/1.3.0/advanced-resources/support-managed-k8s-service/upgrade-k8s-on-aks.md
content/docs/1.3.0/advanced-resources/support-managed-k8s-service/upgrade-k8s-on-eks.md
content/docs/1.3.0/advanced-resources/support-managed-k8s-service/upgrade-k8s-on-gke.md

https://github.com/longhorn/longhorn/issues/1800

Cloud k8s management

---

content/docs/1.2.4/snapshots-and-backups/csi-snapshot-support/enable-csi-snapshot-support.md

https://github.com/longhorn/longhorn/issues/2214

Use v1 as VolumeSnapshotClass example

---

content/kb/troubleshooting-pod-with-block-volume-is-stuck-in-terminating.md

Add KB: Troubleshooting: Pod with `volumeMode: Block` is stuck in terminating

---

content/kb/troubleshooting-create-support-bundle-with-curl.md

Current script produces an invalid zip file including curl headers.

Fix kb troubleshooting support bundle

---

content/docs/1.1.0/volumes-and-nodes/maintenance.md
content/docs/1.1.1/advanced-resources/backing-image.md
content/docs/1.1.1/volumes-and-nodes/maintenance.md
content/docs/1.1.2/advanced-resources/backing-image.md
content/docs/1.1.2/volumes-and-nodes/maintenance.md
content/docs/1.1.3/advanced-resources/backing-image.md
content/docs/1.1.3/volumes-and-nodes/maintenance.md
content/docs/1.2.0/advanced-resources/backing-image.md
content/docs/1.2.0/volumes-and-nodes/maintenance.md
content/docs/1.2.1/advanced-resources/backing-image.md
content/docs/1.2.1/volumes-and-nodes/maintenance.md
content/docs/1.2.2/advanced-resources/backing-image.md
content/docs/1.2.2/volumes-and-nodes/maintenance.md
content/docs/1.2.3/advanced-resources/backing-image.md
content/docs/1.2.3/volumes-and-nodes/maintenance.md
content/docs/1.2.4/advanced-resources/backing-image.md
content/docs/1.2.4/volumes-and-nodes/maintenance.md
content/docs/1.3.0/advanced-resources/backing-image.md
content/docs/1.3.0/advanced-resources/deploy/customizing-default-settings.md
content/docs/1.3.0/advanced-resources/orphaned-data-cleanup.md
content/docs/1.3.0/volumes-and-nodes/create-volumes.md
content/docs/1.3.0/volumes-and-nodes/maintenance.md

[Longhorn 3529](https://github.com/longhorn/longhorn/issues/3529)
[Longhorn 685](https://github.com/longhorn/longhorn/issues/685)

Update create-volumes.md for PV annotation

---

content/docs/1.3.0/advanced-resources/orphaned-data-cleanup.md

Add UI part
https://github.com/longhorn/longhorn/issues/685
https://github.com/longhorn/longhorn/issues/3853

Update orphaned-data-cleanup doc

---

content/docs/1.3.0/deploy/important-notes/index.md

Add note about supported Kubernetes version in Longhorn v1.3.0

---

content/kb/troubleshooting-unable-to-mount-an-nfs-backup-target.md

[longhorn/longhorn#3576](https://github.com/longhorn/longhorn/issues/3576)

Add KB: Troubleshooting: NFS server setting and mount a NFS storage

---

content/docs/1.3.0/advanced-resources/deploy/storage-network.md
content/docs/1.3.0/references/settings.md

https://github.com/longhorn/longhorn/issues/4081
https://github.com/longhorn/longhorn/issues/2285

storage-network: add doc

---

.gitignore
content/docs/1.3.0/advanced-resources/security/_index.md
content/docs/1.3.0/advanced-resources/security/mtls-support.md
content/docs/1.3.0/advanced-resources/security/volume-encryption.md

I added the documentation for MTLS setup.
I also created a new Security category underneath the advanced resources and moved the volume encryption page into it. 
longhorn/longhorn#3953

Add MTLS documentation

---

content/kb/troubleshooting-unable-to-mount-an-nfs-backup-target.md

Cherry-pick from master to v1.3.0

---

content/docs/1.3.0/high-availability/k8s-cluster-autoscaler.md

https://github.com/longhorn/longhorn/issues/3884

cluster-autoscaler: reword

---

content/docs/1.3.0/deploy/upgrade/_index.md
content/docs/1.3.0/deploy/upgrade/longhorn-manager.md
content/docs/1.3.0/deploy/upgrade/upgrade-engine.md
content/docs/1.3.0/what-is-longhorn.md

Add s390x IBM Z support

---

content/docs/1.3.0/monitoring/prometheus-and-grafana-setup.md

https://github.com/longhorn/longhorn/issues/4094

monitoring-stack: update instructions

---

content/docs/1.3.0/best-practices.md
content/docs/1.3.0/what-is-longhorn.md

Architectures are AMD64A, RM64 (experimental), s390x (experimental)
longhorn/longhorn#4135
Signed-off-by: James Lu <jamesluhz@gmail.com>

Add Arch. section in 'Best Practices'

---

content/docs/1.3.0/advanced-resources/deploy/customizing-default-settings.md

[Longhorn 4174](https://github.com/longhorn/longhorn/issues/4174)

Update the customizing default settings doc

---

content/docs/1.3.0/deploy/install/install-with-helm.md
content/docs/1.3.0/deploy/install/install-with-kubectl.md
content/docs/1.3.0/deploy/upgrade/longhorn-manager.md

[Longhorn 4175](https://github.com/longhorn/longhorn/issues/4175)

Update helm installation and upgrade doc

---

content/docs/1.3.0/deploy/upgrade/longhorn-manager.md

Add migration instruction to upgrade doc

---

content/kb/how-to-migrate-longhorn-chart-installed-in-old-rancher-ui-to-the-chart-in-new-rancher-ui.md

Clarify the upstream cluster
longhorn/longhorn#4235

Rancher chart migration script clarification

---

content/docs/1.3.0/volumes-and-nodes/volume-size.md

https://github.com/longhorn/longhorn/issues/4158

 doc: Update the rebuilding-related volume size description

---

content/docs/0.8.0/what-is-longhorn.md
content/docs/0.8.1/what-is-longhorn.md
content/docs/1.0.0/what-is-longhorn.md
content/docs/1.0.1/what-is-longhorn.md
content/docs/1.0.2/what-is-longhorn.md
content/docs/1.1.0/what-is-longhorn.md
content/docs/1.1.1/what-is-longhorn.md
content/docs/1.1.2/what-is-longhorn.md
content/docs/1.1.3/what-is-longhorn.md
content/docs/1.2.0/what-is-longhorn.md
content/docs/1.2.1/what-is-longhorn.md
content/docs/1.2.2/what-is-longhorn.md
content/docs/1.2.3/what-is-longhorn.md
content/docs/1.2.4/what-is-longhorn.md
content/docs/1.3.0/what-is-longhorn.md

Remove IOPS requirements of the volume configuration explanation 

---

content/docs/1.2.4/best-practices.md
content/docs/1.3.0/best-practices.md

https://github.com/longhorn/longhorn/issues/4182

Add spinning disk verification in best practice

---

content/docs/1.3.0/references/settings.md
content/docs/1.3.0/volumes-and-nodes/volume-size.md

https://github.com/longhorn/longhorn/issues/4183
https://github.com/longhorn/longhorn/issues/4251

Update the doc for feature purging-before-rebuilding

---

content/docs/1.2.5/references/settings.md
content/docs/1.2.5/volumes-and-nodes/volume-size.md

Longhorn/longhorn#4183
Longhorn/longhorn#4252

[Backport][v1.2.5] Update the doc for feature purging-before-rebuilding

---

content/docs/1.2.5/advanced-resources/deploy/rancher_windows_cluster.md

https://github.com/longhorn/longhorn/pull/4273
https://github.com/longhorn/longhorn/pull/4262
https://github.com/longhorn/website/pull/546

[v1.2.5] deploy: support Rancher deployed Windows Cluster

---

content/docs/1.3.1/advanced-resources/deploy/rancher_windows_cluster.md

https://github.com/longhorn/longhorn/issues/4274
https://github.com/longhorn/longhorn/issues/4246
https://github.com/longhorn/website/pull/546

[v1.3.1] deploy: support Rancher deployed Windows Cluster

---

content/docs/1.4.0/references/settings.md
content/docs/1.4.0/volumes-and-nodes/volume-size.md

https://github.com/longhorn/longhorn/issues/4183

Update the v1.4.0 doc for feature purging-before-rebuilding

---

content/docs/1.1.0/concepts.md
content/docs/1.1.1/concepts.md
content/docs/1.1.2/concepts.md
content/docs/1.1.3/concepts.md
content/docs/1.2.0/concepts.md
content/docs/1.2.1/concepts.md
content/docs/1.2.2/concepts.md
content/docs/1.2.3/concepts.md
content/docs/1.2.4/concepts.md
content/docs/1.2.5/concepts.md
content/docs/1.3.0/concepts.md
content/docs/1.3.1/concepts.md
content/docs/1.4.0/concepts.md
content/docs/archives/0.8.0/concepts.md
content/docs/archives/0.8.1/concepts.md
content/docs/archives/1.0.0/concepts.md
content/docs/archives/1.0.1/concepts.md
content/docs/archives/1.0.2/concepts.md

Signed-off-by: Tim Serong <tserong@suse.com>

Fix 'read the write' => 'read and write'

---

config.toml
content/docs/1.3.1/deploy/upgrade/_index.md
content/docs/1.3.1/deploy/upgrade/longhorn-manager.md
content/docs/1.3.1/deploy/upgrade/upgrade-engine.md

Release 1.3.1

---

content/docs/1.2.0/snapshots-and-backups/scheduling-backups-and-snapshots.md
content/docs/1.2.1/snapshots-and-backups/scheduling-backups-and-snapshots.md
content/docs/1.2.2/snapshots-and-backups/scheduling-backups-and-snapshots.md
content/docs/1.2.3/snapshots-and-backups/scheduling-backups-and-snapshots.md
content/docs/1.2.4/snapshots-and-backups/scheduling-backups-and-snapshots.md
content/docs/1.2.5/snapshots-and-backups/scheduling-backups-and-snapshots.md
content/docs/1.3.0/snapshots-and-backups/scheduling-backups-and-snapshots.md
content/docs/1.3.1/snapshots-and-backups/scheduling-backups-and-snapshots.md
content/docs/1.4.0/snapshots-and-backups/scheduling-backups-and-snapshots.md

delete unnecessary commas
Signed-off-by: hethehe <hethehe@outlook.com>

Fix wrong formatted json

---

content/docs/1.3.0/references/settings.md
content/docs/1.3.1/references/settings.md
content/docs/1.4.0/references/settings.md

[Longhorn 4432](https://github.com/longhorn/longhorn/issues/4432)

Add "Orphaned Data Automatic Deletion"

---

content/docs/1.1.0/deploy/install/_index.md
content/docs/1.1.1/deploy/install/_index.md
content/docs/1.1.2/deploy/install/_index.md
content/docs/1.1.3/deploy/install/_index.md
content/docs/1.2.0/deploy/install/_index.md
content/docs/1.2.1/deploy/install/_index.md
content/docs/1.2.2/deploy/install/_index.md
content/docs/1.2.3/deploy/install/_index.md
content/docs/1.2.4/deploy/install/_index.md
content/docs/1.2.5/deploy/install/_index.md
content/docs/1.3.0/deploy/install/_index.md
content/docs/1.3.1/deploy/install/_index.md
content/docs/1.4.0/deploy/install/_index.md

Modify the open-iscsi installing commands to synchronize with the `longhorn-iscsi-installation.yaml` file
https://github.com/longhorn/longhorn/issues/3630#issuecomment-1217522272
Signed-off-by: James Lu <jamesluhz@gmail.com>

Sync open-iscsi installation with the YAML file

---

content/kb/troubleshooting-volume-filesystem-corruption.md

[Longhorn 4440](https://github.com/longhorn/longhorn/issues/4440)

Update KB "Troubleshooting: Pod stuck in creating state when Longhorn volumes filesystem is corrupted"

---

config.toml

Release 1.2.5

---

content/kb/how-to-migrate-longhorn-chart-installed-in-old-rancher-ui-to-the-chart-in-new-rancher-ui.md

longhorn/longhorn#3714
There shouldn't have the = character for the flags

Fix the flag for chart migration script

---

layouts/partials/css.html
layouts/partials/javascript.html
layouts/partials/search-bar.html

Change css url and appId, apiKey.
Re-indexing the website at Algolia/Crawler website.
longhorn/longhorn#4457
Signed-off-by: James Lu <james.lu@suse.com>

Migrate docsearch from v2 to v3.

---

content/docs/1.1.1/deploy/install/_index.md
content/docs/1.1.2/deploy/install/_index.md
content/docs/1.1.3/deploy/install/_index.md
content/docs/1.2.0/deploy/install/_index.md
content/docs/1.2.1/deploy/install/_index.md
content/docs/1.2.2/deploy/install/_index.md
content/docs/1.2.3/deploy/install/_index.md
content/docs/1.2.4/deploy/install/_index.md
content/docs/1.2.5/deploy/install/_index.md
content/docs/1.3.0/deploy/install/_index.md
content/docs/1.3.1/deploy/install/_index.md
content/docs/1.4.0/deploy/install/_index.md

A single little spelling error I found while reading the docs.

Fix small spelling error

---

content/docs/1.4.0/best-practices.md

docs: update recommended os version info
For https://github.com/longhorn/longhorn/issues/4620, https://github.com/longhorn/longhorn/issues/4618

docs: update recommended os version info

---

content/docs/1.3.0/references/networking.md
content/docs/1.3.1/references/networking.md
content/docs/1.4.0/references/networking.md

[Longhorn 4478
](https://github.com/longhorn/longhorn/issues/4478)

Longhorn Networking: add webhook and recovery backend

---

content/docs/1.2.5/deploy/install/_index.md
content/docs/1.3.0/deploy/install/_index.md
content/docs/1.3.1/deploy/install/_index.md
content/docs/1.4.0/deploy/install/_index.md

[Longhorn 4450](https://github.com/longhorn/longhorn/issues/4450)

docs(deploy): Update the Environment Check Script output result

---

content/docs/1.4.0/deploy/important-notes/index.md
content/docs/1.4.0/deploy/uninstall/_index.md
content/docs/1.4.0/references/settings.md

Add deleting-confirmation-flag document

---

config.toml

Release 1.2.6

---

content/docs/1.4.0/deploy/uninstall/_index.md

issue https://github.com/longhorn/longhorn/issues/4841
Signed-off-by: Roger Yao <roger.yao@suse.com>

Update Longhorn doc in uninstalling longhorn using kubectl

---

content/docs/1.4.0/volumes-and-nodes/storage-tags.md

[Longhorn 4574](https://github.com/longhorn/longhorn/issues/4574)

docs(volume): description for storageclass node selector setting

---

content/docs/1.4.0/references/settings.md

[Longhorn 4491](https://github.com/longhorn/longhorn/issues/4491)

Add setting engine-replica-timeout

---

content/docs/1.4.0/references/settings.md
content/docs/1.4.0/volumes-and-nodes/trim-filesystem.md
content/docs/1.4.0/volumes-and-nodes/volume-size.md

Update docs for the filesystem trim feature

---

content/docs/1.4.0/advanced-resources/support-bundle.md
content/docs/1.4.0/advanced-resources/troubleshooting.md
content/docs/1.4.0/references/settings.md

https://github.com/longhorn/longhorn/issues/2759

doc(support-bundle): add feature doc

---

content/docs/1.4.0/deploy/important-notes/index.md
content/docs/1.4.0/deploy/install/install-with-helm.md
content/docs/1.4.0/deploy/install/install-with-kubectl.md
content/docs/1.4.0/deploy/install/install-with-rancher.md

Add PSP document

---

content/docs/1.4.0/advanced-resources/fast-replica-rebuild.md
content/docs/1.4.0/references/settings.md

doc: add "Fast Rebuild Rebuild" doc and settings

---

content/docs/1.4.0/deploy/important-notes/index.md
content/docs/1.4.0/references/examples.md
content/docs/1.4.0/references/settings.md
content/docs/1.4.0/volumes-and-nodes/create-volumes.md

[Longhorn 4642](https://github.com/longhorn/longhorn/issues/4642)

docs: add description for parameter `mkfsParams` of storage class

---

content/docs/1.4.0/references/settings.md
content/docs/1.4.0/snapshots-and-backups/backup-and-restore/restore-recurring-jobs-from-a-backup.md

Add a feature page to `Backup and Restore` Section.
Add the setting `Restore Volume Recurring Jobs` to `Settings Reference` Section
longhorn/longhorn#2227

doc(recurringjob): backup and restore

---

content/docs/1.4.0/high-availability/data-locality.md
content/docs/1.4.0/references/settings.md

Update data-locality doc

---

content/docs/1.4.0/deploy/important-notes/index.md

https://github.com/longhorn/longhorn/issues/5023

important nodes: add fast replica rebuilding

---

content/docs/1.4.0/advanced-resources/deploy/customizing-default-settings.md
content/docs/1.4.0/references/settings.md

[Longhorn 1711](https://github.com/longhorn/longhorn/issues/1711)
[Longhorn 4912](https://github.com/longhorn/longhorn/issues/4912)

docs(recurringjob): description about recurring job history limit count

---

content/kb/troubleshooting-volume-filesystem-corruption.md

Update troubleshooting-volume-filesystem-corruption doc

---

.github/workflows/codespell.yml

chore: use code spell v1

---

content/docs/1.4.0/advanced-resources/rwx-workloads.md

chore: Correct grammar and typos in the RWX volume documentation

---

content/docs/1.4.0/advanced-resources/deploy/node-selector.md
content/docs/1.4.0/advanced-resources/deploy/taint-toleration.md

Update node-selector and taint-toleration docs

---

content/docs/1.2.3/advanced-resources/cluster-restore/restore-to-a-new-cluster-using-velero.md
content/docs/1.2.4/advanced-resources/cluster-restore/restore-to-a-new-cluster-using-velero.md
content/docs/1.2.5/advanced-resources/cluster-restore/restore-to-a-new-cluster-using-velero.md
content/docs/1.2.6/advanced-resources/cluster-restore/restore-to-a-new-cluster-using-velero.md
content/docs/1.2.7/advanced-resources/cluster-restore/restore-to-a-new-cluster-using-velero.md
content/docs/1.3.0/advanced-resources/cluster-restore/restore-to-a-new-cluster-using-velero.md
content/docs/1.3.1/advanced-resources/cluster-restore/restore-to-a-new-cluster-using-velero.md
content/docs/1.3.2/advanced-resources/cluster-restore/restore-to-a-new-cluster-using-velero.md
content/docs/1.3.3/advanced-resources/cluster-restore/restore-to-a-new-cluster-using-velero.md
content/docs/1.4.0/advanced-resources/cluster-restore/restore-to-a-new-cluster-using-velero.md
content/kb/troubleshooting-restore-pvc-stuck-using-velero-csi-plugin-version-lower-than-0.4.md

[Longhorn 4951](https://github.com/longhorn/longhorn/issues/4951)

docs: add KB for Restore PVC stuck using Velero CSI plugin version < 0.4

---

content/docs/1.4.0/monitoring/metrics.md

Add volume io metrics

---

content/docs/1.4.0/references/settings.md

https://github.com/longhorn/longhorn/issues/4558

doc(concurrent-backup-restore): add setting

---

content/docs/1.4.0/references/settings.md

Update "Snapshot Data Integrity" default value to "fast-check"

---

content/docs/1.4.0/volumes-and-nodes/trim-filesystem.md

docs: rwo volume does not support trim

---

content/docs/1.4.0/volumes-and-nodes/trim-filesystem.md

Update the limitations for the trim feature

---

content/docs/1.4.0/volumes-and-nodes/expansion.md

docs: Update the doc after implementing online expansion

---

content/docs/1.4.0/advanced-resources/_index.md
content/docs/1.4.0/advanced-resources/data-recovery/_index.md
content/docs/1.4.0/advanced-resources/deploy/_index.md
content/docs/1.4.0/advanced-resources/os-distro-specific/_index.md
content/docs/1.4.0/advanced-resources/security/_index.md
content/docs/1.4.0/advanced-resources/support-managed-k8s-service/_index.md
content/docs/1.4.0/deploy/_index.md
content/docs/1.4.0/high-availability/_index.md
content/docs/1.4.0/monitoring/_index.md
content/docs/1.4.0/references/_index.md
content/docs/1.4.0/snapshots-and-backups/_index.md
content/docs/1.4.0/snapshots-and-backups/csi-snapshot-support/_index.md
content/docs/1.4.0/volumes-and-nodes/_index.md

doc: Add TOC for each doc parent page

---

content/blog/longhorn-v1.4.md

docs: add 1.4.0 blog post

---

content/docs/1.4.0/volumes-and-nodes/trim-filesystem.md

Longhorn/longhorn#5203
Longhorn/longhorn#5218

docs: Add one more requirement for the trim doc to avoid compatibility issues

---

content/docs/1.1.3/volumes-and-nodes/multidisk.md
content/docs/1.3.2/volumes-and-nodes/multidisk.md
content/docs/1.3.3/volumes-and-nodes/multidisk.md
content/docs/1.4.0/volumes-and-nodes/multidisk.md
content/docs/1.4.1/volumes-and-nodes/multidisk.md
content/docs/1.5.0/volumes-and-nodes/multidisk.md
content/docs/archives/1.2.5/volumes-and-nodes/multidisk.md

docs: add replica eviction ref to removing disks

---

content/docs/1.4.0/deploy/upgrade/_index.md
content/docs/1.4.0/deploy/upgrade/longhorn-manager.md
content/docs/1.4.0/deploy/upgrade/upgrade-engine.md
content/docs/1.4.1/deploy/upgrade/_index.md
content/docs/1.4.1/deploy/upgrade/longhorn-manager.md
content/docs/1.4.1/deploy/upgrade/upgrade-engine.md
content/docs/1.5.0/deploy/upgrade/_index.md
content/docs/1.5.0/deploy/upgrade/longhorn-manager.md
content/docs/1.5.0/deploy/upgrade/upgrade-engine.md

docs: fix the wrong version in upgrade doc

---

content/docs/1.5.0/snapshots-and-backups/scheduling-backups-and-snapshots.md

https://github.com/longhorn/longhorn/issues/3836

doc(recurring-job): new task types

---

content/docs/1.3.3/snapshots-and-backups/scheduling-backups-and-snapshots.md
content/docs/1.4.1/snapshots-and-backups/scheduling-backups-and-snapshots.md
content/docs/1.5.0/snapshots-and-backups/scheduling-backups-and-snapshots.md

https://github.com/longhorn/longhorn/issues/4893
https://github.com/longhorn/longhorn/issues/5109
https://github.com/longhorn/longhorn/issues/3836

doc(recurring-job/v1.3.3, v1.4.1): new task types

---

content/docs/1.3.0/volumes-and-nodes/maintenance.md
content/docs/1.3.1/volumes-and-nodes/maintenance.md
content/docs/1.3.2/volumes-and-nodes/maintenance.md
content/docs/1.3.3/volumes-and-nodes/maintenance.md
content/docs/1.4.0/volumes-and-nodes/maintenance.md
content/docs/1.4.1/volumes-and-nodes/maintenance.md
content/docs/1.5.0/volumes-and-nodes/maintenance.md

Add pod-selector to avoid draining Longhorn webhook

---

content/docs/1.4.1/advanced-resources/system-backup-restore/restore-longhorn-system.md
content/docs/1.5.0/advanced-resources/system-backup-restore/restore-longhorn-system.md

- https://github.com/longhorn/longhorn/issues/5442
- https://github.com/longhorn/longhorn/issues/5473

docs(system-restore): ignore backup target settings

---

content/docs/1.4.0/deploy/important-notes/index.md
content/docs/1.4.1/deploy/important-notes/index.md
content/docs/1.4.2/deploy/important-notes/index.md
content/docs/1.5.0/deploy/important-notes/index.md

fix: wrong supported kubernetes version in 1.4

---

content/docs/1.4.0/deploy/uninstall/_index.md
content/docs/1.4.1/deploy/uninstall/_index.md
content/docs/1.5.0/deploy/uninstall/_index.md

issue https://github.com/longhorn/longhorn/issues/5540
Signed-off-by: Roger Yao <roger.yao@suse.com>

Update LH Doc to correct kubectl command in uninstallation job example

---

content/docs/1.5.0/snapshots-and-backups/backup-and-restore/set-backup-target.md
content/docs/1.5.0/terminology.md

Add CIFS backupstore

---

content/docs/1.5.0/snapshots-and-backups/scheduling-backups-and-snapshots.md

https://github.com/longhorn/longhorn/issues/5186

doc(recurring-job): filesystem-trim

---

content/docs/1.5.0/references/settings.md

https://github.com/longhorn/longhorn/issues/2694

doc(setting): decrease Storage Over Provisioning Percentage

---

content/docs/1.5.0/advanced-resources/deploy/customizing-default-settings.md
content/docs/1.5.0/deploy/important-notes/index.md
content/docs/1.5.0/references/settings.md

Remove disable-replica-rebuild setting

---

content/docs/1.5.0/snapshots-and-backups/backup-and-restore/set-backup-target.md

This is tied to https://github.com/longhorn/longhorn/issues/5774

docs: added documentation on configuring google cloud storage bucket as a backup source

---

content/docs/1.5.0/advanced-resources/deploy/customizing-default-settings.md
content/docs/1.5.0/advanced-resources/troubleshooting.md
content/docs/1.5.0/best-practices.md
content/docs/1.5.0/deploy/important-notes/index.md
content/docs/1.5.0/deploy/install/_index.md
content/docs/1.5.0/deploy/install/install-with-helm.md
content/docs/1.5.0/deploy/install/install-with-kubectl.md
content/docs/1.5.0/deploy/upgrade/longhorn-manager.md
content/docs/1.5.0/references/settings.md

https://github.com/longhorn/longhorn/issues/5208
https://github.com/longhorn/longhorn/issues/5917

doc: consolidate instance managers

---

content/docs/1.1.3/volumes-and-nodes/multidisk.md
content/docs/1.2.6/volumes-and-nodes/multidisk.md
content/docs/1.3.0/volumes-and-nodes/multidisk.md
content/docs/1.3.1/volumes-and-nodes/multidisk.md
content/docs/1.3.2/volumes-and-nodes/multidisk.md
content/docs/1.3.3/volumes-and-nodes/multidisk.md
content/docs/1.3.4/volumes-and-nodes/multidisk.md
content/docs/1.4.0/volumes-and-nodes/multidisk.md
content/docs/1.4.1/volumes-and-nodes/multidisk.md
content/docs/1.4.2/volumes-and-nodes/multidisk.md
content/docs/1.4.3/volumes-and-nodes/multidisk.md
content/docs/1.5.0/volumes-and-nodes/multidisk.md
content/docs/archives/1.0.0/volumes-and-nodes/multidisk.md
content/docs/archives/1.0.1/volumes-and-nodes/multidisk.md
content/docs/archives/1.0.2/volumes-and-nodes/multidisk.md
content/docs/archives/1.1.0/volumes-and-nodes/multidisk.md
content/docs/archives/1.1.1/volumes-and-nodes/multidisk.md
content/docs/archives/1.1.2/volumes-and-nodes/multidisk.md
content/docs/archives/1.2.0/volumes-and-nodes/multidisk.md
content/docs/archives/1.2.1/volumes-and-nodes/multidisk.md
content/docs/archives/1.2.2/volumes-and-nodes/multidisk.md
content/docs/archives/1.2.3/volumes-and-nodes/multidisk.md
content/docs/archives/1.2.4/volumes-and-nodes/multidisk.md
content/docs/archives/1.2.5/volumes-and-nodes/multidisk.md

related to https://github.com/longhorn/website/issues/701

doc: fix typo in multidisk document

---

content/docs/1.5.0/advanced-resources/backing-image.md
content/docs/1.5.0/snapshots-and-backups/csi-snapshot-support/csi-volume-snapshot-associated-with-longhorn-backing-image.md

ref: [longhorn/longhorn#5005](https://github.com/longhorn/longhorn/issues/5005)

doc: add doc for csi volumesnapshot associated with longhorn backing image

---

content/docs/1.5.0/snapshots-and-backups/scheduling-backups-and-snapshots.md

https://github.com/longhorn/longhorn/issues/5791

doc(recurring-job): set to PVC

---

content/docs/1.5.0/deploy/important-notes/index.md

https://github.com/longhorn/longhorn/issues/2865

doc: remove Volume recurringJob field

---

content/docs/1.5.0/snapshots-and-backups/scheduling-backups-and-snapshots.md

https://github.com/longhorn/longhorn/issues/5791

doc(recurring-job): PVC source label

---

content/docs/1.5.0/deploy/important-notes/index.md

https://github.com/longhorn/website/pull/671#discussion_r1209705291

doc: fix typo

---

content/docs/1.5.0/deploy/important-notes/index.md

https://github.com/longhorn/longhorn/issues/3289

doc(important-note): remove CRD fields

---

content/docs/1.4.3/advanced-resources/support-bundle.md
content/docs/1.5.0/advanced-resources/support-bundle.md

https://github.com/longhorn/longhorn/issues/5882

doc(support-bundle): concurrent generation

---

content/docs/1.5.0/snapshots-and-backups/csi-snapshot-support/csi-volume-snapshot-associated-with-longhorn-backup.md
content/docs/1.5.0/snapshots-and-backups/csi-snapshot-support/csi-volume-snapshot-associated-with-longhorn-snapshot.md

Auto-attach volume for K8s CSI snapshot

---

content/docs/1.5.0/references/networking.md

ref: [longhorn/longhorn 5403](https://github.com/longhorn/longhorn/issues/5403)

feat(network): add network policy to the chart

---

content/docs/1.5.0/deploy/important-notes/index.md

Add important note about: attachment/detachment refactoring side effect on the upgrade process

---

content/docs/1.5.0/advanced-resources/deploy/customizing-default-settings.md
content/docs/1.5.0/deploy/important-notes/index.md
content/docs/1.5.0/references/settings.md
content/docs/1.5.0/volumes-and-nodes/maintenance.md

Remove deprecated allow-node-drain-with-last-healthy-replica setting

---

content/docs/1.5.0/references/settings.md

https://github.com/longhorn/longhorn/issues/5235

doc(settings): longhorn resource usage metrics in ranges

---

content/docs/1.5.0/spdk/quick-start.md

Update minor content of SPDK quick-start.md
ref: [5744](https://github.com/longhorn/longhorn/issues/5744)

Update SPDK quick-start.md

---

content/docs/1.5.0/spdk/quick-start.md

spdk: update quick-start doc

---

content/docs/1.3.0/deploy/install/_index.md
content/docs/1.3.1/deploy/install/_index.md
content/docs/1.3.2/deploy/install/_index.md
content/docs/1.3.3/deploy/install/_index.md
content/docs/1.3.4/deploy/install/_index.md
content/docs/1.4.0/deploy/install/_index.md
content/docs/1.4.1/deploy/install/_index.md
content/docs/1.4.2/deploy/install/_index.md
content/docs/1.4.3/deploy/install/_index.md
content/docs/1.5.0/deploy/install/_index.md
content/kb/troubleshooting-volume-attachment-fails-due-to-selinux-denials.md

Add KB article outlining recent SELinux issues

---

content/docs/1.5.0/snapshots-and-backups/backup-and-restore/restore-from-a-backup.md

ref: [longhorn/longhorn#3506](https://github.com/longhorn/longhorn/issues/3506)

doc(backup): store storageclass in backup meta

---

content/docs/1.5.0/references/settings.md

https://github.com/longhorn/longhorn/issues/5235

doc(setting): out-of-format

---

content/docs/1.5.0/references/settings.md
content/docs/1.5.0/spdk/_index.md
content/docs/1.5.0/spdk/automatic-offline-replica-rebuilding.md
content/docs/1.5.0/spdk/quick-start.md

spdk: update documents

---

content/docs/1.5.0/references/settings.md

https://github.com/longhorn/longhorn/issues/5235

doc(settings): remove longhorn resource usage metrics ranges

---

content/docs/1.5.0/references/settings.md

Reduce BackupConcurrentLimit and RestoreConcurrentLimit to 2

---

content/docs/1.5.0/best-practices.md

doc: update os info
For https://github.com/longhorn/longhorn/issues/5177

doc: update os info

---

content/docs/1.5.0/references/settings.md
content/docs/1.5.1/references/settings.md
content/docs/1.6.0/references/settings.md

doc: add default disk reserved percentage setting

---

content/kb/troubleshooting-failure-to-delete-orphaned-pod-volume-directory.md

[Longhorn 3207](https://github.com/longhorn/longhorn/issues/3207)

docs: Add KB about failure to delete orphaned pod volume directory

---

content/kb/troubleshooting-unexpected-expansion-leads-to-degredation-or-attach-failure.md
content/kb/troubleshooting-volume-attachment-fails-due-to-selinux-denials.md

Create a KB for incorrect replica expansion

---

content/docs/1.6.0/references/settings.md

https://github.com/longhorn/longhorn/issues/6410

doc(telemetric): collect Snapshot Data Integrity CronJob setting as boolean

---

content/docs/1.4.4/monitoring/metrics.md
content/docs/1.5.2/monitoring/metrics.md
content/docs/1.6.0/monitoring/metrics.md

https://github.com/longhorn/longhorn/issues/5297

doc(metrics): add pvc name to volume metrics

---

content/kb/space-consumption-guideline.md

https://github.com/longhorn/longhorn/issues/6592

docs: Add space-consumption-guideline

---

content/docs/1.6.0/references/settings.md
content/docs/1.6.0/volumes-and-nodes/scheduling.md

ref: [longhorn/longhorn#4826](https://github.com/longhorn/longhorn/issues/4826)

doc(scheduling): add allow empty selector settings

---

content/kb/troubleshooting-failed-rwx-mount-due-to-connection-timeout.md

Add KB for TX checksum offloading bug

---

content/docs/1.4.0/advanced-resources/rwx-workloads.md
content/docs/1.4.1/advanced-resources/rwx-workloads.md
content/docs/1.4.2/advanced-resources/rwx-workloads.md
content/docs/1.4.3/advanced-resources/rwx-workloads.md
content/docs/1.4.4/advanced-resources/rwx-workloads.md
content/docs/1.5.0/advanced-resources/rwx-workloads.md
content/docs/1.5.1/advanced-resources/rwx-workloads.md
content/docs/1.5.2/advanced-resources/rwx-workloads.md
content/docs/1.6.0/advanced-resources/rwx-workloads.md

Update rwx volume doc

---

content/docs/1.4.0/references/storage-class-parameters.md
content/docs/1.4.1/references/storage-class-parameters.md
content/docs/1.4.2/references/storage-class-parameters.md
content/docs/1.4.3/references/storage-class-parameters.md
content/docs/1.4.4/references/storage-class-parameters.md
content/docs/1.5.0/references/storage-class-parameters.md
content/docs/1.5.1/references/storage-class-parameters.md
content/docs/1.5.2/references/storage-class-parameters.md
content/docs/1.6.0/references/storage-class-parameters.md

Part of https://github.com/longhorn/longhorn/issues/6655.

Add mount options to storage class reference.

---

content/docs/1.4.0/references/storage-class-parameters.md
content/docs/1.4.1/references/storage-class-parameters.md
content/docs/1.4.2/references/storage-class-parameters.md
content/docs/1.4.3/references/storage-class-parameters.md
content/docs/1.4.4/references/storage-class-parameters.md
content/docs/1.5.0/deploy/important-notes/index.md
content/docs/1.5.0/references/storage-class-parameters.md
content/docs/1.5.1/deploy/important-notes/index.md
content/docs/1.5.1/references/storage-class-parameters.md
content/docs/1.5.2/deploy/important-notes/index.md
content/docs/1.5.2/references/storage-class-parameters.md
content/docs/1.5.2/spdk/quick-start.md
content/docs/1.6.0/deploy/important-notes/index.md
content/docs/1.6.0/references/storage-class-parameters.md
content/docs/1.6.0/spdk/quick-start.md
content/docs/archives/0.8.0/users-guide/backup-and-restore/backupstores-and-backuptargets.md
content/kb/space-consumption-guideline.md

Remove nvme-cli installation from v1.5.2+

---

content/kb/troubleshooting-fstrim-error.md

Add KB troubleshooting filesystem trim error 

---

content/kb/troubleshooting-volume-filesystem-corruption.md

Describe how to fsck.ext4 when using an old distro

---

content/docs/1.4.4/monitoring/metrics.md
content/docs/1.5.2/monitoring/metrics.md
content/docs/1.6.0/monitoring/metrics.md

https://github.com/longhorn/longhorn/issues/6858
https://github.com/longhorn/longhorn/issues/6873
https://github.com/longhorn/longhorn/issues/6872

feat(metrics): longhorn_disk_status

---

content/kb/troubleshooting-volume-filesystem-corruption.md

longhorn/longhorn#6859
Updated formatting based on @jillian-maroket's feedback from https://github.com/longhorn/website/pull/783#pullrequestreview-1686603558.

Format previously added fsct.ext4 old distro instructions

---

content/docs/1.5.0/deploy/important-notes/index.md
content/docs/1.5.0/deploy/upgrade/_index.md
content/docs/1.5.1/deploy/important-notes/index.md
content/docs/1.5.1/deploy/upgrade/_index.md
content/docs/1.5.2/deploy/important-notes/index.md
content/docs/1.5.2/deploy/upgrade/_index.md

Add note for longhorn-system upgrade for v2 volumes

---

content/docs/1.4.5/monitoring/metrics.md
content/docs/1.5.3/monitoring/metrics.md
content/docs/1.6.0/monitoring/metrics.md

https://github.com/longhorn/longhorn/issues/7077

doc(metrics): add pvc namespace to volume metrics

---

content/docs/1.5.0/deploy/important-notes/index.md
content/docs/1.5.0/deploy/upgrade/_index.md
content/docs/1.5.1/deploy/important-notes/index.md
content/docs/1.5.1/deploy/upgrade/_index.md
content/docs/1.5.2/deploy/important-notes/index.md
content/docs/1.5.2/deploy/upgrade/_index.md
content/docs/1.5.3/deploy/important-notes/index.md
content/docs/1.5.3/deploy/upgrade/_index.md

doc: update upgrade for v2 volumes

---

content/docs/archives/_index.md
layouts/partials/docs/dashboard.html
layouts/partials/docs/nav.html
layouts/shortcodes/current-version.html

doc: fix broken archived version page

---

content/docs/1.6.0/references/helm-values.md

From https://github.com/longhorn/longhorn/issues/7050#issuecomment-1840244962

Update helm-chart values

---

content/docs/1.6.0/references/helm-values.md
content/docs/1.6.0/references/settings.md

ref: https://github.com/longhorn/longhorn/issues/6978
Add setting `DetachManuallyAttachedVolumesDuringDrain` default to `true`

feat(node drain): add DetachManuallyAttachedVolumesDuringDrain setting

---

content/docs/1.5.0/snapshots-and-backups/scheduling-backups-and-snapshots.md
content/docs/1.5.1/snapshots-and-backups/scheduling-backups-and-snapshots.md
content/docs/1.5.2/snapshots-and-backups/scheduling-backups-and-snapshots.md
content/docs/1.5.3/snapshots-and-backups/scheduling-backups-and-snapshots.md
content/docs/1.5.4/snapshots-and-backups/scheduling-backups-and-snapshots.md
content/docs/1.6.0/snapshots-and-backups/scheduling-backups-and-snapshots.md

Fix typo in PVC recurring job label example

---

content/docs/1.6.0/references/settings.md

https://github.com/longhorn/longhorn/issues/6033

doc(telemetry): collect SPDK node disk type

---

content/docs/1.6.0/best-practices.md
content/docs/1.6.0/deploy/install/_index.md

https://github.com/longhorn/longhorn/issues/7224

doc: suggest supported Kubernetes version

---

content/docs/1.6.0/deploy/install/_index.md
content/docs/1.6.0/deploy/install/install-with-fleet.md

doc: add document for fleet
For https://github.com/longhorn/longhorn/issues/7331

doc: add document for fleet

---

content/docs/1.5.1/volumes-and-nodes/trim-filesystem.md
content/docs/1.5.2/volumes-and-nodes/trim-filesystem.md
content/docs/1.5.3/volumes-and-nodes/trim-filesystem.md
content/docs/1.5.4/volumes-and-nodes/trim-filesystem.md
content/docs/1.6.0/volumes-and-nodes/trim-filesystem.md

https://github.com/longhorn/longhorn/issues/6733
Revise note that UI does not support trim on RWX volumes.  Duplicate the change to releases 1.5.1-1.5.4

Remove outdated note that UI trim does not support RWX.

---

content/docs/1.6.0/deploy/install/_index.md
content/docs/1.6.0/deploy/install/install-with-argocd.md

doc: add document for argocd
For https://github.com/longhorn/longhorn/issues/7360

doc: add document for argocd

---

content/docs/1.6.0/deploy/install/_index.md
content/docs/1.6.0/deploy/install/install-with-flux.md

doc: add document for flux
For https://github.com/longhorn/longhorn/issues/7335

doc: add document for flux

---

content/docs/1.5.4/snapshots-and-backups/csi-snapshot-support/enable-csi-snapshot-support.md
content/docs/1.6.0/snapshots-and-backups/csi-snapshot-support/enable-csi-snapshot-support.md

https://github.com/longhorn/longhorn/issues/6916
https://github.com/longhorn/longhorn/issues/7150

doc(1.6.0, 1.5.4): update CSI snapshotter version to v6.3.0

---

content/docs/1.4.0/best-practices.md
content/docs/1.4.0/volumes-and-nodes/multidisk.md
content/docs/1.4.1/best-practices.md
content/docs/1.4.1/volumes-and-nodes/multidisk.md
content/docs/1.4.2/best-practices.md
content/docs/1.4.2/volumes-and-nodes/multidisk.md
content/docs/1.4.3/best-practices.md
content/docs/1.4.3/volumes-and-nodes/multidisk.md
content/docs/1.4.4/best-practices.md
content/docs/1.4.4/volumes-and-nodes/multidisk.md
content/docs/1.4.5/best-practices.md
content/docs/1.4.5/volumes-and-nodes/multidisk.md
content/docs/1.5.0/best-practices.md
content/docs/1.5.0/volumes-and-nodes/multidisk.md
content/docs/1.5.1/best-practices.md
content/docs/1.5.1/volumes-and-nodes/multidisk.md
content/docs/1.5.2/best-practices.md
content/docs/1.5.2/volumes-and-nodes/multidisk.md
content/docs/1.5.3/best-practices.md
content/docs/1.5.3/volumes-and-nodes/multidisk.md
content/docs/1.5.4/best-practices.md
content/docs/1.5.4/volumes-and-nodes/multidisk.md
content/docs/1.6.0/best-practices.md
content/docs/1.6.0/references/helm-values.md
content/docs/1.6.0/volumes-and-nodes/multidisk.md

https://github.com/longhorn/longhorn/issues/7342
Simple correction to match the code and Settings documentation in all non-archived releases.

Fix value of default setting StorageMinimalAvailablePercentage

---

content/docs/1.6.0/monitoring/metrics.md

https://github.com/longhorn/longhorn/issues/5869#issuecomment-1865823767

doc(metrics): update longhorn_snapshot_actual_size_bytes example

---

content/docs/1.6.0/references/helm-values.md
content/docs/1.6.0/snapshots-and-backups/csi-snapshot-support/enable-csi-snapshot-support.md

https://github.com/longhorn/longhorn/issues/7384

doc(1.6.0): update CSI components version

---

content/docs/1.6.0/advanced-resources/deploy/customizing-default-settings.md
content/docs/1.6.0/deploy/install/install-with-helm.md

fix: remove helm 2 support

---

content/docs/1.6.0/advanced-resources/deploy/priority-class.md
content/docs/1.6.0/deploy/important-notes/index.md
content/docs/1.6.0/references/settings.md

Add import notes for the default priority class at v1.6.0.
Ref: longhorn/longhorn#6528

doc: default priority class

---

content/docs/1.6.0/best-practices.md
content/docs/1.6.0/references/helm-values.md
content/docs/1.6.0/references/settings.md

Add docs for `V1 Data Engine` and `Guaranteed Instance Manager CPU for V2 Data Engine`

---

content/docs/1.6.0/deploy/important-notes/index.md

https://github.com/longhorn/longhorn/issues/5842#issuecomment-1870748181

doc(1.6.0): update engine upgrade enforcement

---

content/docs/1.5.4/snapshots-and-backups/csi-snapshot-support/enable-csi-snapshot-support.md

https://github.com/longhorn/longhorn/issues/7492

doc(v1.5.4): update csi-snapshotter version to v6.3.2

---

content/docs/1.4.5/volumes-and-nodes/expansion.md
content/docs/1.4.5/volumes-and-nodes/volume-size.md
content/docs/1.5.4/volumes-and-nodes/expansion.md
content/docs/1.5.4/volumes-and-nodes/volume-size.md
content/docs/1.6.0/volumes-and-nodes/expansion.md
content/docs/1.6.0/volumes-and-nodes/volume-size.md

Descriptions of the maximum volume size for file systems.
Ref: longhorn/longhorn#7423

doc(volume): max volume size for the file system

---

content/docs/1.6.0/advanced-resources/snapshot-space-management.md

https://github.com/longhorn/longhorn/issues/6563

doc(1.6.0): add snapshot space management

---

content/docs/1.6.0/advanced-resources/backing-image-backup.md
content/docs/1.6.0/advanced-resources/backing-image.md

ref: https://github.com/longhorn/longhorn/issues/4165

doc(backup backing image): add backup and restore backing image doc

---

content/docs/1.6.0/spdk/features.md

v2 volume: update features

---

content/docs/1.6.0/deploy/important-notes/index.md
content/docs/1.6.0/references/settings.md
content/docs/1.6.0/spdk/prerequisites.md
content/docs/1.6.0/spdk/quick-start.md

https://github.com/longhorn/longhorn/issues/7606

v2 volume: change default hugepage to 2048 MiB

---

content/docs/1.6.0/best-practices.md

Updated distro version:
- Ubuntu 22.04
- SLES 15 SP5
- SLE Micro 5.5
- RHEL 9.3
- Oracle Linux 9.3
- Rocky Linux 9.3
- Talos Linux 1.6.1
Signed-off-by: Khushboo <fnu.khushboo@suse.com>

Update distro versions

---

content/docs/1.6.0/references/helm-values.md

ref: longhorn/longhorn 7667
There are some descriptions update not synced to website before
So need to update it back here.
Now two content should be consisten

fix(doc): update the description in helm values

---

content/docs/1.4.5/best-practices.md
content/docs/1.5.4/best-practices.md

Issue - https://github.com/longhorn/website/pull/842/files#r1451283819

Update Sles version

---

content/docs/1.5.0/v2-data-engine/automatic-offline-replica-rebuilding.md
content/docs/1.5.0/v2-data-engine/performance-benchmark.md
content/docs/1.5.0/v2-data-engine/quick-start.md
content/docs/1.5.1/v2-data-engine/automatic-offline-replica-rebuilding.md
content/docs/1.5.1/v2-data-engine/performance-benchmark.md
content/docs/1.5.1/v2-data-engine/quick-start.md
content/docs/1.5.2/v2-data-engine/automatic-offline-replica-rebuilding.md
content/docs/1.5.2/v2-data-engine/performance-benchmark.md
content/docs/1.5.2/v2-data-engine/quick-start.md
content/docs/1.5.3/v2-data-engine/automatic-offline-replica-rebuilding.md
content/docs/1.5.3/v2-data-engine/performance-benchmark.md
content/docs/1.5.3/v2-data-engine/quick-start.md
content/docs/1.5.4/v2-data-engine/automatic-offline-replica-rebuilding.md
content/docs/1.5.4/v2-data-engine/performance-benchmark.md
content/docs/1.5.4/v2-data-engine/quick-start.md

v2 volume: update v1.5.x doc based on the changes in v1.6.0 doc

---

content/docs/1.6.0/v2-data-engine/prerequisites.md

v2 volume: fix wrong indent

---

content/docs/1.5.4/deploy/important-notes/index.md
content/docs/1.5.4/references/settings.md
content/docs/1.5.4/volumes-and-nodes/maintenance.md

longhorn/longhorn#7421 (backport of https://github.com/longhorn/longhorn/issues/2238)

Document new node drain policies and clarify drain behavior (backport #794)

---

content/docs/1.4.5/monitoring/metrics.md
content/docs/1.5.4/monitoring/metrics.md

Issues:
- longhorn/longhorn#7725
- longhorn/longhorn#7726
`N/A`
`None`
longhorn/longhorn#5869

doc(v1.5.4, v1.4.5): feat metrics collect backups and snapshots

---

content/docs/1.6.0/references/settings.md
content/docs/1.6.0/references/storage-class-parameters.md
content/docs/1.6.0/v2-data-engine/quick-start.md

v2 volume: replace backendStoreDriver with dataEngine in v1.6.0

---

content/docs/1.4.5/high-availability/recover-volume-when-read-only.md
content/docs/1.5.4/high-availability/recover-volume-when-read-only.md
content/docs/1.6.0/high-availability/recover-volume-when-read-only.md

ref: https://github.com/longhorn/longhorn/issues/6386
Add doc for remount when volume becomes read only

doc(ha): add doc for remount when volume read only

---

content/docs/1.6.0/advanced-resources/deploy/node-selector.md
content/docs/1.6.0/advanced-resources/deploy/priority-class.md
content/docs/1.6.0/advanced-resources/deploy/storage-network.md
content/docs/1.6.0/advanced-resources/deploy/taint-toleration.md
content/docs/1.6.0/deploy/important-notes/index.md
content/docs/1.6.0/references/settings.md

Issue longhorn/longhorn#7173, longhorn/longhorn#7675
Users can customize the danger zone settings but the settings will only take effect when all volumes are detached.

doc(setting): eventual danger zone setting update

---

content/docs/1.5.4/monitoring/prometheus-and-grafana-setup.md
content/docs/1.6.0/monitoring/prometheus-and-grafana-setup.md
content/docs/1.6.1/monitoring/prometheus-and-grafana-setup.md
content/docs/1.7.0/monitoring/prometheus-and-grafana-setup.md

Issue # longhorn/longhorn#7864
Add the description to create `serviceMonitor` with Helm.

doc: add `serviceMonitor` with helm for v1.5.4

---

content/docs/1.6.0/references/settings.md
content/docs/1.6.1/references/settings.md
content/docs/1.7.0/references/settings.md

It was missing
Fixes https://github.com/longhorn/longhorn/issues/7894

Add Snapshot Maximum Count to the Settings Reference page

---

content/docs/1.6.0/advanced-resources/security/volume-encryption.md

Reworded the section on "Using an Encrypted Volume" to make more grammatical sense.
None
Helps the website docs make more grammatical sense.

volume-encryption.md - rewording/grammar

---

content/docs/1.4.5/high-availability/recover-volume-when-read-only.md
content/docs/1.5.4/high-availability/recover-volume-when-read-only.md
content/docs/1.6.0/high-availability/recover-volume-when-read-only.md
content/docs/1.6.1/high-availability/recover-volume-when-read-only.md
content/docs/1.7.0/high-availability/recover-volume-when-read-only.md

ref: https://github.com/longhorn/longhorn/issues/7843
change the behavior of the auto remount read only volume documents

doc: update the behavior of remount read only volume

---

content/docs/1.4.4/best-practices.md
content/docs/1.5.3/best-practices.md

Issue longhorn/longhorn#7666
Should update the latest version of SLE and SLE Micro to the recently released and supported docs. 
https://github.com/longhorn/longhorn/wiki/Version-Update-Policy#os-distro-version-update
@roger-ryao Please help follow up with distro releases including OS and K3s/RKE2, and update the pipelines and doc accordingly. You can refer to the above document to understand more about our `Version Update Policy`.

docs(os): support SLE 15.5 and SLE Micro 5.5 to 1.5.3 and 1.4.4

---

content/docs/1.4.5/volumes-and-nodes/trim-filesystem.md
content/docs/1.5.4/volumes-and-nodes/trim-filesystem.md
content/docs/1.6.1/nodes-and-volumes/volumes/trim-filesystem.md
content/docs/1.7.0/nodes-and-volumes/volumes/trim-filesystem.md

longhorn/longhorn#7103
I wanted to clarify the effects of https://github.com/longhorn/longhorn-engine/pull/1008. In addition, there were a few things in this doc that confused me when I read it at the start of working on longhorn/longhorn#7103.

Explain trim behavior while rebuilding and clean up doc

---

content/kb/kubernetes-resource-revision-frequency-expectations.md
content/kb/space-consumption-guideline.md
content/kb/troubleshooting-engine-upgrading-stuck-in-deadlock.md
content/kb/troubleshooting-fstrim-error.md
content/kb/troubleshooting-rwx-mount-ownership-set-to-nobody.md
content/kb/troubleshooting-rwx-volume-fails-to-attached-caused-by-protocol-not-supported.md
content/kb/troubleshooting-some-old-instance-manager-pods-are-still-running-after-upgrade.md
content/kb/troubleshooting-volume-filesystem-corruption.md
content/kb/troubleshooting-volume-with-multipath.md
content/kb/troubleshooting-websocket_handshake_error_with_unexpected_response_code_200.md

Fix "Knowledge Base"

---

content/docs/1.4.0/references/storage-class-parameters.md
content/docs/1.4.1/references/storage-class-parameters.md
content/docs/1.4.2/references/storage-class-parameters.md
content/docs/1.4.3/references/storage-class-parameters.md
content/docs/1.4.4/references/storage-class-parameters.md
content/docs/1.4.5/references/storage-class-parameters.md
content/docs/1.5.0/references/storage-class-parameters.md
content/docs/1.5.1/references/storage-class-parameters.md
content/docs/1.5.2/references/storage-class-parameters.md
content/docs/1.5.3/references/storage-class-parameters.md
content/docs/1.5.4/references/storage-class-parameters.md
content/docs/1.5.5/references/storage-class-parameters.md
content/docs/1.6.0/references/storage-class-parameters.md
content/docs/1.6.1/references/storage-class-parameters.md
content/docs/1.7.0/references/storage-class-parameters.md

doc(recurring-job): remove extra s on "Jobs" in parameters.recurringJobsSelector

---

content/docs/1.6.0/deploy/install/install-with-fleet.md
content/docs/1.6.1/deploy/install/install-with-fleet.md
content/docs/1.7.0/deploy/install/install-with-fleet.md

Issue https://github.com/longhorn/longhorn/issues/8214
Refine fleet document for ignoring modified crd.

doc: refine fleet document for ignoring modified crd

---

content/docs/1.5.5/deploy/important-notes/index.md
content/docs/1.5.5/volumes-and-nodes/pvc-ownership-and-permission.md
content/docs/1.6.1/deploy/important-notes/index.md
content/docs/1.6.1/nodes-and-volumes/volumes/pvc-ownership-and-permission.md
content/docs/1.6.2/deploy/important-notes/index.md
content/docs/1.6.2/nodes-and-volumes/volumes/pvc-ownership-and-permission.md
content/docs/1.7.0/deploy/important-notes/index.md
content/docs/1.7.0/nodes-and-volumes/volumes/pvc-ownership-and-permission.md

Add doc for Longhorn PVC ownership and permission

---

content/docs/1.7.0/nodes-and-volumes/volumes/rwx-volumes.md

Longhorn/longhorn#7872
Issue #

rwx: add "Configuring Volume Locality for an RWX Volume"

---

content/kb/troubleshooting-failed-rwx-mount-due-to-connection-timeout.md
content/kb/troubleshooting-rwx-volume-fails-to-attached-caused-by-protocol-not-supported.md

kb: update "Troubleshooting: RWX Volume Fails to Be Attached Caused by `Protocol not supported`"

---

content/docs/1.5.5/references/examples.md
content/docs/1.6.1/references/examples.md
content/docs/1.6.2/references/examples.md
content/docs/1.7.0/references/examples.md

longhorn/longhorn#8198
Adds the example from https://github.com/longhorn/longhorn/pull/8200/files to the website.
I tried to match the line break behavior from the rest of the page, but it was inconsistent, so I ended up unifying it according to the suggestions of my Markdown linter.
Creating as a draft until https://github.com/longhorn/longhorn/pull/8200 merges (in case that one changes).

Add an example that uses a generic ephemeral volume

---

content/docs/1.7.0/references/helm-values.md

Issue # longhorn/longhorn#7889

doc(ingress): update new field `pathType`

---

content/docs/1.6.0/deploy/install/install-with-argocd.md
content/docs/1.6.0/deploy/install/install-with-fleet.md
content/docs/1.6.0/deploy/install/install-with-flux.md
content/docs/1.6.0/deploy/upgrade/longhorn-manager.md
content/docs/1.6.1/deploy/install/install-with-argocd.md
content/docs/1.6.1/deploy/install/install-with-fleet.md
content/docs/1.6.1/deploy/install/install-with-flux.md
content/docs/1.6.1/deploy/upgrade/longhorn-manager.md
content/docs/1.7.0/deploy/install/install-with-argocd.md
content/docs/1.7.0/deploy/install/install-with-fleet.md
content/docs/1.7.0/deploy/install/install-with-flux.md
content/docs/1.7.0/deploy/upgrade/longhorn-manager.md

Issue https://github.com/longhorn/longhorn/issues/8240
add upgrade with gitops documents

doc: add upgrade with gitops documents

---

content/docs/1.7.0/v2-data-engine/features/_index.md

v2 volume: support filesystem trim

---

content/docs/1.7.0/advanced-resources/os-distro-specific/container-optimized-os-support.md
content/docs/1.7.0/best-practices.md
content/docs/1.7.0/deploy/install/_index.md

Issue longhorn/longhorn#6165
Provide instructions for configuring the environment when Container-Optimized OS is used as the base image for Google Kubernetes Engine (GKE).

doc(1.7.0): support GKE Container-Optimized OS

---

content/docs/1.7.0/advanced-resources/system-backup-restore/backup-longhorn-system.md

Issue # longhorn/longhorn#8056

doc: remove PodSecurityPolicies for system backup

---

content/docs/1.6.1/snapshots-and-backups/scheduling-backups-and-snapshots.md

Replaced PersitentVolumeClam -> PersistentVolumeClaim

Fix typo in `scheduling-backups-amd-snapshots.md`

---

content/docs/1.7.0/deploy/important-notes/index.md

Document minimum XFS volume size

---

content/docs/1.7.0/advanced-resources/backing-image/backing-image.md
content/docs/1.7.0/references/settings.md

ref: https://github.com/longhorn/longhorn/issues/2856

doc(backing image): add ha, scheduling and eviction feature to the doc

---

content/docs/1.6.2/deploy/install/install-with-argocd.md

the helm values changed and are not longer correct, so I corrected them according to the official helm chart https://github.com/longhorn/charts/blob/v1.6.x/charts/longhorn/values.yaml#L165
Issue #

doc(install-argocd): updated to the right helm values

---

content/docs/1.7.0/advanced-resources/deploy/revision_counter.md
content/docs/1.7.0/references/helm-values.md
content/docs/1.7.0/references/settings.md
content/docs/1.7.0/references/storage-class-parameters.md

Disable revision counter by default

---

content/docs/1.7.0/references/helm-values.md
content/docs/1.7.0/references/settings.md

https://github.com/longhorn/longhorn/issues/8365

feat: add autoCleanupSnapshotWhenDeleteBackup

---

content/docs/1.7.0/references/helm-values.md
content/docs/1.7.0/references/settings.md

Make long gRPC timeout configurable

---

content/docs/1.6.0/advanced-resources/os-distro-specific/okd-support.md
content/docs/1.6.1/advanced-resources/os-distro-specific/okd-support.md
content/docs/1.6.2/advanced-resources/os-distro-specific/okd-support.md
content/docs/1.6.3/advanced-resources/os-distro-specific/okd-support.md
content/docs/1.7.0/advanced-resources/os-distro-specific/okd-support.md

Issue # longhorn/longhorn#8359, okd-project/okd#1165

doc(distro): okd does not support ARM

---

content/docs/1.7.0/references/reference-setup-performance-scalability-and-sizing-guidelines.md

Add report for  Reference Setup, Performance, Scalability, and Sizing Guidelines

---

content/docs/1.6.2/deploy/install/install-with-argocd.md
content/docs/1.6.3/deploy/install/install-with-argocd.md

Issue #
Original is static content, this PR fixed to `{{< current-version >}}`

Fix install with argocd targetRevision not match each version

---

content/kb/troubleshooting-orphan-iscsi-session-error.md

Add Troubleshooting: Orphan ISCSI Session Error

---

content/docs/1.7.0/v2-data-engine/features/_index.md
content/docs/1.7.0/v2-data-engine/features/node-disk-support.md

doc(v2 data engine): add node disk (nvme, virtio and aio) support

---

content/docs/1.5.6/best-practices.md
content/docs/1.6.3/best-practices.md
content/docs/1.7.0/best-practices.md

Update the best practice page to mention some broken kernels

---

content/docs/1.7.0/advanced-resources/backing-image/backing-image-encryption.md
content/docs/1.7.0/advanced-resources/backing-image/backing-image.md

https://github.com/longhorn/longhorn/issues/7051
Add document for backing image encryption

Lh7051 backingimage encryption support

---

content/docs/1.7.0/advanced-resources/os-distro-specific/okd-support.md

Issue # longhorn/longhorn#8300
Users can know how to deploy Longhorn with the manifest file.

doc(okd): add a section to deploy Longhorn by the manifest

---

content/docs/1.7.0/references/settings.md

Issue # longhorn/longhorn#7173

doc(setting): add methods to check if a setting is applied.

---

content/docs/1.7.0/advanced-resources/longhornctl/_index.md

doc(longhornctl): fix the link to document

---

content/docs/1.7.0/deploy/install/_index.md
content/docs/1.7.0/nodes-and-volumes/nodes/default-disk-and-node-config.md
content/docs/1.7.0/nodes-and-volumes/nodes/disks-or-nodes-eviction.md
content/docs/1.7.0/nodes-and-volumes/nodes/multidisk.md
content/docs/1.7.0/nodes-and-volumes/nodes/node-conditions.md
content/docs/1.7.0/nodes-and-volumes/nodes/scheduling.md
content/docs/1.7.0/nodes-and-volumes/nodes/storage-tags.md

Issue # longhorn/longhorn#7571
Explain the new node conditions.
`None`
`None`

doc(node): node conditions for environment checks

---

content/docs/1.5.0/references/networking.md
content/docs/1.5.1/references/networking.md
content/docs/1.5.2/references/networking.md
content/docs/1.5.3/references/networking.md
content/docs/1.5.4/references/networking.md
content/docs/1.5.5/references/networking.md
content/docs/1.5.6/references/networking.md
content/docs/1.6.0/references/networking.md
content/docs/1.6.1/references/networking.md
content/docs/1.6.2/references/networking.md
content/docs/1.6.3/references/networking.md
content/docs/1.7.0/references/networking.md

doc(network): update Longhorn Networking

---

content/docs/1.7.0/v2-data-engine/prerequisites.md

doc(v2): describe better the disks supported

---

content/docs/1.7.0/deploy/important-notes/index.md

Longhorn/longhorn#7672
Longhorn/longhorn#7534
Longhorn/longhorn#7641
Longhorn/longhorn#9054
Longhorn/longhorn#7927
Longhorn/longhorn#7070
Longhorn/longhorn#2856
Longhorn/longhorn#6205
Longhorn/longhorn#2765

doc(v1.7.0): update "Important Notes"

---

content/docs/1.7.0/deploy/important-notes/index.md
content/docs/1.7.0/high-availability/rwx-volume-fast-failover.md
content/docs/1.7.0/nodes-and-volumes/volumes/rwx-volumes.md
content/docs/1.7.0/references/settings.md

Issue https://github.com/longhorn/longhorn/issues/6205
Another piece of RWX HA - document the feature and its enabling setting.

feat(rwx ha): Add rwx volume fast failover.

---

content/docs/1.7.0/deploy/install/_index.md
content/docs/1.7.0/v2-data-engine/quick-start.md

Issue # longhorn/longhorn#9075
Users can understand how to use the Longhorn CLI tool to check/install/set up the environment before installing the Longhorn.

doc(install): add Longhorn CLI in quick installation section

---

content/docs/1.5.0/deploy/uninstall/_index.md
content/docs/1.5.1/deploy/uninstall/_index.md
content/docs/1.5.2/deploy/uninstall/_index.md
content/docs/1.5.3/deploy/uninstall/_index.md
content/docs/1.5.4/deploy/uninstall/_index.md
content/docs/1.5.5/deploy/uninstall/_index.md
content/docs/1.5.6/deploy/uninstall/_index.md
content/docs/1.6.0/deploy/uninstall/_index.md
content/docs/1.6.1/deploy/uninstall/_index.md
content/docs/1.6.2/deploy/uninstall/_index.md
content/docs/1.6.3/deploy/uninstall/_index.md
content/docs/1.7.0/deploy/uninstall/_index.md

Issue https://github.com/longhorn/longhorn/issues/9116, `[DOC] Last-ditch uninstall cleanup instructions are out of date.`

docs:  Update forcible CRD deletion script in uninstall page.

---

layouts/partials/home/project-info.html

feat: add Rancher Academy Longhorn Basis link

---

content/docs/1.7.0/deploy/install/_index.md

Issue # longhorn/longhorn#9139
Some Immutable Linux dirstro require a reboot of the worker nodes after executing the Longhorn CLI `install` sub-command.

doc(install): immutable distro require a reboot

---

content/docs/1.7.0/deploy/important-notes/index.md
content/docs/1.7.0/deploy/install/_index.md

Issue # longhorn/longhorn#9239

doc(script): deprecated note for environment_check.sh script

---

content/docs/1.5.0/best-practices.md
content/docs/1.5.1/best-practices.md
content/docs/1.5.2/best-practices.md
content/docs/1.5.3/best-practices.md
content/docs/1.5.4/best-practices.md
content/docs/1.5.5/best-practices.md
content/docs/1.5.6/best-practices.md
content/docs/1.6.0/best-practices.md
content/docs/1.6.1/best-practices.md
content/docs/1.6.2/best-practices.md
content/docs/1.6.3/best-practices.md
content/docs/1.7.0/best-practices.md
content/docs/archives/1.2.3/best-practices.md
content/docs/archives/1.2.4/best-practices.md
content/docs/archives/1.2.5/best-practices.md
content/docs/archives/1.2.6/best-practices.md
content/docs/archives/1.3.0/best-practices.md
content/docs/archives/1.3.1/best-practices.md
content/docs/archives/1.3.2/best-practices.md
content/docs/archives/1.3.3/best-practices.md
content/docs/archives/1.3.4/best-practices.md
content/docs/archives/1.4.0/best-practices.md
content/docs/archives/1.4.1/best-practices.md
content/docs/archives/1.4.2/best-practices.md
content/docs/archives/1.4.3/best-practices.md
content/docs/archives/1.4.4/best-practices.md

doc(os): bump OS versions supported by Longhorn

---

content/docs/1.7.0/advanced-resources/_index.md
content/docs/1.7.0/deploy/_index.md
content/docs/1.7.0/deploy/important-notes/index.md
content/docs/1.7.0/high-availability/_index.md
content/docs/1.7.0/important-notes/_index.md
content/docs/1.7.0/maintenance/_index.md
content/docs/1.7.0/monitoring/_index.md
content/docs/1.7.0/nodes-and-volumes/_index.md
content/docs/1.7.0/references/_index.md
content/docs/1.7.0/snapshots-and-backups/_index.md
content/docs/1.7.0/troubleshoot/_index.md

docs(v1.7.0): add "Auto-Balance Pressured Disks" in important notes

---

content/docs/1.7.0/v2-data-engine/features/node-disk-support.md
content/docs/1.7.1/v2-data-engine/features/node-disk-support.md
content/docs/1.7.2/v2-data-engine/features/node-disk-support.md
content/docs/1.8.0/v2-data-engine/features/node-disk-support.md

fix(v2 volume): fix Node Disk Support

---

content/docs/1.7.2/nodes-and-volumes/nodes/node-conditions.md
content/docs/1.8.0/nodes-and-volumes/nodes/node-conditions.md

Issue # longhorn/longhorn#9153

doc(node): add `KernelModulesLoaded` node condition

---

content/docs/1.6.4/advanced-resources/os-distro-specific/okd-support.md
content/docs/1.6.4/references/helm-values.md
content/docs/1.7.2/advanced-resources/os-distro-specific/okd-support.md
content/docs/1.7.2/references/helm-values.md
content/docs/1.8.0/advanced-resources/os-distro-specific/okd-support.md
content/docs/1.8.0/references/helm-values.md

docs(openshift): remove mirrored openshift image from Longhorn

---

content/docs/1.5.0/snapshots-and-backups/scheduling-backups-and-snapshots.md
content/docs/1.5.1/snapshots-and-backups/scheduling-backups-and-snapshots.md
content/docs/1.5.2/snapshots-and-backups/scheduling-backups-and-snapshots.md
content/docs/1.5.3/snapshots-and-backups/scheduling-backups-and-snapshots.md
content/docs/1.5.4/snapshots-and-backups/scheduling-backups-and-snapshots.md
content/docs/1.5.5/snapshots-and-backups/scheduling-backups-and-snapshots.md
content/docs/1.5.6/snapshots-and-backups/scheduling-backups-and-snapshots.md
content/docs/1.6.0/snapshots-and-backups/scheduling-backups-and-snapshots.md
content/docs/1.6.1/snapshots-and-backups/scheduling-backups-and-snapshots.md
content/docs/1.6.2/snapshots-and-backups/scheduling-backups-and-snapshots.md
content/docs/1.6.3/snapshots-and-backups/scheduling-backups-and-snapshots.md
content/docs/1.6.4/snapshots-and-backups/scheduling-backups-and-snapshots.md
content/docs/1.7.0/snapshots-and-backups/scheduling-backups-and-snapshots.md
content/docs/1.7.1/snapshots-and-backups/scheduling-backups-and-snapshots.md
content/docs/1.7.2/snapshots-and-backups/scheduling-backups-and-snapshots.md
content/docs/1.8.0/snapshots-and-backups/scheduling-backups-and-snapshots.md
content/docs/archives/1.3.3/snapshots-and-backups/scheduling-backups-and-snapshots.md
content/docs/archives/1.3.4/snapshots-and-backups/scheduling-backups-and-snapshots.md
content/docs/archives/1.4.2/snapshots-and-backups/scheduling-backups-and-snapshots.md
content/docs/archives/1.4.3/snapshots-and-backups/scheduling-backups-and-snapshots.md
content/docs/archives/1.4.4/snapshots-and-backups/scheduling-backups-and-snapshots.md

Hello, sorry for not filling the template. Should that be corrected? Thanks.

docs(backups): fix a typo

---

content/docs/1.7.2/references/settings.md

Issue # longhorn/longhorn#8319

doc(backup): add the setting `Backup Execution Timeout`

---

content/docs/1.6.4/snapshots-and-backups/backup-and-restore/restore-statefulset.md
content/docs/1.7.1/snapshots-and-backups/backup-and-restore/restore-statefulset.md
content/docs/1.7.2/snapshots-and-backups/backup-and-restore/restore-statefulset.md
content/docs/1.8.0/snapshots-and-backups/backup-and-restore/restore-statefulset.md

Issue https://github.com/longhorn/longhorn/issues/9571

docs: added how to create PV from encrypted volume step

---

content/docs/1.6.4/deploy/important-notes/index.md
content/docs/1.6.4/snapshots-and-backups/backup-and-restore/set-backup-target.md
content/docs/1.7.2/important-notes/_index.md
content/docs/1.7.2/snapshots-and-backups/backup-and-restore/set-backup-target.md
content/docs/1.8.0/important-notes/_index.md
content/docs/1.8.0/snapshots-and-backups/backup-and-restore/set-backup-target.md

Issue # longhorn/longhorn#9530

doc(backup): related custom resources might disappear

---

content/docs/1.8.0/references/settings.md
content/docs/1.8.0/v2-data-engine/features/configurable-cpu-cores.md

docs(v2 data engine): add V2 Data Engine CPU Mask

---

content/docs/1.5.0/volumes-and-nodes/detaching-volumes.md
content/docs/1.5.1/volumes-and-nodes/detaching-volumes.md
content/docs/1.5.2/volumes-and-nodes/detaching-volumes.md
content/docs/1.5.3/volumes-and-nodes/detaching-volumes.md
content/docs/1.5.4/volumes-and-nodes/detaching-volumes.md
content/docs/1.5.5/volumes-and-nodes/detaching-volumes.md
content/docs/1.5.6/volumes-and-nodes/detaching-volumes.md
content/docs/1.6.0/nodes-and-volumes/volumes/detaching-volumes.md
content/docs/1.6.1/nodes-and-volumes/volumes/detaching-volumes.md
content/docs/1.6.2/nodes-and-volumes/volumes/detaching-volumes.md
content/docs/1.6.3/nodes-and-volumes/volumes/detaching-volumes.md
content/docs/1.7.0/nodes-and-volumes/volumes/detaching-volumes.md
content/docs/1.7.1/nodes-and-volumes/volumes/detaching-volumes.md
content/docs/1.8.0/nodes-and-volumes/volumes/detaching-volumes.md

Explain how to scale down DaemonSets without deleting the DaemonSet.

docs(detach): Explain how to scale down DaemonSets

---

content/docs/1.6.0/best-practices.md
content/docs/1.6.0/deploy/important-notes/index.md
content/docs/1.6.1/best-practices.md
content/docs/1.6.1/deploy/important-notes/index.md
content/docs/1.6.2/best-practices.md
content/docs/1.6.2/deploy/important-notes/index.md
content/docs/1.6.3/best-practices.md
content/docs/1.6.3/deploy/important-notes/index.md
content/docs/1.6.4/best-practices.md
content/docs/1.6.4/deploy/important-notes/index.md
content/docs/1.7.0/best-practices.md
content/docs/1.7.0/important-notes/_index.md
content/docs/1.7.1/best-practices.md
content/docs/1.7.1/important-notes/_index.md
content/docs/1.7.2/best-practices.md
content/docs/1.7.2/important-notes/_index.md
content/docs/1.7.3/best-practices.md
content/docs/1.7.3/important-notes/_index.md
content/docs/1.8.0/best-practices.md
content/docs/1.8.0/important-notes/_index.md

docs: move Supported Kubernetes Versions to Best Practices

---

content/docs/1.6.4/deploy/important-notes/index.md
content/docs/1.6.4/deploy/upgrade/longhorn-manager.md
content/docs/1.7.3/deploy/upgrade/longhorn-manager.md
content/docs/1.7.3/important-notes/_index.md
content/docs/1.8.0/deploy/upgrade/longhorn-manager.md
content/docs/1.8.0/important-notes/_index.md

Issue https://github.com/longhorn/longhorn/issues/9569
Document pre-upgrade check event behavior.

docs(upgrade) pre-upgrade check will event

---

content/docs/1.5.0/advanced-resources/deploy/priority-class.md
content/docs/1.5.1/advanced-resources/deploy/priority-class.md
content/docs/1.5.2/advanced-resources/deploy/priority-class.md
content/docs/1.5.3/advanced-resources/deploy/priority-class.md
content/docs/1.5.4/advanced-resources/deploy/priority-class.md
content/docs/1.5.5/advanced-resources/deploy/priority-class.md
content/docs/1.5.6/advanced-resources/deploy/priority-class.md

https://github.com/longhorn/longhorn/issues/9612

docs(1.5.x): add warning about cluster default priority class

---

content/docs/1.6.0/snapshots-and-backups/backup-and-restore/set-backup-target.md
content/docs/1.6.1/snapshots-and-backups/backup-and-restore/set-backup-target.md
content/docs/1.6.2/snapshots-and-backups/backup-and-restore/set-backup-target.md
content/docs/1.6.3/snapshots-and-backups/backup-and-restore/set-backup-target.md
content/docs/1.6.4/deploy/important-notes/index.md
content/docs/1.6.4/snapshots-and-backups/backup-and-restore/set-backup-target.md
content/docs/1.7.0/snapshots-and-backups/backup-and-restore/set-backup-target.md
content/docs/1.7.1/snapshots-and-backups/backup-and-restore/set-backup-target.md
content/docs/1.7.2/important-notes/_index.md
content/docs/1.7.2/snapshots-and-backups/backup-and-restore/set-backup-target.md
content/docs/1.7.3/important-notes/_index.md
content/docs/1.7.3/snapshots-and-backups/backup-and-restore/set-backup-target.md
content/docs/1.8.0/important-notes/_index.md
content/docs/1.8.0/snapshots-and-backups/backup-and-restore/set-backup-target.md

docs: add a notice prohibiting retention policies on backup targets

---

content/docs/1.6.4/best-practices.md
content/docs/1.7.3/best-practices.md
content/docs/1.8.0/best-practices.md

Issue longhorn/longhorn#9752, longhorn/longhorn#9803, longhorn/longhorn#9802
Add CoreDNS to best practices.
`None`
`None`

doc(1.8.0, 1.7.4, 1.6.3): add CoreDNS setup to best practices

---

content/docs/1.7.2/deploy/install/_index.md
content/docs/1.7.3/deploy/install/_index.md
content/docs/1.8.0/deploy/install/_index.md

Issue # longhorn/longhorn#9153
Update the document that we add a new directory.

doc(deploy): mount host's directory /boot

---

content/docs/1.8.0/best-practices.md

longhorn/longhorn#9879
OS Distro and K8S Version Update for longhorn v1.8.0
- https://github.com/longhorn/longhorn/issues/9684
- https://github.com/longhorn/longhorn/issues/9879

docs(v1.8.0): Update best practices for OS and K8S version

---

content/docs/1.7.0/important-notes/_index.md
content/docs/1.7.1/important-notes/_index.md
content/docs/1.7.2/important-notes/_index.md
content/docs/1.7.3/important-notes/_index.md
content/docs/1.8.0/advanced-resources/deploy/storage-network.md
content/docs/1.8.0/advanced-resources/os-distro-specific/talos-linux-support.md
content/docs/1.8.0/important-notes/_index.md

docs(v1.8.0): remove old items from important notes

---

content/docs/1.8.0/nodes-and-volumes/nodes/node-conditions.md

Issue https://github.com/longhorn/longhorn/issues/9983 https://github.com/longhorn/longhorn-manager/pull/3350
Added documentation for the HugePagesAvailable node condition
Explains the purpose of the condition in ensuring HugePages (2Mi) configuration for Longhorn v2 data engine

docs: add hugepagesavailable node condition details

---

content/docs/1.6.0/deploy/important-notes/index.md
content/docs/1.6.0/deploy/upgrade/_index.md
content/docs/1.6.1/deploy/important-notes/index.md
content/docs/1.6.1/deploy/upgrade/_index.md
content/docs/1.6.2/deploy/important-notes/index.md
content/docs/1.6.2/deploy/upgrade/_index.md
content/docs/1.6.3/deploy/important-notes/index.md
content/docs/1.6.3/deploy/upgrade/_index.md
content/docs/1.6.4/deploy/important-notes/index.md
content/docs/1.6.4/deploy/upgrade/_index.md
content/docs/1.7.0/deploy/upgrade/_index.md
content/docs/1.7.0/important-notes/_index.md
content/docs/1.7.1/deploy/upgrade/_index.md
content/docs/1.7.1/important-notes/_index.md
content/docs/1.7.2/deploy/upgrade/_index.md
content/docs/1.7.2/important-notes/_index.md
content/docs/1.7.3/deploy/upgrade/_index.md
content/docs/1.7.3/important-notes/_index.md
content/docs/1.8.0/deploy/upgrade/_index.md
content/docs/1.8.0/important-notes/_index.md

Issue https://github.com/longhorn/longhorn/issues/9440
Mention some important items to check before doing upgrade.
When the text is approved, this will be copied to v1.6.x and v1.7.x docs.

doc(1.8.0): add important note with things to check before upgrade

---

content/docs/1.7.3/advanced-resources/os-distro-specific/container-optimized-os-support.md
content/docs/1.8.0/advanced-resources/os-distro-specific/container-optimized-os-support.md

Issue longhorn/longhorn#10049
https://github.com/longhorn/longhorn/issues/10049#issuecomment-2562253129
`None`
`None`

doc(1.8.0, 1.7.3): volume encryption limitation for COS

---

content/docs/1.8.0/advanced-resources/backing-image/backing-image.md
content/docs/1.8.0/advanced-resources/system-backup-restore/backup-longhorn-system.md
content/docs/1.8.0/advanced-resources/system-backup-restore/restore-longhorn-system.md
content/docs/1.8.0/v2-data-engine/features/_index.md

ref: [longhorn/longhorn 6341](https://github.com/longhorn/longhorn/issues/6341)

doc: add v2 backing image doc

---

content/docs/1.6.4/best-practices.md

docs: update Kubernetes Version in v1.6.4

---

content/docs/1.6.0/nodes-and-volumes/volumes/volume-size.md
content/docs/1.6.1/nodes-and-volumes/volumes/volume-size.md
content/docs/1.6.2/nodes-and-volumes/volumes/volume-size.md
content/docs/1.6.3/nodes-and-volumes/volumes/volume-size.md
content/docs/1.6.4/nodes-and-volumes/volumes/volume-size.md
content/docs/1.7.0/nodes-and-volumes/volumes/volume-size.md
content/docs/1.7.1/nodes-and-volumes/volumes/volume-size.md
content/docs/1.7.2/nodes-and-volumes/volumes/volume-size.md
content/docs/1.7.3/nodes-and-volumes/volumes/volume-size.md
content/docs/1.8.0/nodes-and-volumes/volumes/volume-size.md

Issue #[8843](https://github.com/longhorn/longhorn/issues/8843)
I rewrote the descriptions of both terms to facilitate quicker understanding of the concepts. The descriptions expand on the the tooltips provided in the linked issue.

Rewrite descriptions of volume terms: `Size` and `Actual Size`

---

content/docs/1.8.0/advanced-resources/security/volume-encryption.md
content/docs/1.8.0/important-notes/_index.md
content/docs/1.8.0/v2-data-engine/features/_index.md

Issue # longhorn/longhorn#7355

docs(crypto): v2 volume encryption support

---

content/docs/1.8.0/nodes-and-volumes/nodes/node-conditions.md

Issue https://github.com/longhorn/longhorn/issues/9915
We have already added kernel module checks for engine v2.  
However, the documentation lacked explanations for the newly added kernel modules.

docs: add required kernel modules for engine v2

---

content/docs/1.8.0/important-notes/_index.md

docs(v1.8.0): update important note

---

content/docs/1.8.0/important-notes/_index.md
content/docs/1.8.0/references/helm-values.md
content/docs/1.8.0/snapshots-and-backups/csi-snapshot-support/enable-csi-snapshot-support.md
content/docs/1.9.0/important-notes/_index.md

docs(v1.8.0): update image versions

---

content/docs/1.8.0/references/settings.md
content/docs/1.8.1/references/settings.md
content/docs/1.9.0/references/settings.md

Issue https://github.com/longhorn/longhorn/issues/10323
Straight copy/paste from 1.7.x docs.

docs: add backup-execution-timeout setting reference

---

content/docs/1.9.0/advanced-resources/system-backup-restore/backup-longhorn-system.md
content/docs/1.9.0/important-notes/_index.md

Issue longhorn/longhorn#6534
- Add to important note.
- Add steps for creating recurring system backups.
`None`
`None`

doc(1.9.0): recurring system backup

---

content/kb/troubleshooting-two-active-engines.md

docs: troubleshooting two active engines during volume live migration

---

content/docs/1.9.0/advanced-resources/system-backup-restore/backup-longhorn-system.md

Issue longhorn/longhorn#6534
https://github.com/longhorn/website/pull/1045#discussion_r1948675253
`None`
`None`

doc(1.9.0): fix convention and formatting

---

content/docs/1.7.3/references/helm-values.md

docs(1.7.3): update image tags in "References > Helm Values"

---

content/docs/1.8.1/advanced-resources/deploy/customizing-default-settings.md
content/docs/1.8.1/references/settings.md
content/docs/1.9.0/advanced-resources/deploy/customizing-default-settings.md
content/docs/1.9.0/references/settings.md

docs: add setting "upgrade-responder-url" to v1.8.1 and v1.9.0

---

content/docs/1.8.1/best-practices.md

longhorn/longhorn#10400
OS Distro and K8S Version Update for longhorn `v1.8.1`

docs(v1.8.1): Update best practices for OS and K8S version

---

content/docs/1.9.0/references/settings.md

Issue longhorn/longhorn#7047
Added items to usage metric collection:
- Host system architecture.
- Count of volumes that are encrypted or unencrypted.
`None`
`None`

doc(1.9.0): add items to usage metric collection

---

content/docs/1.6.0/references/settings.md
content/docs/1.6.1/references/settings.md
content/docs/1.6.2/references/settings.md
content/docs/1.6.3/references/settings.md
content/docs/1.6.4/references/settings.md
content/docs/1.6.5/references/settings.md
content/docs/1.7.0/references/settings.md
content/docs/1.7.1/references/settings.md
content/docs/1.7.2/references/settings.md
content/docs/1.7.3/references/settings.md
content/docs/1.7.4/references/settings.md
content/docs/1.8.0/references/settings.md
content/docs/1.8.1/references/settings.md
content/docs/1.9.0/references/settings.md

docs: update settings in Danger Zone

---

content/docs/1.9.0/snapshots-and-backups/csi-snapshot-support/csi-volume-snapshot-associated-with-longhorn-backup.md

ref: https://github.com/longhorn/longhorn/issues/9785
add doc for backup mode parameters in csi volumesnaoshot backup type

doc: update csi snapshot backup type for backup mode parameter

---

content/docs/1.7.0/advanced-resources/backing-image/backing-image.md
content/docs/1.7.1/advanced-resources/backing-image/backing-image.md
content/docs/1.7.2/advanced-resources/backing-image/backing-image.md
content/docs/1.7.3/advanced-resources/backing-image/backing-image.md
content/docs/1.7.4/advanced-resources/backing-image/backing-image.md
content/docs/1.8.0/advanced-resources/backing-image/backing-image.md
content/docs/1.8.1/advanced-resources/backing-image/backing-image.md
content/docs/1.8.2/advanced-resources/backing-image/backing-image.md
content/docs/1.9.0/advanced-resources/backing-image/backing-image.md

ref: https://github.com/longhorn/longhorn/issues/10093

doc: add exporting backing image details

---

content/docs/1.9.0/deploy/install/_index.md
content/docs/1.9.0/v2-data-engine/quick-start.md

Issue https://github.com/longhorn/longhorn/issues/9256

doc(v1.9.0): update notes for sle micro in longhorn command line interface installation

---

content/docs/1.9.0/references/settings.md

docs(1.9.0): update Guaranteed Instance Manager CPU for V2 Data Engine

---

content/docs/1.9.0/references/helm-values.md
content/docs/1.9.0/references/settings.md

Issue # longhorn/longhorn#9213

docs(backup): introduce the setting "auto-cleanup-snapshot-after-on-demand-backup-completed"

---

content/docs/1.9.0/monitoring/metrics.md

https://github.com/longhorn/longhorn/issues/10550

docs: add engine rebuild progress metric to monitoring docs

---

content/docs/1.9.0/monitoring/metrics.md

Issue https://github.com/longhorn/longhorn/issues/10722

docs: add engine and replica metrics to monitoring docs

---

content/docs/1.9.0/v2-data-engine/features/ublk-frontend-support.md

feat: ublk frontend for v2 data engine

---

content/docs/1.9.0/important-notes/_index.md

docs(1.9.0): Important Notes

---

content/docs/1.9.0/advanced-resources/rebuilding/fast-replica-rebuilding.md
content/docs/1.9.0/advanced-resources/rebuilding/offline-replica-rebuilding.md
content/docs/1.9.0/important-notes/_index.md

Issue # longhorn/longhorn#8443
Add the important note.
Introduce offline replica rebuilding in advanced-resources/rebuilding.

docs(replica): offline replica rebuilding

---

content/docs/1.9.0/advanced-resources/data-cleanup/orphaned-data-cleanup.md
content/docs/1.9.0/advanced-resources/data-cleanup/orphaned-instance-cleanup.md
content/docs/1.9.0/advanced-resources/deploy/customizing-default-settings.md
content/docs/1.9.0/important-notes/_index.md

Issue longhorn/longhorn#6764
- Document for orphaned instance management
- Replace setting `orphanAutoDeletion` with `orphanResourceAutoDeletion`

doc: orphaned instance deletion

---

content/docs/1.8.0/snapshots-and-backups/backup-and-restore/set-backup-target.md
content/docs/1.8.1/snapshots-and-backups/backup-and-restore/set-backup-target.md
content/docs/1.8.2/snapshots-and-backups/backup-and-restore/set-backup-target.md
content/docs/1.9.0/snapshots-and-backups/backup-and-restore/set-backup-target.md

Issue #
Correct some indentation for markdown format in the setting backup target page.

docs: correct markdown format for setting backup targets

---

content/docs/1.9.0/best-practices.md

docs(v1.9.0): Update best practices for OS and K8S version

---

content/docs/1.9.0/references/settings.md

Issue longhorn/longhorn#6764
`orphan-auto-deletion` is replaced by `orphan-resource-auto-deletion` from v1.9.0

doc(setting): replace orphan-auto-deletion with orphan-resource-auto-deletion

---

content/docs/1.9.0/advanced-resources/data-cleanup/orphaned-data-cleanup.md
content/docs/1.9.0/advanced-resources/data-cleanup/orphaned-instance-cleanup.md

Issue https://github.com/longhorn/longhorn/issues/6764
The UI wording has been updated, adjust the documentation as follows:
- Change `Orphaned Data` to `Orphan Resources`
- Change `Replica Data Orphans` to `Replica Data`
- Change `Instance Orphans` to `Instances`
UI PR: https://github.com/longhorn/longhorn-ui/pull/916

doc(1.9.0): update orphaned resources UI

---

content/docs/1.6.0/concepts.md
content/docs/1.6.1/concepts.md
content/docs/1.6.2/concepts.md
content/docs/1.6.3/concepts.md
content/docs/1.6.4/concepts.md
content/docs/1.6.5/concepts.md
content/docs/1.7.0/best-practices.md
content/docs/1.7.0/concepts.md
content/docs/1.7.1/best-practices.md
content/docs/1.7.1/concepts.md
content/docs/1.7.2/best-practices.md
content/docs/1.7.2/concepts.md
content/docs/1.7.3/best-practices.md
content/docs/1.7.3/concepts.md
content/docs/1.7.4/best-practices.md
content/docs/1.7.4/concepts.md
content/docs/1.8.0/best-practices.md
content/docs/1.8.0/concepts.md
content/docs/1.8.1/best-practices.md
content/docs/1.8.1/concepts.md
content/docs/1.8.2/best-practices.md
content/docs/1.8.2/concepts.md
content/docs/1.9.0/best-practices.md
content/docs/1.9.0/concepts.md
content/docs/archives/1.3.0/best-practices.md

docs: remove s390x (experimental) support

---

content/docs/1.9.0/advanced-resources/data-cleanup/orphaned-instance-cleanup.md

longhorn/longhorn 10888
longhorn/website 1107
Issue longhorn/longhorn#10888
Found in PR #1107

fix(orphan): fix typo

---

content/docs/1.9.0/important-notes/_index.md

docs(1.9.0): update important notes

---

content/docs/1.8.0/deploy/upgrade/_index.md
content/docs/1.8.0/deploy/upgrade/longhorn-manager.md
content/docs/1.8.1/deploy/upgrade/_index.md
content/docs/1.8.1/deploy/upgrade/longhorn-manager.md
content/docs/1.8.2/deploy/upgrade/_index.md
content/docs/1.8.2/deploy/upgrade/longhorn-manager.md
content/docs/1.9.0/deploy/upgrade/_index.md
content/docs/1.9.0/deploy/upgrade/longhorn-manager.md
content/docs/1.9.0/deploy/upgrade/upgrade-engine.md

docs: update upgrade docs

---

content/docs/1.9.0/advanced-resources/data-cleanup/orphaned-data-cleanup.md
content/docs/1.9.0/advanced-resources/data-cleanup/orphaned-instance-cleanup.md
content/docs/1.9.0/advanced-resources/deploy/customizing-default-settings.md
content/docs/1.9.0/references/settings.md

docs(1.9.0): add orphan-resource-auto-deletion-grace-period setting

---

content/docs/1.6.0/deploy/upgrade/_index.md
content/docs/1.6.1/deploy/upgrade/_index.md
content/docs/1.6.2/deploy/upgrade/_index.md
content/docs/1.6.3/deploy/upgrade/_index.md
content/docs/1.6.4/deploy/upgrade/_index.md
content/docs/1.6.5/deploy/upgrade/_index.md
content/docs/1.7.0/deploy/upgrade/_index.md
content/docs/1.7.1/deploy/upgrade/_index.md
content/docs/1.7.2/deploy/upgrade/_index.md
content/docs/1.7.3/deploy/upgrade/_index.md
content/docs/1.7.4/deploy/upgrade/_index.md
content/docs/1.8.0/deploy/upgrade/_index.md
content/docs/1.8.1/deploy/upgrade/_index.md
content/docs/1.8.2/deploy/upgrade/_index.md
content/docs/1.9.0/deploy/upgrade/_index.md
content/docs/archives/1.5.0/deploy/upgrade/_index.md
content/docs/archives/1.5.1/deploy/upgrade/_index.md
content/docs/archives/1.5.2/deploy/upgrade/_index.md
content/docs/archives/1.5.3/deploy/upgrade/_index.md
content/docs/archives/1.5.4/deploy/upgrade/_index.md
content/docs/archives/1.5.5/deploy/upgrade/_index.md
content/docs/archives/1.5.6/deploy/upgrade/_index.md

docs: update "Upgrade Path Enforcement and Downgrade Prevention"

---

content/docs/1.8.2/references/storage-class-parameters.md
content/docs/1.9.0/references/storage-class-parameters.md

Issue # longhorn/longhorn#10961

docs: update storage class parameters for the backup target name

---

content/docs/1.6.0/deploy/install/_index.md
content/docs/1.6.1/deploy/install/_index.md
content/docs/1.6.2/deploy/install/_index.md
content/docs/1.6.3/deploy/install/_index.md
content/docs/1.6.4/deploy/install/_index.md
content/docs/1.6.5/deploy/install/_index.md
content/docs/1.7.0/deploy/install/_index.md
content/docs/1.7.1/deploy/install/_index.md
content/docs/1.7.2/deploy/install/_index.md
content/docs/1.7.3/deploy/install/_index.md
content/docs/1.7.4/deploy/install/_index.md
content/docs/1.8.0/deploy/install/_index.md
content/docs/1.8.1/deploy/install/_index.md
content/docs/1.8.2/deploy/install/_index.md
content/docs/1.9.0/deploy/install/_index.md

docs: reorganize Quick Installation

---

content/docs/1.9.0/important-notes/_index.md

fix(1.9.0): fix wrong link

---

content/docs/1.9.0/important-notes/_index.md

docs(1.9.0): update important note

---

content/docs/1.8.0/nodes-and-volumes/nodes/multidisk.md
content/docs/1.8.1/nodes-and-volumes/nodes/multidisk.md
content/docs/1.8.2/nodes-and-volumes/nodes/multidisk.md
content/docs/1.9.0/nodes-and-volumes/nodes/multidisk.md

docs: add related settings to Multiple Disk Support page

---

content/docs/1.7.3/important-notes/_index.md

docs: update longhorn-share-manager hotfix image to v1.7.3 important notes

---

content/docs/1.8.2/important-notes/_index.md

docs(1.8.2): update important notes

---

content/docs/1.10.0/important-notes/_index.md

Issue longhorn/longhorn#2259
For IPv6 support.
`None`
`None`

doc(1.10.0): IPv6 support

---

content/docs/1.9.0/advanced-resources/os-distro-specific/okd-support.md

Updates documentation with latest OpenShift version (4.18)
Issue # 
https://github.com/longhorn/longhorn/issues/11174
Updates documentation with latest OpenShift version (4.18)

feat: Update okd-support.md

---

content/docs/1.10.0/nodes-and-volumes/nodes/multidisk.md
content/docs/1.7.0/nodes-and-volumes/nodes/multidisk.md
content/docs/1.7.1/nodes-and-volumes/nodes/multidisk.md
content/docs/1.7.2/nodes-and-volumes/nodes/multidisk.md
content/docs/1.7.3/nodes-and-volumes/nodes/multidisk.md
content/docs/1.7.4/nodes-and-volumes/nodes/multidisk.md
content/docs/1.8.0/nodes-and-volumes/nodes/multidisk.md
content/docs/1.8.1/nodes-and-volumes/nodes/multidisk.md
content/docs/1.8.2/nodes-and-volumes/nodes/multidisk.md
content/docs/1.8.3/nodes-and-volumes/nodes/multidisk.md
content/docs/1.9.0/nodes-and-volumes/nodes/multidisk.md
content/docs/1.9.1/nodes-and-volumes/nodes/multidisk.md

docs: improve Multiple Disk Support

---

content/docs/1.10.0/snapshots-and-backups/setup-disaster-recovery-volumes.md
content/docs/1.8.0/snapshots-and-backups/setup-disaster-recovery-volumes.md
content/docs/1.8.1/snapshots-and-backups/setup-disaster-recovery-volumes.md
content/docs/1.8.2/snapshots-and-backups/setup-disaster-recovery-volumes.md
content/docs/1.8.3/snapshots-and-backups/setup-disaster-recovery-volumes.md
content/docs/1.9.0/snapshots-and-backups/setup-disaster-recovery-volumes.md
content/docs/1.9.1/snapshots-and-backups/setup-disaster-recovery-volumes.md

docs: improve DR volumes

---

content/docs/1.10.0/v2-data-engine/features/replica-rebuild-qos.md

Issue https://github.com/longhorn/longhorn/issues/10770#issuecomment-2912805775

docs(v1.10.0) replica rebuild qos

---

content/docs/1.10.0/advanced-resources/_index.md
content/docs/1.10.0/deploy/_index.md
content/docs/1.10.0/monitoring/_index.md
content/docs/1.10.0/references/_index.md
content/docs/1.10.0/references/settings.md
content/docs/1.10.0/snapshots-and-backups/_index.md
content/docs/1.10.0/v2-data-engine/_index.md

docs: rename `Deploy` to `Installation and Setup`

---

content/docs/1.10.0/references/settings.md

docs: rename `Global Settings` to `Settings`

---

content/docs/1.10.0/advanced-resources/volumeattachment.md

docs: add "Longhorn VolumeAttachment"

---

content/docs/1.10.0/monitoring/metrics.md

Issue https://github.com/longhorn/longhorn/issues/11223

docs: add disk performance metrics (throughput, iops, latency)

---

content/docs/1.10.0/advanced-resources/os-distro-specific/talos-linux-support.md

Issue #https://github.com/longhorn/longhorn/issues/11015
Talos After 1.10.x disk managment and depreciation of `.machine.disks`

feat(talos): update doc to include new disk management in 1.10.x

---

content/docs/1.10.0/references/settings.md
content/docs/1.10.0/v2-data-engine/features/configurable-cpu-cores.md

docs: update v1.10.0 settings

---

content/docs/1.10.0/advanced-resources/rebuilding/_index.md
content/docs/1.10.0/nodes-and-volumes/volumes/create-volumes.md

Related PR: #1175 
It removes an extra colon and no longer needed issue
N/A
N/A

Removed extra colon and no-longer-needed issue

---

content/docs/1.10.0/references/settings.md

feat: add settings "Log Level" and "Log Path"

---

content/kb/backup-store-lock-conflict-error-message.md

Issue https://github.com/longhorn/longhorn/issues/11293
It adds a post in kb

Add KB: backup store lock conflict error message

---

content/docs/1.7.0/deploy/install/install-with-argocd.md
content/docs/1.7.1/deploy/install/install-with-argocd.md
content/docs/1.7.2/deploy/install/install-with-argocd.md
content/docs/1.7.3/deploy/install/install-with-argocd.md
content/docs/1.7.4/deploy/install/install-with-argocd.md
content/docs/1.8.0/deploy/install/install-with-argocd.md
content/docs/1.8.1/deploy/install/install-with-argocd.md
content/docs/1.8.2/deploy/install/install-with-argocd.md
content/docs/1.8.3/deploy/install/install-with-argocd.md
content/docs/1.9.0/deploy/install/install-with-argocd.md
content/docs/archives/1.6.0/deploy/install/install-with-argocd.md
content/docs/archives/1.6.2/deploy/install/install-with-argocd.md
content/docs/archives/1.6.3/deploy/install/install-with-argocd.md
content/docs/archives/1.6.4/deploy/install/install-with-argocd.md
content/docs/archives/1.6.5/deploy/install/install-with-argocd.md

Issue https://github.com/longhorn/longhorn/discussions/10786
add ignoreDifferences to prevent application out of sync

doc(argocd): add ignoreDifferences to prevent application out of sync

---

content/docs/1.10.0/deploy/install/_index.md
content/docs/1.10.0/v2-data-engine/quick-start.md

[Issue #11430](https://github.com/longhorn/longhorn/issues/11430)
It removes the outdated content and add context about `longhornctl check preflight` command.
N/A
N/A

Removed outdated content and added longhornctl check preflight

---

content/docs/1.10.0/references/settings.md

docs(setting): update Snapshot Data Integrity

---

content/docs/1.10.0/references/settings.md

fix: fix setting descriptions

---

content/docs/1.10.0/references/settings.md

docs(setting): update settings

---

content/docs/1.10.0/important-notes/_index.md
content/docs/1.10.0/references/settings.md

feat(setting): introduce Data Engine Hugepage Enabled

---

content/docs/1.10.0/nodes-and-volumes/nodes/scheduling.md

Issue longhorn/longhorn#10436
It adds detailed explanations of:
- The **Actual Space Usage Condition** and **Scheduling Space Condition**
- The formulas used in evaluating disk eligibility

docs: add disk scheduling formulas #10436

---

content/docs/1.10.0/references/settings.md

docs: update settings

---

content/docs/1.10.0/nodes-and-volumes/volumes/volume-size.md
content/docs/1.8.3/nodes-and-volumes/volumes/volume-size.md
content/docs/1.9.2/nodes-and-volumes/volumes/volume-size.md

Issue # longhorn/longhorn#10718
Add the section to the `Volume Size` page for v1.10.0, v1.9.2, and v1.8.3.

docs(volume): add volume size troubleshooting section

---

content/docs/1.10.0/important-notes/_index.md
content/docs/1.10.0/v2-data-engine/features/interrupt-mode.md

Issue longhorn/longhorn#9834, longhorn/longhorn#11816

doc(1.10.0): disk limitation in interrupt mode

---

content/docs/1.9.2/best-practices.md

Issue longhorn/longhorn#11699
Update best practice K8s version for v1.9.2

doc(1.9.2): update best practice K8s version

---

content/docs/1.10.0/important-notes/_index.md
content/docs/1.10.1/important-notes/_index.md

doc(v1.10.0): more detail for CRD migration trouble shoot command

---

content/docs/1.10.0/important-notes/_index.md
content/docs/1.10.1/important-notes/_index.md

docs(1.10): update important note

---

content/docs/1.10.0/important-notes/_index.md
content/docs/1.10.1/important-notes/_index.md

chore(1.10): update important note
