assets/sass/main.scss
themes/longhorn-theme/assets/sass/main.scss
themes/longhorn-theme/layouts/partials/footer.html

This PR changes the copyright text in the footer to bring Longhorn more in line with other CNCF projects. I see that this was updated in #13 but I think the approach in this PR is a bit more automated.

New footer copyright text

---

layouts/partials/footer.html

Due to a Hugo upgrade, the year string in the footer is displaying incorrectly due to a string interpolation issue. This PR fixes that by using `%d` for the year integers instead of the errant `%s`.

Fix footer year display issue

---

content/docs/architecture/driver.md
content/docs/install/longhorn-airgap.md
content/docs/install/viewing-ui.md

This PR is intended to move the airgap document and readme.md changes from the v0.8.1 branch of longhorn/longhorn to the v0.8.1 branch of longhorn/website.

Add Longhorn v0.8.1 docs to longhorn.io

---

layouts/index.redirects

This URL behaves as expected:
https://deploy-preview-57--longhornio.netlify.app/docs
cc @yasker

Add missing forced redirect

---

content/docs/0.8.1/snapshots-and-backups/backup-and-restore/set-backup-target.md

Our default minio-test backupstore is setup to use such a certificate
and can be used as an example.
Signed-off-by: Joshua Moody <joshua.moody@rancher.com>

Add explanation on how to use a self signed ssl certificate for s3

---

layouts/index.redirects

This PR removes subdomain redirects that cannot be applied by the Netlify platform.

Remove non-functioning redirects

---

content/docs/0.8.1/volumes-and-nodes/maintenance.md

This PR adds content from the wiki https://github.com/yasker/longhorn/wiki/Maintenance-Guide into the Longhorn docs. It is intended to address this issue https://github.com/longhorn/longhorn/issues/1121
I think this PR should not be merged into staging until https://github.com/longhorn/website/pull/107/ is merged, so that we can start using staging for 1.0 specific changes.

Move node maintenance doc to Longhorn docs

---

content/docs/0.8.1/deploy/upgrade/_index.md
content/docs/0.8.1/deploy/upgrade/longhorn-manager.md

This PR is intended to address this issue https://github.com/longhorn/longhorn/issues/1397 and incorporates the content from this wiki https://github.com/yasker/longhorn/wiki/Upgrade-from-v0.8.1-to-v1.0.0-%5BDRAFT%5D into the docs.
For the step about "Shut down your workloads following the instructions," I replaced the link from this https://longhorn.io/docs/0.8.1/deploy/upgrade/upgrade-engine/#offline-upgrades to this https://longhorn.io/docs/0.8.1/volumes-and-nodes/detaching-volumes/ because the latter page seemed more specific to shutting down workloads.

Document upgrading from v0.8.1 to v1.0.0

---

content/docs/0.8.1/advanced-resources/os-distro-specific/csi-on-k3s.md
content/docs/0.8.1/deploy/accessing-the-ui/_index.md
content/docs/0.8.1/deploy/install/_index.md
content/docs/0.8.1/deploy/install/install-with-kubectl.md
content/docs/0.8.1/deploy/upgrade/_index.md
content/docs/0.8.1/deploy/upgrade/longhorn-manager.md

Since we won't support Longhorn v0.7.0 or lower versions after GA.

Remove the instruction related to Longhorn v0.7.0

---

content/docs/1.0.0/snapshots-and-backups/backup-and-restore/set-backup-target.md

..it works on 0.8, at least. I thought it might fail, so perhaps this will save some effort for others.
I haven't built the docs, I'm just assuming the format will be fine.

Note a subpath may be used, with an example.

---

content/docs/1.0.0/architecture.md

In the 1.0.0 version, below sentence continuously displayed two times in the `architecture` page
```
Volume-level metadata is stored in `volume.cfg`.
```

remove a duplicated sentence.

---

content/docs/1.0.0/advanced-resources/deploy/airgap.md

Because we change from using a full image name to using a checksum for instance-manager labels, we remove the documentation about the limitation on instance-manager image name.
longhorn/longhorn#1323

docs/1.0.0/advanced-resources/deploy: remove the limitation warning about the length of the instance-manager image name

---

content/docs/1.0.0/advanced-resources/deploy/priority-class.md
content/docs/1.0.0/references/settings.md

This PR adds documentation for the `Priority Class` setting that was requested in longhorn/longhorn#1487, laying out what the setting does, how to use it during initial `Longhorn` installation, and the dangers of modifying the `Setting` (since it results in redeployment of all `Longhorn` workloads.

Add documentation for Priority Class setting

---

content/docs/1.0.0/volumes-and-nodes/delete-volumes.md

This PR adds documentation to the website regarding deletion of `Volumes` and the new deletion behavior introduced for longhorn/longhorn#520. This will inform the user about deleting `Volumes` through `Kubernetes` and `longhorn-ui`, as well as side effects of deleting `Volumes` through `longhorn-ui`, such as deletion of associated `Kubernetes` resources and warnings on attached `Volumes`.

Add documentation for Volume deletion

---

content/docs/1.0.0/advanced-resources/deploy/customizing-default-settings.md
content/docs/1.0.0/deploy/install/install-with-helm.md

This PR updates the docs on the website to reference the new `Helm` repository at https://charts.longhorn.io. The `Helm` installation instructions have been modified to reference that repository instead of having the user clone the `Longhorn` repository to access the chart. Additionally, the instructions for modifying the `Default Settings` in `Longhorn` have been updated to omit the `git clone` step and to indicate how to obtain and modify a copy of `values.yaml` for `Helm` if using the `--values` flag.

Update docs with Helm repo

---

content/docs/1.0.0/advanced-resources/deploy/airgap.md

Added instruction to `air-gap installation` section in `Longhorn` document.
longhorn/longhorn#1419

advance-resources/deploy: document about providing list of images and scripts to pull and push all Longhorn component images to user provided registry

---

content/docs/1.0.1/deploy/install/_index.md

This PR adds a note to the list of requirements for deploying Longhorn indicating that Longhorn needs root access in order for Longhorn to be properly deployed and operated as requested in longhorn/longhorn#1625. Documentation about Pod Security Policy requirements has been omitted due to concerns about Pod Security Policy being deprecated in future versions of Kubernetes.

Add note about root requirement to deploy docs

---

content/docs/1.1.0/advanced-resources/deploy/customizing-default-settings.md
content/docs/1.1.0/high-availability/node-failure.md
content/docs/1.1.0/references/settings.md

Add document about `Pod Deletion Policy When Node Downs`. Longhorn provides 4 different Pod deletion policies when node downs: `do-nothing`, `delete-statefulset-pod`, `delete-deployment-pod`, `delete-both-statefulset-and-deployment-pod`. User can change the setting in setting tab in Longhorn UI or in `Customizing Default Settings`
Longhorn/longhorn#1105

high-availability: add document for how to handle node failure

---

content/docs/1.0.1/advanced-resources/deploy/airgap.md
content/docs/1.0.2/advanced-resources/deploy/airgap.md

"the script load images" --> "the script loads images"

Fix typo in airgapped installation

---

content/docs/1.1.0/concepts.md
content/docs/1.1.0/snapshots-and-backups/csi-snapshot-support/_index.md
content/docs/1.1.0/snapshots-and-backups/csi-snapshot-support/create-a-backup-via-csi.md
content/docs/1.1.0/snapshots-and-backups/csi-snapshot-support/enable-csi-snapshot-support.md
content/docs/1.1.0/snapshots-and-backups/csi-snapshot-support/restore-a-backup-via-csi.md

Issue: longhorn/longhorn#304
LEP: https://github.com/longhorn/longhorn/blob/master/enhancements/20200904-csi-snapshot-support.md
@yasker
The 1.1 release note need to mention the required update of the csi-provisioner and the addition of the csi-snapshotter image for airgap environments.
Also mentioned in the documentation under enable csi support

Add documentation for CSI snapshot feature

---

content/docs/1.1.0/volumes-and-nodes/maintenance.md

content/docs/v1.1.0/volumes-and-nodes: remove the --force flags requirement when users drain node

---

content/docs/1.1.0/deploy/uninstall/_index.md

`--purge` flag is no longer exist in Helm 3. 
By default, Helm 3 does purge. If user don't want to purge, they can set `--keep-history`
https://github.com/helm/helm/pull/5283

content/docs/v1.1.0: Fix uninstall instruction for Helm installation

---

content/docs/0.8.0/getting-started/quick-start-with-helm.md
content/docs/0.8.0/install/install-with-rancher.md
content/docs/0.8.0/install/requirements.md
content/docs/0.8.1/deploy/install/_index.md
content/docs/1.0.0/deploy/install/_index.md
content/docs/1.0.1/deploy/install/_index.md
content/docs/1.0.2/deploy/install/_index.md

Longhorn does not specifically require Docker. I went by these requirements and later found out that any Kubernetes container runtime works through [a discussion on Slack](https://rancher-users.slack.com/archives/CC2UQM49Y/p1604669734311000).

Mention that any Kubernetes-compatible container runtime is sufficient

---

content/docs/1.0.2/deploy/install/_index.md

Signed-off-by: cloudoutloud <seanrigby26@gmail.com>
Just mentioned jq may need to be installed. This is not installed by default on most OS.

Update doc to include jq mention

---

content/docs/1.1.0/monitoring/integrating-with-rancher-monitoring.md

Rancher 2.5 uses a separate monitoring app for monitoring feature.
This PR update the link so that it makes sense for all Rancher monitoring system  v2.4- and v2.5+.

Fix prometheus feature document so that it makes sense for bot Rancher 2.4- and 2.5+

---

layouts/partials/docs/pagination.html

Navigate between section pages instead of all regular pages.
Signed-off-by: Kiefer Chang <kiefer.chang@suse.com>
The PR fixes the problem that the previous and next buttons link to the wrong pages, e.g.

Fix pagination in Docs

---

content/docs/1.1.0/snapshots-and-backups/backup-and-restore/set-backup-target.md

The secret is a base 64 encoded string.
If the user copy-pastes his/her AWS credential directly, an AWS credential error occurs.
Enhance the document to help the user to cease the problem.

Add example to create AWS S3 credential via kubectl command

---

content/docs/1.1.1/references/settings.md

update settings according to reviews rev 1 to resolve ticket '[FEATURE] Add new setting descriptions in the doc' (#2153)
1. Remove "System Pods Image Pull Policy"
2. Change "Auto Cleanup System Generated Snapshot" to "Automatically Cleanup System Generated Snapshot"
Improvement.
None
Refs: https://github.com/longhorn/longhorn/issues/2153
None
Signed-off-by: Clark Hsu <clark.hsu@suse.com>

update settings according to reviews rev 1 (#2153)

---

content/kb/troubleshooting-volume-take-long-time-to-mount.md

Add KB for the issue `volumes with lot of files take a long time to finish mounting`

---

content/docs/1.1.1/deploy/accessing-the-ui/longhorn-ingress.md

update longhorn ingress manifest from v1beta1 to v1 to resolve deprecated warning message during apply/delete.
Signed-off-by: Clark Hsu <clark.hsu@suse.com>

update longhorn ingress manifest from v1beta1 to v1

---

content/docs/1.1.1/deploy/install/_index.md
content/docs/1.1.1/deploy/uninstall/_index.md

We should specify the namespace when using kubectl command.
https://github.com/longhorn/longhorn/issues/2292

Enhance uninstall longhorn

---

content/docs/1.1.1/deploy/uninstall/_index.md

We should specify the namespace `default` when using kubectl command.
Issues
https://github.com/longhorn/longhorn/issues/2292

Keep uninstall job at default namespace

---

content/kb/troubleshooting-websocket_handshake_error_with_unexpected_response_code_200.md

add knowledge base to describe changing route to HashHistory mode (#2265)
add knowledge base to describe changing route to HashHistory mode to resolve ticket 'Longhorn-UI: Error during WebSocket handshake: Unexpected response code: 200' (#2265)
Knowledge Base
Refs: # https://github.com/longhorn/longhorn/issues/2265
None
Signed-off-by: Clark Hsu <clark.hsu@suse.com>

add knowledge base to describe changing route to HashHistory mode

---

content/docs/0.8.1/deploy/uninstall/_index.md
content/docs/1.0.0/deploy/uninstall/_index.md
content/docs/1.0.1/deploy/uninstall/_index.md
content/docs/1.0.2/deploy/uninstall/_index.md
content/docs/1.1.0/deploy/uninstall/_index.md

We should specify the namespace `default` when using kubectl command.

Add namespace flag for uninstall job

---

layouts/partials/javascript.html

This reverts commit 4ed4ffc51d8199e790e5d0ae0818c9d3e048340b.
This PR _must_ be merged after algolia/docsearch-configs#4090 merged.

Revert "Add version facet filter"

---

layouts/partials/javascript.html

This reverts commit 3ef834535e360e706172300bb3e7f3742b3a0169.
If the user at https://longhorn.io/docs/x.y.z, the Javascript client pass the facet filter with version x.y.z
If the user at https://longhorn.io/ or https://longhorn.io/blog/ or https://longhorn.io/kb/, the JS client won't pass the facet version filter.
related https://github.com/algolia/docsearch-configs/pull/4096
fix #305 

Add version facet filter

---

content/docs/1.1.2/references/settings.md

Updated default replica count information. 
Source: https://cloud-native.slack.com/archives/CNVPEL9U3/p1622445869034600
My question:
```
Hey guys! Can anyone explain to me why the default replica count should be set to two instead of three when having three (storage) nodes? From the documentation (https://longhorn.io/docs/0.8.0/users-guide/settings/#default-replica-count):
Note: The recommended way of choosing the default replica count is: if you have more than three nodes for storage, use 3; otherwise use 2. Using a single replica on a single node cluster is also OK, but the HA functionality wouldn't be available. You can still take snapshots/backups of the volume.
I’d rather have it set to three, so I’d like to know the reasoning why Longhorn recommends setting it to two with three …
```

Updated default replica count recommendation

---

content/docs/1.1.0/snapshots-and-backups/csi-snapshot-support/enable-csi-snapshot-support.md
content/docs/1.1.1/snapshots-and-backups/csi-snapshot-support/enable-csi-snapshot-support.md

Set crd url to v1beta to resolve issue '[BUG] Longhorn document is pointing to the wrong version of CSI snapshot CRDs'
Longhorn: # https://github.com/longhorn/longhorn/issues/2653
Signed-off-by: Clark Hsu <clark.hsu@suse.com>

Set crd url to v1beta

---

content/docs/1.1.1/snapshots-and-backups/backup-and-restore/set-backup-target.md

The kube2iam/kiam Pods must be the same node as longhorn-manager as well
as replica instance manager Pods.
https://github.com/longhorn/longhorn/issues/2718

[cherry-pick-v1.1.2] Add a note for AWS IAM Role ARN

---

content/docs/1.1.1/snapshots-and-backups/backup-and-restore/set-backup-target.md

The kube2iam/kiam Pods must be the same node as longhorn-manager as well
as replica instance manager Pods.
https://github.com/longhorn/longhorn/issues/2718

[cherry-pick-v1.2.0] Add a note for AWS IAM Role ARN

---

content/docs/1.1.1/snapshots-and-backups/backup-and-restore/set-backup-target.md

The kube2iam/kiam Pods must be the same node as longhorn-manager as well
as replica instance manager Pods.
https://github.com/longhorn/longhorn/issues/2718

Add a note for AWS IAM Role ARN

---

content/docs/1.1.1/deploy/upgrade/longhorn-manager.md

Fix incorrect upgrade path for 1.1.1 in the manager upgrade doc

---

content/docs/1.2.0/snapshots-and-backups/csi-snapshot-support/enable-csi-snapshot-support.md

* Longhorn v1.2.0 only run on Kubernetes v1.18+ so don't need to mention Kubernetes v1.17
* CSI versions should be updated already when the users upgrade to Longhorn v1.2.0

Remove some outdated information in the CSI snapshot document

---

layouts/partials/meta.html

To make the search engine do not create duplicate indexing across multiple doc versions, use the `latest` URL in the canonical tag. For example:
- was
```html
<link rel="canonical" href="https://longhorn.io/docs/1.2.0/deploy/install/" />
```
- is
```html
<link rel="canonical" href="https://longhorn.io/docs/latest/deploy/install/" />
```
So, the search engine will only index that page instead of all duplicated version pages.
https://developers.google.com/search/docs/advanced/crawling/consolidate-duplicate-urls#rel-canonical-link-method
https://github.com/longhorn/longhorn/issues/2758

Use the `latest` url in canonical tag

---

content/docs/1.2.0/references/examples.md
content/docs/1.2.0/volumes-and-nodes/create-volumes.md

Start from v1.2.0, the recurring job format in StorageClass changes to use `recurringJobSelector`.

Fix recurring job format

---

content/docs/1.2.1/snapshots-and-backups/scheduling-backups-and-snapshots.md

Hi, I know, huge change 😄 But docs for 1.2.1 are unreadable here https://longhorn.io/docs/1.2.1/snapshots-and-backups/scheduling-backups-and-snapshots/#set-up-recurring-jobs-using-a-longhorn-recurringjob

Fix Markdown for RecurringJob definition

---

content/docs/1.1.0/monitoring/integrating-with-rancher-monitoring.md
content/docs/1.1.1/monitoring/integrating-with-rancher-monitoring.md
content/docs/1.1.2/monitoring/integrating-with-rancher-monitoring.md
content/docs/1.2.0/monitoring/integrating-with-rancher-monitoring.md
content/docs/1.2.1/monitoring/integrating-with-rancher-monitoring.md
content/docs/1.2.2/monitoring/integrating-with-rancher-monitoring.md

Rancher doc separates to use different URL links, such as v2.0-v2.4, v2.5, v2.6.
To make Longhorn documentation compatible across all Rancher docs, I think we should remove the hyperlink directly.
Then users have to find the related doc by themselves.
https://github.com/longhorn/longhorn/issues/3215

Remove broken link of Rancher doc

---

content/docs/1.2.2/volumes-and-nodes/maintenance.md

This makes sure that Kubernetes doesn't evict CSI attacher and provisioner so Longhorn can properly detach the volumes
longhorn/longhorn#3304

Add --pod-selector to the drain instruction

---

content/docs/1.3.0/snapshots-and-backups/csi-snapshot-support/csi-volume-snapshot-associated-with-longhorn-backup.md
content/docs/1.3.0/snapshots-and-backups/csi-snapshot-support/csi-volume-snapshot-associated-with-longhorn-snapshot.md

The values will be either `snap`, `bak`,or `""` after this change.
longhorn/longhorn#2534

[Doc] Using user-friendly name for the csiSnapshotType

---

content/docs/1.1.0/snapshots-and-backups/csi-snapshot-support/enable-csi-snapshot-support.md
content/docs/1.1.1/snapshots-and-backups/csi-snapshot-support/enable-csi-snapshot-support.md
content/docs/1.1.2/snapshots-and-backups/csi-snapshot-support/enable-csi-snapshot-support.md
content/docs/1.1.3/snapshots-and-backups/csi-snapshot-support/enable-csi-snapshot-support.md
content/docs/1.2.0/snapshots-and-backups/csi-snapshot-support/enable-csi-snapshot-support.md
content/docs/1.2.1/snapshots-and-backups/csi-snapshot-support/enable-csi-snapshot-support.md
content/docs/1.2.2/snapshots-and-backups/csi-snapshot-support/enable-csi-snapshot-support.md
content/docs/1.2.3/snapshots-and-backups/csi-snapshot-support/enable-csi-snapshot-support.md

Update the wording to inform the users that must install the release-4.0 snapshot v1beta1 CRDs.
https://github.com/longhorn/longhorn/issues/2973

Specific the snapshot CRDs version to install

---

content/docs/1.2.4/snapshots-and-backups/csi-snapshot-support/enable-csi-snapshot-support.md

Update the wording to inform the users that must install the release-4.0 snapshot v1beta1 CRDs.
https://github.com/longhorn/longhorn/issues/3691

Add note for snapshot CRD and snapshot controller version

---

content/docs/1.3.0/advanced-resources/backing-image.md
content/docs/1.3.0/advanced-resources/deploy/airgap.md
content/docs/1.3.0/references/settings.md

Update documents with new API version `v1beta2` starting from v1.3.0.
Signed-off-by: James Lu <jamesluhz@gmail.com>

Bump the version of longhorn API to v1beta2.

---

content/docs/1.1.0/concepts.md
content/docs/1.1.1/concepts.md
content/docs/1.1.2/concepts.md
content/docs/1.1.3/concepts.md
content/docs/1.2.0/concepts.md
content/docs/1.2.1/concepts.md
content/docs/1.2.2/concepts.md
content/docs/1.2.3/concepts.md
content/docs/1.2.4/concepts.md
content/docs/1.2.5/concepts.md
content/docs/1.3.0/concepts.md
content/docs/1.3.1/concepts.md
content/docs/1.4.0/concepts.md
content/docs/archives/0.8.0/concepts.md
content/docs/archives/0.8.1/concepts.md
content/docs/archives/1.0.0/concepts.md
content/docs/archives/1.0.1/concepts.md
content/docs/archives/1.0.2/concepts.md

Signed-off-by: Tim Serong <tserong@suse.com>
(I found this while browsing the 1.3.0 docs online, then discovered it was in all versions so just did a search and replace everywhere - I hope that's the right approach here)

Fix transposed 'the' and 'unless'

---

content/docs/1.3.0/monitoring/metrics.md
content/docs/1.3.1/monitoring/metrics.md
content/docs/1.4.0/monitoring/metrics.md

Add Prometheus metrics for backup
From JenTing Hsiao <jenting.hsiao@suse.com>
Add the Prometheus metrics for backup into 1.3.1 and 1.4.0 documents.
longhorn/longhorn#4521
Signed-off-by: James Lu <james.lu@suse.com>

Add Prometheus metrics for backup

---

content/docs/1.3.2/deploy/install/_index.md
content/docs/1.3.3/deploy/install/_index.md

[Longhorn 4450](https://github.com/longhorn/longhorn/issues/4450)
Since the [PR#592](https://github.com/longhorn/website/pull/592) branch doesn't have 1.3.2 and 1.3.3, this PR will align the docs for > 1.2.5.  (ref. https://github.com/longhorn/longhorn/issues/4450#issuecomment-1294479499)

docs(deploy): Update v1.3.2/3 the Environment Check Script output result

---

content/docs/1.4.0/best-practices.md

Signed-off-by: Chris Chien <chris.chien@suse.com>
From https://github.com/longhorn/longhorn/issues/4206#issuecomment-1305688968, remove experimental from ARM64 in v1.4.0

Remove experimental from ARM64 in v1.4.0

---

content/docs/1.2.5/references/settings.md
content/docs/1.2.6/references/settings.md
content/docs/1.2.7/references/settings.md
content/docs/1.3.2/references/settings.md
content/docs/1.3.3/references/settings.md
content/docs/1.4.0/references/settings.md

Add failed backup TTL to setting reference including default value and its properties.
longhorn/longhorn#4913
longhorn/longhorn#3898

docs: add `failed-backup-tll` to setting reference

---

content/docs/1.4.0/advanced-resources/security/volume-encryption.md

Extend the volume-encryption.md to explain customization of volume encryption.
longhorn/longhorn#3353
https://github.com/longhorn/longhorn/issues/3285
Signed-off-by: James Lu <james.lu@suse.com>

doc(encrypt): Allow customization of the cipher

---

content/docs/1.4.0/monitoring/prometheus-and-grafana-setup.md

@derekbit created the LH Grafana dashboard for **v1.4.0**
We need to update LH document in [setting up Grafana](https://longhorn.io/docs/1.4.0/monitoring/prometheus-and-grafana-setup/#setup-grafana)
issue longhorn/longhorn#5158
Signed-off-by: Roger Yao <roger.yao@suse.com>

Update `LH Grafana dashboard` link in grafana-setup

---

content/kb/troubleshooting-volumes-stuck-in-attach-detach-loop-when-using-longhorn-on-okd.md

[#4988](https://github.com/longhorn/longhorn/issues/4988)
Knowledge base page for volumes stuck in attach detach loop when using longhorn on okd.
Signed-off-by: Jack Lin <jack.lin@suse.com>

docs: add KB for volumes stuck in attach detach loop when using longhorn on okd

---

content/docs/1.5.0/deploy/important-notes/index.md
content/docs/1.5.0/snapshots-and-backups/csi-snapshot-support/enable-csi-snapshot-support.md

https://github.com/longhorn/longhorn/issues/5672
We can't move to these versions of external-provisioner and external-snapshotter in Longhorn < v1.5, as they no longer support the v1beta1 VolumeSnapshot API. We deprecated its use in Longhorn v1.4 (https://github.com/longhorn/longhorn/blob/master/CHANGELOG/CHANGELOG-1.4.0.md#deprecation--incompatibilities).
EDIT: This comment was previously (incorrectly) missing the "<" sign.

Bump CSI sidecars for K8s v1.20+ and Longhorn v1.5

---

content/docs/1.5.0/deploy/upgrade/_index.md
content/docs/1.5.0/deploy/upgrade/longhorn-manager.md

Add the upgrade path enforcement section for the `upgrade` part.
And what will happen when upgrade from v1.3.x or old versions to v1.5.0
Ref: longhorn/longhorn#5131

doc: upgrade path enforcement

---

content/docs/1.5.0/snapshots-and-backups/backup-and-restore/set-backup-target.md

Set a remote backup target.
Ref: longhorn/longhorn#1309

doc: Azure Blob Storage backupstore support

---

content/docs/1.5.0/deploy/important-notes/index.md

longhorn/longhorn#5595
It looks like we will not need to change the minimum Kubernetes version for Longhorn v1.5. Slightly tweak the wording on the website (since the supported version has not changed).

Slightly tweak Kubernetes minimum version wording

---

content/docs/1.5.0/snapshots-and-backups/setup-disaster-recovery-volumes.md

Since v1.5.0, Longhorn supports activating a degrade DR volume when the setting `allow-volume-creation-with-degraded-availability` is enabled.
Ref: longhorn/longhorn#1512

doc(dr-volume): activate a degrade DR volume

---

content/docs/1.4.0/snapshots-and-backups/csi-snapshot-support/enable-csi-snapshot-support.md
content/docs/1.4.1/snapshots-and-backups/csi-snapshot-support/enable-csi-snapshot-support.md
content/docs/1.4.2/snapshots-and-backups/csi-snapshot-support/enable-csi-snapshot-support.md
content/docs/1.4.3/snapshots-and-backups/csi-snapshot-support/enable-csi-snapshot-support.md
content/docs/1.5.0/snapshots-and-backups/csi-snapshot-support/enable-csi-snapshot-support.md

In the `Enable CSI Snapshot Support on the Cluster` page, we need to install the CSI Snapshot CRD and the CSI Snapshot Controller. The version of `CSI external-snapshotte` after 5.0 uses kustomize to manage resource files, so it is necessary to modify the parameters of kubectl to operate normally
- [v6.2.1](https://github.com/kubernetes-csi/external-snapshotter/tree/v6.2.1/client/config/crd): Used by Longhorn v1.5.0
- [v5.0.1](https://github.com/kubernetes-csi/external-snapshotter/tree/v5.0.1/client/config/crd): Used by Longhorn v1.4.x
https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#apply

doc: Update kubectl options for `CSI external-snapshotter` version > 5.0

---

content/docs/1.5.0/spdk/prerequisites.md

v5.13+ can provide better stability

spdk: update linux kernel version requirement

---

content/docs/1.5.2/references/settings.md

Backported to v1.5.2.
ref: https://github.com/longhorn/longhorn/issues/6438, https://github.com/longhorn/longhorn/issues/6410

doc(telemetric): collect Snapshot Data Integrity CronJob setting as boolean

---

content/docs/1.5.2/deploy/important-notes/index.md
content/docs/1.6.0/deploy/important-notes/index.md

longhorn/longhorn#5845
Tagging this to https://github.com/longhorn/longhorn/issues/6550 (the v1.5.x backport of longhorn/longhorn#5845) as well, since longhorn/longhorn#5845 is already closed and https://github.com/longhorn/longhorn/issues/6550 is not.

Offline upgrade is required to prevent unexpected replica expansion

---

content/docs/1.5.0/deploy/upgrade/_index.md
content/docs/1.5.1/deploy/upgrade/_index.md
content/docs/1.5.2/deploy/upgrade/_index.md
content/docs/1.6.0/deploy/upgrade/_index.md

Modify the upgrade path supported matrix to use `current-version` for 1.5.x and 1.6.x upgrade path documents.

doc(upgrade): modify upgrade path example

---

content/docs/1.6.0/advanced-resources/os-distro-specific/okd-support.md
content/docs/1.6.0/deploy/install/_index.md

Add/modify documents to support deploying Longhorn on OPCP/OKD
Ref: longhorn/longhorn#1831

doc(os/distro): OCP/OKD support

---

content/docs/1.4.0/references/storage-class-parameters.md
content/docs/1.4.1/references/storage-class-parameters.md
content/docs/1.4.2/references/storage-class-parameters.md
content/docs/1.4.3/references/storage-class-parameters.md
content/docs/1.4.4/references/storage-class-parameters.md
content/docs/1.5.0/references/storage-class-parameters.md
content/docs/1.5.1/references/storage-class-parameters.md
content/docs/1.5.2/references/storage-class-parameters.md
content/docs/1.6.0/advanced-resources/deploy/customizing-default-settings.md
content/docs/1.6.0/advanced-resources/orphaned-data-cleanup.md
content/docs/1.6.0/references/settings.md
content/docs/1.6.0/references/storage-class-parameters.md
content/docs/1.6.0/volumes-and-nodes/scheduling.md

doc: add a page explaining storage class parameters

---

content/docs/1.6.0/references/helm-values.md

ref: https://github.com/longhorn/longhorn/issues/5455

doc(helm): add helm values to website

---

content/kb/troubleshooting-rwx-volume-fails-to-attached-caused-by-protocol-not-supported.md

Longhorn/longhorn#6887
Longhorn/longhorn#6857

KB: add "Troubleshooting: RWX Volume Fails to Be Attached Caused by `Protocol not supported`"

---

content/kb/selinux-and-longhorn.md

longhorn/longhorn#6074
Before we closed https://github.com/longhorn/longhorn/issues/6074, we found https://github.com/longhorn/longhorn/issues/5348.
Each time an SELinux issue is discovered, it can take a developer time to ramp up and understand what is going on. I imagine this is even more difficult for our users, who may be neither SELinux nor Longhorn experts.
I wrote this KB with the intention of making it easier for users and developers to understand how Longhorn SHOULD be interacting with SELinux and provide some basic tools to troubleshoot it if things aren't looking right.

Add SELinux and Longhorn KB

---

content/docs/1.6.0/advanced-resources/security/volume-encryption.md

Update volume encryption doc

---

content/docs/1.6.0/references/settings.md
content/docs/1.6.0/volumes-and-nodes/volume-size.md

Add a new global setting that allows users to keep the retain number of snapshots when the recurring job does a backup.
Ref: longhorn/longhorn#2997

doc(setting): keep snapshots for the backup

---

content/docs/1.4.0/best-practices.md
content/docs/1.4.0/snapshots-and-backups/backup-and-restore/set-backup-target.md
content/docs/1.4.1/best-practices.md
content/docs/1.4.1/snapshots-and-backups/backup-and-restore/set-backup-target.md
content/docs/1.4.2/best-practices.md
content/docs/1.4.2/snapshots-and-backups/backup-and-restore/set-backup-target.md
content/docs/1.4.3/best-practices.md
content/docs/1.4.3/snapshots-and-backups/backup-and-restore/set-backup-target.md
content/docs/1.4.4/best-practices.md
content/docs/1.4.4/snapshots-and-backups/backup-and-restore/set-backup-target.md
content/docs/1.4.5/best-practices.md
content/docs/1.4.5/snapshots-and-backups/backup-and-restore/set-backup-target.md
content/docs/1.5.0/best-practices.md
content/docs/1.5.0/snapshots-and-backups/backup-and-restore/set-backup-target.md
content/docs/1.5.1/best-practices.md
content/docs/1.5.1/snapshots-and-backups/backup-and-restore/set-backup-target.md
content/docs/1.5.2/best-practices.md
content/docs/1.5.2/snapshots-and-backups/backup-and-restore/set-backup-target.md
content/docs/1.5.3/best-practices.md
content/docs/1.5.3/snapshots-and-backups/backup-and-restore/set-backup-target.md
content/docs/1.5.4/best-practices.md
content/docs/1.5.4/snapshots-and-backups/backup-and-restore/set-backup-target.md
content/docs/1.6.0/best-practices.md
content/docs/1.6.0/snapshots-and-backups/backup-and-restore/set-backup-target.md

Proposed addition to address https://github.com/longhorn/longhorn/issues/6773.
When this is acceptable, I will duplicate it to all current releases.

Add a note about best practice for choice of a backup store.

---

content/docs/1.5.0/references/settings.md
content/docs/1.5.0/snapshots-and-backups/backup-and-restore/set-backup-target.md
content/docs/1.5.1/references/settings.md
content/docs/1.5.1/snapshots-and-backups/backup-and-restore/set-backup-target.md
content/docs/1.5.2/references/settings.md
content/docs/1.5.2/snapshots-and-backups/backup-and-restore/set-backup-target.md
content/docs/1.5.3/references/settings.md
content/docs/1.5.3/snapshots-and-backups/backup-and-restore/set-backup-target.md
content/docs/1.5.4/references/settings.md
content/docs/1.5.4/snapshots-and-backups/backup-and-restore/set-backup-target.md
content/docs/1.6.0/references/settings.md
content/docs/1.6.0/snapshots-and-backups/backup-and-restore/set-backup-target.md

This PR has the documentation changes for longhorn/longhorn#6608, enable mount options for NFS and CIFS backup targets.
First version is for review on contents.  Changes will need to be backported where the functionality has.
I will squash all the commits when the content is approved for all releases.

6608 - Docs changes for backup target mount options.

---

content/docs/1.6.0/deploy/important-notes/index.md
content/docs/1.6.0/references/settings.md
content/docs/1.6.0/volumes-and-nodes/maintenance.md

longhorn/longhorn#2238
- Mention new `Node Drain Policy` options in `v1.6.0` notes.
- Mention field deprectation in `v1.6.0` notes.
- Clarify what happens during a drain.
- Add a section comparing and contrasting different node drain policies (including the new ones).

Document new node drain policies and clarify drain behavior

---

content/docs/1.6.0/monitoring/metrics.md

https://github.com/longhorn/longhorn/issues/5869

doc(1.6.0): metrics collect snapshot actual size

---

content/docs/1.4.0/references/storage-class-parameters.md
content/docs/1.4.1/references/storage-class-parameters.md
content/docs/1.4.2/references/storage-class-parameters.md
content/docs/1.4.3/references/storage-class-parameters.md
content/docs/1.4.4/references/storage-class-parameters.md
content/docs/1.5.0/references/storage-class-parameters.md
content/docs/1.5.0/spdk/quick-start.md
content/docs/1.5.1/references/storage-class-parameters.md
content/docs/1.5.1/spdk/quick-start.md
content/docs/1.5.2/references/storage-class-parameters.md
content/docs/1.5.2/spdk/quick-start.md
content/docs/1.5.3/spdk/quick-start.md
content/docs/1.5.4/spdk/quick-start.md
content/docs/1.6.0/references/storage-class-parameters.md
content/docs/1.6.0/spdk/quick-start.md
content/kb/space-consumption-guideline.md

minor change to fix spdk quick-start to use correct backendStoreDriver parameter value.

fix quick-start backendStorageDriver

---

content/docs/1.6.0/deploy/important-notes/index.md

https://github.com/longhorn/longhorn/issues/5842

doc: engine version enforcement

---

content/docs/1.6.0/deploy/important-notes/index.md
content/docs/1.6.0/spdk/features.md
content/docs/1.6.0/spdk/prerequisites.md

v2 volume: update documents

---

content/docs/1.6.0/advanced-resources/os-distro-specific/talos-linux-support.md
content/docs/1.6.0/best-practices.md
content/docs/1.6.0/deploy/install/_index.md

https://github.com/longhorn/longhorn/issues/3161

doc(1.6.0): Talos Linux support

---

content/docs/1.4.0/references/storage-class-parameters.md
content/docs/1.4.1/references/storage-class-parameters.md
content/docs/1.4.2/references/storage-class-parameters.md
content/docs/1.4.3/references/storage-class-parameters.md
content/docs/1.4.4/references/storage-class-parameters.md
content/docs/1.4.5/references/storage-class-parameters.md
content/docs/1.5.0/references/storage-class-parameters.md
content/docs/1.5.1/references/storage-class-parameters.md
content/docs/1.5.2/references/storage-class-parameters.md
content/docs/1.5.3/references/storage-class-parameters.md
content/docs/1.5.4/references/storage-class-parameters.md
content/docs/1.6.0/references/storage-class-parameters.md

These were accidentally lost by IDE a few commits ago.

Restore markdown newline delimiters.

---

content/docs/1.6.0/monitoring/prometheus-and-grafana-setup.md
content/docs/1.6.0/references/helm-values.md

Add descriptions for the values `helmPreUpgradeCheckerJob` and `serviceMonitor`.
Ref: longhorn/longhorn#7485

doc: add descriptions for helm values.

---

content/docs/1.6.0/references/settings.md

Issue https://github.com/longhorn/longhorn/issues/7655
v1 and v2 date engines are separate, so the warning `When applying the setting, Longhorn will restart all instance-manager pods.` is not required.

Update the description of v2-data-engine setting

---

content/docs/1.4.0/deploy/uninstall/_index.md
content/docs/1.4.1/deploy/uninstall/_index.md
content/docs/1.4.2/deploy/uninstall/_index.md
content/docs/1.4.3/deploy/uninstall/_index.md
content/docs/1.4.4/deploy/uninstall/_index.md
content/docs/1.4.5/deploy/uninstall/_index.md
content/docs/1.5.0/deploy/uninstall/_index.md
content/docs/1.5.1/deploy/uninstall/_index.md
content/docs/1.5.2/deploy/uninstall/_index.md
content/docs/1.5.3/deploy/uninstall/_index.md
content/docs/1.5.4/deploy/uninstall/_index.md
content/docs/1.6.0/deploy/uninstall/_index.md

https://github.com/longhorn/longhorn/issues/7603
The troubleshooting note about attach/detach is not on topic for uninstall, and duplicates a section in the advanced-resource troubleshooting page.

doc: remove duplicated troubleshooting section from uninstall topic

---

content/docs/1.6.0/best-practices.md

Per [David's instructions](https://github.com/harvester/harvesterhci.io/pull/51#pullrequestreview-1812329155), I am adding the content that I wrote for [this Harvester KB article](https://harvesterhci.io/kb/best_practices_for_optimizing_longhorn_disk_performance) to the Longhorn documentation.
A few differences:
- Links all point to the Longhorn v1.6.0 doc
- Filesystem trim is mentioned (This was removed from the Harvester KB article because of a known issue.)

Add disk performance optimization measures to best-practices.md

---

content/docs/1.6.0/references/helm-values.md

Issue longhorn/longhorn#6527
This field is used to override the Longhorn namespace when Longhorn is a sub-chart.

doc: add the field namespaceOverride back.

---

content/docs/1.5.3/volumes-and-nodes/trim-filesystem.md
content/docs/1.5.4/volumes-and-nodes/trim-filesystem.md
content/docs/1.6.0/nodes-and-volumes/volumes/trim-filesystem.md

Issue https://github.com/longhorn/longhorn/issues/7712
Adds a sentence mentioning it's possible to add a RecurringJob that executes a filesystem trim.

Mention recurring jobs for filesystem trim

---

content/docs/1.5.3/v2-data-engine/_index.md
content/docs/1.5.3/v2-data-engine/automatic-offline-replica-rebuilding.md
content/docs/1.5.3/v2-data-engine/features.md
content/docs/1.5.3/v2-data-engine/performance-benchmark.md
content/docs/1.5.3/v2-data-engine/prerequisites.md
content/docs/1.5.3/v2-data-engine/quick-start.md
content/docs/1.5.3/v2-data-engine/troubleshooting.md
content/docs/1.6.0/v2-data-engine/_index.md
content/docs/1.6.0/v2-data-engine/features/_index.md
content/docs/1.6.0/v2-data-engine/features/automatic-offline-replica-rebuilding.md
content/docs/1.6.0/v2-data-engine/features/selective-v2-data-engine-activation.md
content/docs/1.6.0/v2-data-engine/performance.md
content/docs/1.6.0/v2-data-engine/prerequisites.md
content/docs/1.6.0/v2-data-engine/quick-start.md
content/docs/1.6.0/v2-data-engine/troubleshooting.md

Google search results for topics related to the V2 Data Engine point to `longhorn.io > docs > latest > spdk`. However, the links are broken because the folder was changed to 'v2-data-engine'.
We can use [aliases](https://gohugo.io/content-management/urls/#aliases) to redirect to the new URLs. I added the metadata to the affected v1.5.3 and v1.6.0 files.

Add aliases metadata to files in v2-data-engine

---

content/docs/1.5.0/deploy/upgrade/_index.md
content/docs/1.6.0/deploy/important-notes/index.md
content/docs/1.6.0/deploy/upgrade/_index.md

I reorganized and reworded the existing content, and added details from [this Slack thread](https://suse.slack.com/archives/C02HBK5AVC5/p1703730572042269).
My initial commit only covers v1.5.0 and v1.6.0, but I can expand the scope (if necessary) after I receive feedback.

Improve 'Upgrade Path Enforcement' content

---

content/docs/1.6.0/deploy/install/install-with-argocd.md

The value seems to be outdated. The pre-upgrade checker job is actually `preUpgradeChecker.jobEnabled: false` when using the Helm chart for `v1.6.0`.

Correct setting name for disabling pre-upgrade checker

---

content/docs/1.4.0/volumes-and-nodes/trim-filesystem.md
content/docs/1.4.1/volumes-and-nodes/trim-filesystem.md
content/docs/1.4.2/volumes-and-nodes/trim-filesystem.md
content/docs/1.4.3/volumes-and-nodes/trim-filesystem.md
content/docs/1.4.4/volumes-and-nodes/trim-filesystem.md
content/docs/1.4.5/volumes-and-nodes/trim-filesystem.md
content/docs/1.5.0/volumes-and-nodes/trim-filesystem.md
content/docs/1.5.1/volumes-and-nodes/trim-filesystem.md
content/docs/1.5.2/volumes-and-nodes/trim-filesystem.md
content/docs/1.5.3/volumes-and-nodes/trim-filesystem.md
content/docs/1.5.4/volumes-and-nodes/trim-filesystem.md
content/docs/1.6.0/nodes-and-volumes/volumes/trim-filesystem.md
content/docs/1.6.1/nodes-and-volumes/volumes/trim-filesystem.md
content/docs/1.7.0/nodes-and-volumes/volumes/trim-filesystem.md

- Replaced `UnmapMarkSnapChainAsRemoved` -> `UnmapMarkSnapChainRemoved`
- Replaced `StoragaClasses` -> `StorageClasses`

Fix typo in `trim-filesystem.md`

---

content/kb/troubleshooting-rwx-volume-fails-to-attached-caused-by-protocol-not-supported.md

Issue #
Because Ubuntu or other distros backport the commit that introduces the regression to old kernels, we should add more information for helping users check their kernels.

kb: update "Troubleshooting: RWX Volume Fails to Be Attached Caused by `Protocol not supported`"

---

content/kb/kubernetes-resource-revision-frequency-expectations.md

N/A
A user recently raised concerns regarding high version numbers in etcd for Longhorn resources. I did decent amount of looking into it and thought it would be good to have a KB for future reference.

Add KB describing resource revision frequency expectations

---

content/docs/1.6.2/references/helm-values.md
content/docs/1.7.0/references/helm-values.md

Update doc for openshift/origin-oauth-proxy image, v2DataEngineLogFlags, and v2DataEngineLogLevel helm values

---

content/docs/1.6.2/references/helm-values.md
content/docs/1.7.0/references/helm-values.md

longhorn/longhorn#6313
Make the syntax of the `taintToleration` helm setting more clear, since it can confuse users. (Really, just copy the Helm doc as appropriate from https://github.com/longhorn/longhorn/pull/8525.

Clarify syntax of taintToleration Helm value

---

content/docs/1.5.6/advanced-resources/deploy/node-selector.md
content/docs/1.5.6/advanced-resources/deploy/taint-toleration.md
content/docs/1.6.3/advanced-resources/deploy/node-selector.md
content/docs/1.6.3/advanced-resources/deploy/taint-toleration.md
content/docs/1.7.0/advanced-resources/deploy/node-selector.md
content/docs/1.7.0/advanced-resources/deploy/taint-toleration.md

ref: https://github.com/longhorn/longhorn/issues/5089
- Add global tolerations and nodeselectors for user deployed components
- Use global setting by default
- Override each by their specific settings .

feat(doc): introduce global tolerations and nodeselectors for user deployed components

---

content/docs/1.6.0/best-practices.md
content/docs/1.6.1/best-practices.md
content/docs/1.6.2/best-practices.md
content/docs/1.6.3/best-practices.md
content/docs/1.7.0/best-practices.md

Issue [#8633](https://github.com/longhorn/longhorn/issues/8633)

Fix link issues in best-practices.md

---

content/docs/1.5.6/references/settings.md
content/docs/1.6.3/references/settings.md
content/docs/1.7.0/references/settings.md

Issues:
- longhorn/longhorn#8623
- longhorn/longhorn#8624
- longhorn/longhorn#8625
Add setting reference for new `support-bundle-node-collection-timeout` setting.
`None`
`None`

doc(1.7.0/1.6.3/1.5.6): add support bundle node collection timeout setting

---

content/docs/1.7.0/best-practices.md
content/docs/1.7.0/references/helm-values.md
content/docs/1.7.0/references/settings.md
content/docs/1.7.0/references/storage-class-parameters.md

longhorn/longhorn#2187
- Document the new freeze related global and volume-specific settings.
- Since there are now three different reasons we recommend a particular kernel version, make it easy to find all three recommendations.

Add Freeze File System For Snapshot documentation

---

content/docs/1.5.0/advanced-resources/backing-image.md
content/docs/1.5.1/advanced-resources/backing-image.md
content/docs/1.5.2/advanced-resources/backing-image.md
content/docs/1.5.3/advanced-resources/backing-image.md
content/docs/1.5.4/advanced-resources/backing-image.md
content/docs/1.5.5/advanced-resources/backing-image.md
content/docs/1.5.6/advanced-resources/backing-image.md
content/docs/1.6.0/advanced-resources/backing-image/backing-image.md
content/docs/1.6.1/advanced-resources/backing-image/backing-image.md
content/docs/1.6.2/advanced-resources/backing-image/backing-image.md
content/docs/1.6.3/advanced-resources/backing-image/backing-image.md
content/docs/1.7.0/advanced-resources/backing-image/backing-image.md

[[IMPROVEMENT] BackingImage UI improvement](https://github.com/longhorn/longhorn/issues/7293)
Issue #
[[IMPROVEMENT] BackingImage UI improvement](https://github.com/longhorn/longhorn/issues/7293)
- Update backing image clean up action due to the [PR moves clean up into backing image detail modal](https://github.com/longhorn/longhorn-ui/pull/729) (for v1.7.0 and v1.6.3) 
- Fix extra left parentheses in the end of backing-image.md for all versions.
**Before fix**
**After fix**

Update backing image clean up action according to latest UI change

---

content/docs/1.5.6/deploy/important-notes/index.md
content/docs/1.6.3/deploy/important-notes/index.md

longhorn/longhorn#8488
I was previously not planning on backporting the changes for longhorn/longhorn#8488. Now that we are backporting the changes, they need to be documented in the appropriate releases.

Document minimum XFS volume size backport

---

content/docs/1.7.0/monitoring/metrics.md

ref: https://github.com/longhorn/longhorn/issues/7563
Add backup backing image and backing image metrics .

doc(metrics): add backing image and backup backing image metrics

---

content/docs/1.5.0/deploy/install/_index.md
content/docs/1.5.1/deploy/install/_index.md
content/docs/1.5.2/deploy/install/_index.md
content/docs/1.5.3/deploy/install/_index.md
content/docs/1.5.4/deploy/install/_index.md
content/docs/1.5.5/deploy/install/_index.md
content/docs/1.5.6/deploy/install/_index.md
content/docs/1.6.0/deploy/install/_index.md
content/docs/1.6.1/deploy/install/_index.md
content/docs/1.6.2/deploy/install/_index.md
content/docs/1.6.3/deploy/install/_index.md
content/docs/1.7.0/deploy/install/_index.md

Issue https://github.com/longhorn/longhorn/issues/8697
To inform SUSE users that they need `kernel-default` installed to get the `iscsi_tcp` module, vs. `kernel-default-base` which is a minimal kernel package for use on VMs.
I've only updated the 1.6.2 docs initially, just in case my text needs rewording or moving or whatever. Once everyone's happy with the text, I'll add this update to other versions as well.

Mention kernel-default-base doesn't include iscsi_tcp

---

content/kb/troubleshooting-volume-cannot-attach-due-to-orphan-pending-node-id-or-longhorn-ui-ad-ticket.md

longhorn/longhorn#7994
longhorn/longhorn#8339

Add KB: After upgrading Longhorn, Volume Cannot Attach Because of The Leftover non-empty volume.status.PendingNodeID or Longhorn UI Attachment Ticket

---

content/docs/1.7.0/deploy/important-notes/index.md
content/docs/1.7.0/references/settings.md

Issue # [[UI][IMPROVEMENT] Improve the UX of updating danger zone settings](https://github.com/longhorn/longhorn/issues/8071)
Due to UI PR change, the unapplied danger zone settings will show up on the top of danger zone block.
See recording in https://github.com/longhorn/longhorn-ui/pull/735
N/A
N/A

docs(1.7.0): update danger zone settings block

---

content/docs/1.7.0/advanced-resources/system-backup-restore/backup-longhorn-system.md
content/docs/1.7.0/advanced-resources/system-backup-restore/restore-longhorn-system.md

ref: https://github.com/longhorn/longhorn/issues/5085
support backup backing image in system backup restore

doc(system restore): support backup backing image in system backup restore

---

content/docs/1.7.0/v2-data-engine/prerequisites.md

Issue #7703 #7697 #7693 #7559
Kernel >= 6.7 is recommended to avoid memory corruption inside the system when IO timeouts happen massively between nvme-tcp driver and SPDK. This release contain a better error handling.

docs(1.7.0): update v2-data-engine/prerequisites.md

---

content/docs/1.7.0/high-availability/auto-balance-replicas.md
content/docs/1.7.0/references/settings.md

Issue longhorn/longhorn#4105
Add a new `Replica Auto Balance Disk Pressure Threshold` setting.
https://github.com/longhorn/longhorn/pull/7576

doc(1.7.0): add `Replica Auto Balance Disk Pressure Threshold` setting

---

content/docs/1.5.0/snapshots-and-backups/backup-and-restore/_index.md
content/docs/1.5.1/snapshots-and-backups/backup-and-restore/_index.md
content/docs/1.5.2/snapshots-and-backups/backup-and-restore/_index.md
content/docs/1.5.3/snapshots-and-backups/backup-and-restore/_index.md
content/docs/1.5.4/snapshots-and-backups/backup-and-restore/_index.md
content/docs/1.5.5/snapshots-and-backups/backup-and-restore/_index.md
content/docs/1.5.6/snapshots-and-backups/backup-and-restore/_index.md
content/docs/1.6.0/snapshots-and-backups/backup-and-restore/_index.md
content/docs/1.6.1/snapshots-and-backups/backup-and-restore/_index.md
content/docs/1.6.2/snapshots-and-backups/backup-and-restore/_index.md
content/docs/1.6.3/snapshots-and-backups/backup-and-restore/_index.md
content/docs/1.7.0/snapshots-and-backups/backup-and-restore/_index.md

See [PR 856](https://github.com/longhorn/website/pull/856/).
Changes from PR 856 must be applied to all other active versions.

Apply editorial updates from Alex's old PR

---

content/docs/1.7.0/snapshots-and-backups/backup-and-restore/create-a-backup.md
content/docs/1.7.0/snapshots-and-backups/scheduling-backups-and-snapshots.md

ref: https://github.com/longhorn/longhorn/issues/7070
Add documents for full backup support
This feature depends on the UI, so the documents focus on the UI operation.

doc(backup): add full backup support doc

---

content/docs/1.7.0/advanced-resources/deploy/storage-network.md
content/docs/1.7.0/deploy/important-notes/index.md
content/docs/1.7.0/references/settings.md

Issue longhorn/longhorn#8184
Add storage Network Support for Read-Write-Many (RWX) Volume.
`None`
https://github.com/longhorn/longhorn/pull/8616

doc(storage-network): support RWX volumes

---

content/docs/1.6.3/references/helm-values.md
content/docs/1.7.0/references/helm-values.md

longhorn/longhorn#8142
~Will hold off on this one until https://github.com/longhorn/longhorn/pull/8985 and its backports merge so I can make all website changes in one go.~

docs(metrics): add additional serviceMonitor helm variables

---

content/docs/1.7.0/deploy/install/_index.md

Updates the doc as the SUSE/OpenSUSE section does not cover enabling and starting the iscsid service
`longhorn-test-01:~ # systemctl enable iscsid
Created symlink /etc/systemd/system/multi-user.target.wants/iscsid.service → /usr/lib/systemd/system/iscsid.service.`

update install doc to enable and start iscsi

---

content/docs/1.5.0/references/networking.md
content/docs/1.5.1/references/networking.md
content/docs/1.5.2/references/networking.md
content/docs/1.5.3/references/networking.md
content/docs/1.5.4/references/networking.md
content/docs/1.5.5/references/networking.md
content/docs/1.5.6/references/networking.md
content/docs/1.6.0/references/networking.md
content/docs/1.6.1/references/networking.md
content/docs/1.6.2/references/networking.md
content/docs/1.6.3/references/networking.md
content/docs/1.7.0/references/networking.md

See https://github.com/longhorn/longhorn/pull/9077 for context.

doc(network): remove references to outdated NetworkPolicy examples

---

content/docs/1.7.0/deploy/important-notes/index.md
content/docs/1.7.0/v2-data-engine/prerequisites.md
content/docs/1.7.0/v2-data-engine/quick-start.md

Issue Longhorn/longhorn#9182
According to the [SPDK System Configuration User Guide](https://spdk.io/doc/system_configuration.html), neither uio_pci_generic nor vfio_pci is universally suitable for all devices and environments. Therefore, the preflight installation enables both uio_pci_generic and vfio_pci kernel modules, allowing spdk/setup.sh to automatically select the appropriate module.

doc(spdk): enable uio_pci_generic and vfio_pci kernel modules

---

content/docs/1.7.0/deploy/uninstall/_index.md

https://github.com/longhorn/longhorn/issues/9116
This is an addendum to the section on forcible cleanup.  The user may hit Longhorn webhooks that are still registered although the services have been uninstalled.  Here's how to fix that.

doc(uninstall): Add tip about working around missing webhook service.

---

content/docs/1.7.0/high-availability/rwx-volume-fast-failover.md

longhorn/longhorn#9212
We plan to update the documentation to include details on:
- Number of API requests
- RPC rate
- Memory usage
- Longhorn Manager CPU/RAM usage
- Share Manager CPU/RAM usage
After enabling the Fast Failover feature, we observed increases in these metrics. The data we collected during testing can serve as a valuable reference for users. After discussing this in the QA meeting, we concluded that adding these test results to our documentation would be beneficial. It will help users better understand the impact of enabling the Fast Failover feature on system performance.
@jillian-maroket @PhanLe1010 @james-munson @longhorn/qa 
- https://github.com/longhorn/longhorn/issues/6205#issuecomment-2261144378
- https://github.com/longhorn/longhorn/issues/6205#issuecomment-22626259 …

docs(v1.7.0): Add performance testing about rwx volume fast failover

---

content/docs/1.6.3/deploy/install/_index.md
content/docs/1.7.0/advanced-resources/os-distro-specific/container-optimized-os-support.md
content/docs/1.7.0/deploy/install/_index.md

Issue https://github.com/longhorn/longhorn/issues/8855
Old exemplar commands won't work once namespace is changed
https://github.com/longhorn/longhorn/pull/8856

Update docs to reference longhorn namespace for installation daemonsets

---

content/docs/1.5.0/deploy/upgrade/_index.md
content/docs/1.5.1/deploy/upgrade/_index.md
content/docs/1.5.2/deploy/upgrade/_index.md
content/docs/1.5.3/deploy/upgrade/_index.md
content/docs/1.5.4/deploy/upgrade/_index.md
content/docs/1.5.5/deploy/upgrade/_index.md
content/docs/1.5.6/deploy/upgrade/_index.md
content/docs/1.6.0/deploy/upgrade/_index.md
content/docs/1.6.1/deploy/upgrade/_index.md
content/docs/1.6.2/deploy/upgrade/_index.md
content/docs/1.6.3/deploy/upgrade/_index.md
content/docs/1.7.0/deploy/upgrade/_index.md
content/docs/1.7.1/deploy/upgrade/_index.md
content/docs/1.8.0/deploy/upgrade/_index.md

Issue #9291
This PR removes downgrade examples from the table that explains the supported upgrade paths. Longhorn does not support downgrades at all so those examples do not provide any value to users and may even cause confusion.

Remove downgrade examples from upgrade path table

---

content/docs/1.7.1/references/settings.md
content/docs/1.8.0/references/settings.md

Longhorn 8711
longhorn/longhorn#8711
We need to clarify how the behavior of the `engine-replica-timeout` setting changes in v1.7.1 and v1.8.0.
Per https://github.com/longhorn/longhorn/wiki/Longhorn-Setting-Update, the actual setting definition stored in longhorn-manager should continue to be a one sentence description, so I think we only need to make the change here in the website.
I changed the heading from `Engine to Replica Timeout` to `Engine Replica Timeout` because the actual setting name is `engine-replica-timeout` and I think the "to" might be confusing to users looking for the setting to modify in their environments.

docs: describe new last replica timeout behavior

---

content/docs/1.8.0/important-notes/_index.md

Issue longhorn/longhorn#6613
Add DR volume support for the v2 data engine in the important note.
`None`
`None`

doc(1.8.0): add DR volumes support for v2 data engine

---

content/docs/1.7.0/important-notes/_index.md
content/docs/1.7.1/important-notes/_index.md

Add "Add "Volume Locality for RWX Volumes"
Issue #

docs(1.7.1): update important-notes

---

content/docs/1.8.0/advanced-resources/os-distro-specific/talos-linux-support.md
content/docs/1.8.0/important-notes/_index.md

Issue longhorn/longhorn#7791
Add important notes and instructions outlining the v2 engine support for Talos Linux.
`None`
`None`

doc(talos): v2 engine support

---

content/docs/1.7.1/important-notes/_index.md
content/docs/1.7.1/references/settings.md
content/docs/1.8.0/important-notes/_index.md
content/docs/1.8.0/references/settings.md

longhorn/longhorn#8711
Follow up to https://github.com/longhorn/website/pull/978#issuecomment-2321588862 to address:
- https://github.com/longhorn/website/pull/978#issuecomment-2319481190
- https://github.com/longhorn/website/pull/978#pullrequestreview-2271431204

docs: add last replica timeout behavior to important notes

---

content/docs/1.8.0/monitoring/metrics.md

Issue longhorn/longhorn-manager#3034
Add new field in Backup metrics

docs(1.8.0): Add new label to backup metrics for #3034

---

content/docs/1.7.1/best-practices.md
content/docs/1.7.2/best-practices.md
content/docs/1.8.0/best-practices.md

docs: update Kubernetes Version in Best Practices

---

content/docs/1.8.0/monitoring/metrics.md

ref: https://github.com/longhorn/longhorn/issues/8508
Export the metrics in the following form
- metric name: `longhorn_volume_file_system_read_only`
- type: gauge
- if the volume becomes read-only, it has metric value 1 with the corresponding labels
- So you know which volume is in read-only mode now
- You can sum up the metrics to see how many volumes are in read-only mode now 
```
longhorn_volume_file_system_read_only{node="kworker1",pvc="nginx",pvc_namespace="default",volume="pvc-3a7a208b-c8c9-46a9-b2ce-4c5f740c8673"} 1
```
Note:
If Longhorn remounts the mount point to read-write successfully, the metrics will be cleaned up.
The metric is either 1 or no record for each volume

doc(metric): add volume read only metric

---

content/docs/1.6.4/best-practices.md
content/docs/1.7.2/best-practices.md
content/docs/1.8.0/best-practices.md

Issue `None`
Recommend setting the replica auto-balance setting option to least-effort as best practice for the production environment.
https://suse.slack.com/archives/C02CLV7D2KH/p1726814707259759

doc(1.8.0): add replica auto-balance to best-practice

---

content/docs/1.8.0/deploy/install/_index.md
content/docs/1.8.0/important-notes/_index.md

Issue longhorn/longhorn#9561
Update the minimum supported Kubernetes version for Longhorn, as the longhornio/csi-snapshotter [v8.1.0 requires Kubernetes 1.25](https://github.com/kubernetes-csi/external-snapshotter/releases/tag/v8.1.0).
`None`
`None`

doc(1.8.0): update minimum supported Kubernetes version to 1.25

---

content/docs/1.6.3/references/settings.md
content/docs/1.7.2/references/settings.md
content/docs/1.8.0/references/settings.md

Issue # longhorn/longhorn#9391
Modify the setting `Default Longhorn Static Storage Class Name` description.

doc(setting): modify the setting description

---

content/docs/1.8.0/advanced-resources/system-backup-restore/backup-longhorn-system.md
content/docs/1.8.0/important-notes/_index.md

Issue longhorn/longhorn#6027
- Update important note.
- Update the policy description.
`None`
`None`

doc(1.8.0): system backup's if-not-present volume backup policy

---

content/docs/1.8.0/important-notes/_index.md

Issue longhorn/longhorn#8430
Add important notes about auto-salvage support for v2 volumes.
`None`
https://github.com/longhorn/longhorn/pull/9486

doc(1.8.0): auto-salvage support for v2 volumes

---

content/docs/1.8.0/important-notes/_index.md
content/docs/1.8.0/nodes-and-volumes/volumes/expansion.md

Issue https://github.com/longhorn/longhorn/issues/9736
Document changes to RWX online expansion sequence.

doc(1.8.0): add automatic RWX expansion

---

content/docs/1.7.2/v2-data-engine/prerequisites.md

Issue #
The kernel module name 'nvme_tcp' was incorrectly documented as 'nvme-tcp'. 
This commit corrects the module name to ensure consistency with the actual kernel module naming convention.

docs: correct module name from nvme-tcp to nvme_tcp

---

content/docs/1.6.0/high-availability/data-locality.md
content/docs/1.6.1/high-availability/data-locality.md
content/docs/1.6.2/high-availability/data-locality.md
content/docs/1.6.3/high-availability/data-locality.md
content/docs/1.6.4/high-availability/data-locality.md
content/docs/1.7.0/high-availability/data-locality.md
content/docs/1.7.1/high-availability/data-locality.md
content/docs/1.7.2/high-availability/data-locality.md
content/docs/1.7.3/high-availability/data-locality.md
content/docs/1.8.0/high-availability/data-locality.md

Issue longhorn/longhorn#6735
Data locality strict-local mode is now incompatible with RWX volume from v1.8.0.

doc(1.8.0, 1.7, 1.6): update strict-local restriction

---

content/docs/1.6.3/deploy/accessing-the-ui/longhorn-ingress.md
content/docs/1.6.4/deploy/accessing-the-ui/longhorn-ingress.md
content/docs/1.7.0/deploy/accessing-the-ui/longhorn-ingress.md
content/docs/1.7.1/deploy/accessing-the-ui/longhorn-ingress.md
content/docs/1.7.2/deploy/accessing-the-ui/longhorn-ingress.md
content/docs/1.7.3/deploy/accessing-the-ui/longhorn-ingress.md
content/docs/1.8.0/deploy/accessing-the-ui/longhorn-ingress.md

Add missing ingressClassName
Issue #
After going through Longhorn's documentation, I came across this code snippet to setup Longhorn ingress. It the text above the code snippet, it says it's using nginx as Ingress Controller but the Longhorn Ingress definition is missing the ingressClassName property, which is key to make it work.

Update longhorn-ingress.md. Add missing ingressClassName to ingress .yaml

---

content/docs/1.6.4/advanced-resources/security/volume-encryption.md
content/docs/1.6.4/nodes-and-volumes/volumes/expansion.md
content/docs/1.7.3/advanced-resources/security/volume-encryption.md
content/docs/1.7.3/nodes-and-volumes/volumes/expansion.md
content/docs/1.8.0/advanced-resources/security/volume-encryption.md
content/docs/1.8.0/nodes-and-volumes/volumes/expansion.md

Issue longhorn/longhorn#9902
Longhorn supports online encrypted volume expansion IF Kubernetes supports.
Online encrypted volume expansion may need to be enabled by cluster admin:
- Kubernetes v1.29+: this feature is enabled by default
- Kubernetes v1.25 to v1.28: feature gate is required
In a Kubernetes cluster which supports online encrypted volume expansion, this can be enabled by attaching required parameters in `StorageClass`.

doc(1.8.0, 1.7, 1.6): online volume expansion for encrypted volumes

---

content/kb/troubleshooting-manager-stuck-in-crash-loop-state-due-to-inaccessible-webhook.md

ref: https://github.com/longhorn/longhorn/issues/8293
add a kb for troubleshooting webhook not accessible issue
1. firewall issue
2. dns issue
3. hairpin setting issue

doc: add kb for troubleshooting webhook not accessible issue

---

content/docs/1.9.0/advanced-resources/deploy/storage-network.md
content/docs/1.9.0/important-notes/_index.md

Issue longhorn/longhorn#6450
- Add feature to important note.
- Add the issue link on the storage network page.
`None`
`None`

doc(1.9.0): storage network with v2 data engine

---

content/docs/1.7.0/advanced-resources/backing-image/backing-image.md
content/docs/1.7.1/advanced-resources/backing-image/backing-image.md
content/docs/1.7.2/advanced-resources/backing-image/backing-image.md
content/docs/1.7.3/advanced-resources/backing-image/backing-image.md
content/docs/1.7.4/advanced-resources/backing-image/backing-image.md
content/docs/1.8.0/advanced-resources/backing-image/backing-image.md
content/docs/1.8.1/advanced-resources/backing-image/backing-image.md
content/docs/1.8.2/advanced-resources/backing-image/backing-image.md
content/docs/1.9.0/advanced-resources/backing-image/backing-image.md
content/kb/troubleshooting-backing-image-creation-is-stuck-or-has-failed.md

ref: https://github.com/longhorn/longhorn/issues/10536
- A KB address the limitation that BackingImage should be multiple of 512B
- Provide a workaround to convert the image to multiple of 512B 
- Add the limitation to the document

doc: add the limitation of backing image size to doc and add a KB

---

content/kb/troubleshooting-longhorn-manager-crashes-due-to-backing-image-eviction.md

ref: https://github.com/longhorn/longhorn/issues/10464

doc: add kb for manager crashing due to backing image eviction nil pointer

---

content/docs/1.9.0/important-notes/_index.md

Issue longhorn/longhorn#10250
CRD longhorn.io/v1beta1 is deprecated since v1.9.0, and will be removed at v1.10.0

doc(v1.9.0): deprecate v1beta1 CRDs

---

content/docs/1.9.0/deploy/install/_index.md
content/docs/1.9.0/deploy/install/install-with-argocd.md
content/docs/1.9.0/deploy/install/install-with-fleet.md
content/docs/1.9.0/deploy/install/install-with-flux.md
content/docs/1.9.0/deploy/install/install-with-helm-controller.md
content/docs/1.9.0/deploy/install/install-with-helm.md
content/docs/1.9.0/deploy/install/install-with-kubectl.md
content/docs/1.9.0/deploy/install/install-with-rancher.md
content/docs/1.9.0/important-notes/_index.md
content/docs/1.9.0/nodes-and-volumes/volumes/rwx-volumes.md
content/docs/1.9.0/v2-data-engine/quick-start.md

Issue Longhorn/longhorn#9239
environment_check.sh is removed since Longhorn v1.9.0 and is replaced by longhornctl.

docs(1.9.0): remove environment_check.sh

---

content/kb/troubleshooting-recurring-job-pod-stuck-pending-state.md

Issue longhorn/longhorn#7956
Add KB to resolve the recurring job pod that remains stuck in the `Pending` state after node reboot.
Longhorn doesn't manage the lifecycle of the cronjob pod; this is an upstream issue.
`None`

doc(kb): recurring job pod stuck in pending state

---

content/docs/1.9.0/advanced-resources/data-recovery/export-from-replica.md

Issue longhorn/longhorn#10714
This PR updates the [Export from Replica](https://longhorn.io/docs/1.8.1/advanced-resources/data-recovery/export-from-replica/) documentation to include instructions for RKE2 with containerd.
The current documentation only covers Docker-based installs (RKE1), but RKE2 has become the new standard and uses containerd as its container runtime. Adding RKE2 steps ensures users on newer Rancher Kubernetes distributions can follow accurate recovery procedures.
N/A
N/A

doc: Add documentation for replica recovery on RKE2 and k3s

---

content/docs/1.6.5/important-notes/_index.md
content/docs/1.7.4/important-notes/_index.md
content/docs/1.8.2/important-notes/_index.md
content/docs/1.9.0/important-notes/_index.md

ref: https://github.com/longhorn/longhorn/issues/10644

doc: add important note of the introduction of upgrade path crd validation

---

content/docs/1.6.0/deploy/important-notes/index.md
content/docs/1.6.0/deploy/upgrade/_index.md
content/docs/1.6.1/deploy/important-notes/index.md
content/docs/1.6.1/deploy/upgrade/_index.md
content/docs/1.6.2/deploy/important-notes/index.md
content/docs/1.6.2/deploy/upgrade/_index.md
content/docs/1.6.3/deploy/important-notes/index.md
content/docs/1.6.3/deploy/upgrade/_index.md
content/docs/1.6.4/deploy/important-notes/index.md
content/docs/1.6.4/deploy/upgrade/_index.md
content/docs/1.6.5/deploy/important-notes/index.md
content/docs/1.6.5/deploy/upgrade/_index.md
content/docs/1.7.0/deploy/upgrade/_index.md
content/docs/1.7.0/important-notes/_index.md
content/docs/1.7.1/deploy/upgrade/_index.md
content/docs/1.7.1/important-notes/_index.md
content/docs/1.7.2/deploy/upgrade/_index.md
content/docs/1.7.2/important-notes/_index.md
content/docs/1.7.3/deploy/upgrade/_index.md
content/docs/1.7.3/important-notes/_index.md
content/docs/1.7.4/deploy/upgrade/_index.md
content/docs/1.7.4/important-notes/_index.md
content/docs/1.8.0/deploy/upgrade/_index.md
content/docs/1.8.0/important-notes/_index.md
content/docs/1.8.1/deploy/upgrade/_index.md
content/docs/1.8.1/important-notes/_index.md
content/docs/1.8.2/deploy/upgrade/_index.md
content/docs/1.8.2/important-notes/_index.md
content/docs/1.9.0/deploy/upgrade/_index.md
content/docs/1.9.0/important-notes/_index.md

ref: https://github.com/longhorn/longhorn/issues/10633
- by creating a system backup, we can ensure all the critical resources such as volumes and backing images are backed up and can be restored if there is any issue.

doc: suggest create a system backup before upgrade

---

content/docs/1.9.0/snapshots-and-backups/backup-and-restore/set-backup-target.md

…tent
[#10858](https://github.com/longhorn/longhorn/issues/10858#issue-3043315520)
The `BackupTargetSecret` was removed in UI. There is no such field `Settings/General/BackupTargetSecret`.
Update the doc and add additional notes about create S3 compatible object storage section.
Update the topics table automatically.

dock(1.9.0): update backup target creation notes and update table

---

content/docs/1.8.0/snapshots-and-backups/backup-and-restore/set-backup-target.md
content/docs/1.8.1/snapshots-and-backups/backup-and-restore/set-backup-target.md
content/docs/1.8.2/snapshots-and-backups/backup-and-restore/set-backup-target.md

…tent
[#10858](https://github.com/longhorn/longhorn/issues/10858#issue-3043315520)
The `BackupTargetSecret` was removed in UI. There is no such field `Settings/General/BackupTargetSecret`.
Update the doc and add additional notes about create S3 compatible object storage section.

docs(1.8.x): update backup target creation notes

---

content/docs/1.9.0/best-practices.md

Issue https://github.com/longhorn/longhorn/issues/10756
Update kubernetes version to v1.33 in v1.9.0 best practice page
release date
- https://kubernetes.io/blog/2025/04/23/kubernetes-v1-33-release/?utm_source=chatgpt.com
end of life
- https://kubernetes.io/releases/?utm_source=chatgpt.com

docs(1.9.0): update support kubernetest version

---

content/kb/troubleshooting-orphan-instance.md

Longhorn 6764
Issue longhorn/longhorn#6764
Provide an workaround to clearing up the orphaned instance manually without v1.9.0 orphan controller.

doc(kb): workaround to cleanup orphaned instances without orphan cr

---

content/docs/1.9.0/important-notes/_index.md

Issue longhorn/longhorn#10805
V2 backing image cannot be live upgrade from v1.8.x.

docs(1.9.0): important notes for v2 backing image incompatibility

---

content/docs/1.8.2/important-notes/_index.md

Longhorn 10969
Backport #1102 to v1.8.2.
Issue longhorn/longhorn#10969
https://github.com/longhorn/longhorn/issues/10805

docs(1.8.2): important notes for v2 backing image incompatibility

---

content/blog/longhorn-v1.9.0.md

Adding blogpost for v1.9.0 release from [this doc](https://docs.google.com/document/d/1ispL9sj-9CEBRW9jRl_ev0X-keoxmQpdZrpRZ7wW9QE/edit?usp=sharing)

blog: Add v1.9.0 release blog

---

config.toml
content/community/_index.md
layouts/community/list.html
layouts/community/single.html
layouts/partials/community/content.html

[Issue](https://github.com/longhorn/longhorn/issues/10890)
This PR adds the Longhorn community page. I have added clear sections for community channels, social media links, and detailed guidance on interacting via GitHub. 
- I have structured the new content logically with clear headings for readability.
- All provided Slack, mailing list, and social media links (X, LinkedIn, Bluesky, YouTube) are integrated.
- The GitHub section now clearly outlines how to report issues, participate in discussions, and contribute code.
N/A

Adding community page in the website

---

content/docs/1.9.0/snapshots-and-backups/scheduling-backups-and-snapshots.md

Issue #
The docs for v1.9.0, v1.9.1 and v1.10 examples on the following pages points to CRDs with apiVersion `longhorn.io/v1beta1`:
- [Recurring Snapshots and Backups](https://longhorn.io/docs/1.9.0/snapshots-and-backups/scheduling-backups-and-snapshots/)
- [CSI VolumeSnapshot Associated with Longhorn BackingImage](https://longhorn.io/docs/1.9.0/snapshots-and-backups/csi-snapshot-support/csi-volume-snapshot-associated-with-longhorn-backing-image/)
This PR changes the examples using deprecated crd apiVersion v1beta1 to v1beta2
I have installed helm chart 1.9.0, and created a recurring job shown in the example
```yaml
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
name: snapshot-1
namespace: longhorn-system
spec:
cron: "* * * * *"
task: "snapshot"
groups:
- default
- group1 …
```

docs(1.9.0): Update examples using deprecated crd version v1beta1 to v1beta2 on 1.9.0

---

content/kb/troubleshooting-failed-replicas-with-backing-images-remain-on-evicted-nodes.md

Issue longhorn/longhorn#11053
Workaround to users to cleanup the failed backing image volume replicas

doc: add kb for clearing failed backing image replica on evicted nodes

---

content/docs/1.10.0/snapshots-and-backups/scheduling-backups-and-snapshots.md
content/docs/1.9.1/snapshots-and-backups/scheduling-backups-and-snapshots.md

Issue https://github.com/longhorn/longhorn/issues/11019
This PR changes the examples using deprecated crd apiVersion v1beta1 to v1beta2
This PR is a continuation of previous [PR](https://github.com/longhorn/website/pull/1127) that made changes for the already released v1.9.0

docs(1.9.1, 1.10.0): Update examples using deprecated CRD apiVersion

---

content/docs/1.10.0/deploy/install/airgap.md
content/docs/1.6.0/deploy/install/airgap.md
content/docs/1.6.1/deploy/install/airgap.md
content/docs/1.6.2/deploy/install/airgap.md
content/docs/1.6.3/deploy/install/airgap.md
content/docs/1.6.4/deploy/install/airgap.md
content/docs/1.6.5/deploy/install/airgap.md
content/docs/1.7.0/deploy/install/airgap.md
content/docs/1.7.1/deploy/install/airgap.md
content/docs/1.7.2/deploy/install/airgap.md
content/docs/1.7.3/deploy/install/airgap.md
content/docs/1.7.4/deploy/install/airgap.md
content/docs/1.8.0/deploy/install/airgap.md
content/docs/1.8.1/deploy/install/airgap.md
content/docs/1.8.2/deploy/install/airgap.md
content/docs/1.8.3/deploy/install/airgap.md
content/docs/1.9.0/deploy/install/airgap.md
content/docs/1.9.1/deploy/install/airgap.md

Issue longhorn/longhorn#11237
Remove defaultSettings.registrySecret from air gap installation

docs: remove defaultSettings.registrySecret from air gap installation

---

content/docs/1.10.0/references/storage-class-parameters.md
content/docs/1.7.0/references/storage-class-parameters.md
content/docs/1.7.1/references/storage-class-parameters.md
content/docs/1.7.2/references/storage-class-parameters.md
content/docs/1.7.3/references/storage-class-parameters.md
content/docs/1.7.4/references/storage-class-parameters.md
content/docs/1.8.0/references/storage-class-parameters.md
content/docs/1.8.1/references/storage-class-parameters.md
content/docs/1.8.2/references/storage-class-parameters.md
content/docs/1.8.3/references/storage-class-parameters.md
content/docs/1.9.0/references/storage-class-parameters.md
content/docs/1.9.1/references/storage-class-parameters.md
content/docs/1.9.2/references/storage-class-parameters.md
content/docs/archives/1.6.0/references/storage-class-parameters.md
content/docs/archives/1.6.1/references/storage-class-parameters.md
content/docs/archives/1.6.2/references/storage-class-parameters.md
content/docs/archives/1.6.3/references/storage-class-parameters.md
content/docs/archives/1.6.4/references/storage-class-parameters.md
content/docs/archives/1.6.5/references/storage-class-parameters.md

Issue https://github.com/longhorn/longhorn/issues/11409
The space trimming is applied automatically by the IDE. If it's not needed, I will update the PR

fix: storageclass example still uses the deprecated data engine fields

---

content/docs/1.10.0/troubleshoot/troubleshooting.md

doc(troubleshooting): sync agent profiler usage

---

content/docs/1.10.0/snapshots-and-backups/backup-and-restore/configure-backup-block-size.md

Issue longhorn/longhorn#5215
Inside the volume creation dialog, specify the backup block size in the `Advanced Configurations`.
Ticket for UI change: longhorn/longhorn#11351

doc(backup): backup block size for volume creation

---

content/docs/1.10.0/important-notes/_index.md
content/docs/1.10.0/references/settings.md
content/docs/1.10.0/v2-data-engine/features/interrupt-mode.md

Issue longhorn/longhorn#9834
- Update setting reference
- Adds documentation for the new interrupt mode support in the V2 data engine.
- Adds important note

doc(1.10.0): v2 interrupt mode support

---

content/docs/1.10.0/advanced-resources/deploy/customizing-default-settings.md
content/docs/1.10.0/v2-data-engine/features/replica-rebuild-qos.md

Issue https://github.com/longhorn/longhorn/issues/11690
Due to the possibility of collisions with other CRDs, do not use the simple `settings`, but rather use `settings.longhorn.io` or `lhs` instead.
There are more updates to the docs for the older releases. What is the policy  for correcting old documentation ?
```
$ git grep "kubectl.* settings " | wc -l
48
```
The correct use of settings is common.
```
$ git grep "kubectl.* settings.longhorn.io " | wc -l
115
```

docs: update settings.longhorn.io for kubectl

---

content/docs/1.10.0/nodes-and-volumes/nodes/scheduling.md

none
There is no setting "hard anti-affinity"

doc(scheduling): remove non-existed setting "hard anti-affinity"

---

content/docs/1.10.0/nodes-and-volumes/volumes/pvc-ownership-and-permission.md
content/docs/1.10.1/nodes-and-volumes/volumes/pvc-ownership-and-permission.md
content/docs/1.11.0/nodes-and-volumes/volumes/pvc-ownership-and-permission.md
content/docs/1.8.0/nodes-and-volumes/volumes/pvc-ownership-and-permission.md
content/docs/1.8.1/nodes-and-volumes/volumes/pvc-ownership-and-permission.md
content/docs/1.8.2/nodes-and-volumes/volumes/pvc-ownership-and-permission.md
content/docs/1.8.3/nodes-and-volumes/volumes/pvc-ownership-and-permission.md
content/docs/1.9.0/nodes-and-volumes/volumes/pvc-ownership-and-permission.md
content/docs/1.9.1/nodes-and-volumes/volumes/pvc-ownership-and-permission.md
content/docs/1.9.2/nodes-and-volumes/volumes/pvc-ownership-and-permission.md
content/docs/1.9.3/nodes-and-volumes/volumes/pvc-ownership-and-permission.md

incorrect accessMode mentioned in pvc-ownership-and-permission doc.
So that the correct accessmode is used

Describe with proper accessMode
